{
  "hash": "dd7a71e527ae07c0fd69cb5a4e5e70cb",
  "result": {
    "markdown": "---\ntitle: \"Two-Way ANOVA Model Selection Process\"\nformat: html\neditor: visual\nexecute: \n  warning: false\n  message: false\n---\n\n\n\n\nWe will be using a \"backward\" selection process for deciding on the \"best\" ANOVA model. Meaning, we will start with a more complicated model and decide if it is \"worth it.\"\n\n# Step 1 -- Fit an Interaction Two-Way ANOVA\n\n## Plot the model\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](twa-model-selection-process_files/figure-html/twa-plot-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n**What are we looking for?**\n\nWe are looking to see if relationship between the mean of $y$ and explanatory variable 1 changes over the values of explanatory variable 2. This is akin to looking for evidence of different slopes in a multiple linear regression.\n\nFor these data we are looking to see if the relationship between the mean movie rating and the genre of the movie changes over the different eras.\n\n## Fit the model\n\n*Notice I'm using a `*` for an interaction model!*\n\n\n::: {.cell}\n\n```{.r .cell-code}\naov(rating ~ era * genre, data = movies) %>% \n  tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 4 × 6\n  term         df  sumsq meansq statistic p.value\n  <chr>     <dbl>  <dbl>  <dbl>     <dbl>   <dbl>\n1 era           3   4.59   1.53     0.659   0.581\n2 genre         1   4.19   4.19     1.81    0.185\n3 era:genre     3   3.32   1.11     0.477   0.700\n4 Residuals    48 111.     2.32    NA      NA    \n```\n:::\n:::\n\n\n## Perform a Hypothesis Test\n\nThe `era:genre` line of the ANOVA table is testing if the mean movie rating and the genre of the movie changes over the different eras. It has the following hypotheses:\n\n$H_0$: The relationship between the mean movie rating and the genre of the movie does not change over the eras\n\n$H_A$: The relationship between the mean movie rating and the genre of the movie is different for at least one era\n\nWith a p-value of 0.7 (from an F-statistic of 0.477 with 3 and 48 degrees of freedom) at a significance level of 0.1, I fail to reject the null hypothesis. Thus, the data have unconvincing evidence that the mean movie rating and the genre of the movie is different for at least one era.\n\nSo, my next step is to fit an **additive** two-way ANOVA.\n\n# Step 2: Fit an Additive Two-Way ANOVA\n\nWe are looking to see if the mean of $y$ differs across the values of explanatory variable 1 and / or explanatory variable 2. This is akin to fitting a parallel slopes model in a multiple linear regression, where the y-intercept is the estimated change in the mean of $y$ for each group and the slope is the estimated relationship between the explanatory variable and the mean of $y$.\n\nFor these data we are looking to see if the genres have differences in the mean movie ratings **and** if the eras have differences in the mean movie rating.\n\n## Fit the Model\n\n*Notice I'm using a `+` for an interaction model!*\n\n\n::: {.cell}\n\n```{.r .cell-code}\naov(rating ~ era + genre, data = movies) %>% \n  tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 6\n  term         df  sumsq meansq statistic p.value\n  <chr>     <dbl>  <dbl>  <dbl>     <dbl>   <dbl>\n1 era           3   4.59   1.53     0.680   0.568\n2 genre         1   4.19   4.19     1.86    0.178\n3 Residuals    51 115.     2.25    NA      NA    \n```\n:::\n:::\n\n\n## Perform a Hypothesis Test\n\nFor an additive two-way ANOVA, we have **two** hypothesis tests, one test per explanatory variable.\n\n### Hypothesis Test for `genre`\n\nThe `genre` line of the ANOVA table is testing if the mean movie rating is the same for all genres. It has the following hypotheses:\n\n$H_0$: The mean movie rating is the same for every genre, given the era of the movie\n\n$H_A$: The mean movie rating is different for at least one genre, given the era of the movie\n\n*Notice the hypotheses are similar to a multiple linear regression with two explanatory variables, where the test for each variable is conditional on the other variable(s) included in the model.*\n\nWith a p-value of 0.178 (from an F-statistic of 1.86 with 1 and 51 degrees of freedom) at a significance level of 0.1, I fail to reject the null hypothesis. Thus, the data have unconvincing evidence that at least one genre has a different mean movie rating, given the era of the movie.\n\n### Hypothesis Test for `era`\n\nThe `era` line of the ANOVA table is testing if the mean movie rating is the same for all eras. It has the following hypotheses:\n\n$H_0$: The mean movie rating is the same for every era, given the genre of the movie\n\n$H_A$: The mean movie rating is different for at least one era, given the genre of the movie\n\nWith a p-value of 0.568 (from an F-statistic of 0.68 with 3 and 51 degrees of freedom) at a significance level of 0.1, I fail to reject the null hypothesis. Thus, the data have unconvincing evidence that at least one era has a different mean movie rating, given the genre of the movie.\n\n# Step 3: Fit a One-Way ANOVA\n\nTechnically, both variables had large p-values, but the p-value is conditional on the other variables in the model. So, the next step is to remove the variable with the **largest** p-value and fit a one-way ANOVA.\n\n## Fit the Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\naov(rating ~ genre, data = movies) %>% \n  tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 6\n  term         df  sumsq meansq statistic p.value\n  <chr>     <dbl>  <dbl>  <dbl>     <dbl>   <dbl>\n1 genre         1   4.68   4.68      2.13   0.150\n2 Residuals    54 119.     2.20     NA     NA    \n```\n:::\n:::\n\n\n## Perform a Hypothesis Test\n\nThe `genre` line of the ANOVA table is testing if the mean movie rating is the same for all genres. It has the following hypotheses:\n\n$H_0$: The mean movie rating is the same for every genre\n\n$H_A$: The mean movie rating is different for at least one genre\n\n*Notice the hypotheses don't include era this time, since that variable has been removed from the model!*\n\nWith a p-value of 0.15 (from an F-statistic of 2.13 with 1 and 54 degrees of freedom) at a significance level of 0.1, I fail to reject the null hypothesis. Thus, the data have unconvincing evidence that at least one genre has a different mean movie rating.\n\n# Step 4: Fit a Mean-Only Model\n\nOnce we've failed to reject the null in a one-way ANOVA, the \"best\" model is a model with **one** mean for **all** observations.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummarize(movies,\n          mean_rating = mean(rating)\n          )\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 1\n  mean_rating\n        <dbl>\n1        5.64\n```\n:::\n:::\n",
    "supporting": [
      "twa-model-selection-process_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}