---
title: "Sample Selection & Scope of Inference"
format: html
editor: visual
---

This activity is designed to help you critically evaluate how the data you are using in your Midterm Project were collected. You only need to complete **one** section of the activity, the section related to your dataset!

## Inclusion Criteria

This activity will lead you in thinking about **inclusion criteria**--criteria which needed to be met in order for an observation to be included in a sample. Inclusion criteria determine which members of a population can or cannot be included as a possible observation in a study.

Inclusion criteria are used for experiments and observational studies! For example, a clinical trial for a new treatment for individuals with chronic heart failure might require potential subjects to:

-   be between 18 to 80 years of age
-   have been diagnosed with chronic heart failure within at least 6 months
-   be currently taking stable doses of heart failure therapies
-   be willing to return for required follow-up (post-test) visits

Anyone meeting the inclusion criteria would be eligible to participate in the study. This does not mean that **everyone** meeting these criteria would participate in the study! The researchers would then decide how to *sample* from these eligible participants to obtain the sample for their study.

</br>

Alright, let's give this a go with the dataset you chose for your Midterm Project!

------------------------------------------------------------------------

## [`and_vertebrates`](https://lter.github.io/lterdatasampler/articles/and_vertebrates_vignette.html)

1.  What are the observations / rows in this dataset?

2.  From what population was the sample drawn?

3.  For an observation to be included in the dataset, what *inclusion criteria* needed to be met?

4.  How were the observations who satisfied the inclusion criteria sampled from the population?

5.  Based on the inclusion criteria and sampling methods, to what population can the findings of the study be generalized?

## [`ntl_icecover`](https://lter.github.io/lterdatasampler/articles/ntl_icecover_vignette.html)

1.  What are the observations / rows in this dataset?

2.  From what population was the sample drawn?

3.  For an observation to be included in the dataset, what *inclusion criteria* needed to be met?

4.  How were the observations who satisfied the inclusion criteria sampled from the population?

5.  Based on the inclusion criteria and sampling methods, to what population can the findings of the study be generalized?

## [`hbr_maples`](https://lter.github.io/lterdatasampler/articles/hbr_maples_vignette.html)

1.  What are the observations / rows in this dataset?

2.  From what population was the sample drawn?

3.  For an observation to be included in the dataset, what *inclusion criteria* needed to be met?

4.  How were the observations who satisfied the inclusion criteria sampled from the population?

5.  Based on the inclusion criteria and sampling methods, to what population can the findings of the study be generalized?

## [`pie_crab`](https://lter.github.io/lterdatasampler/articles/pie_crab_vignette.html)

1.  What are the observations / rows in this dataset?

2.  From what population was the sample drawn?

3.  For an observation to be included in the dataset, what *inclusion criteria* needed to be met?

4.  How were the observations who satisfied the inclusion criteria sampled from the population?

5.  Based on the inclusion criteria and sampling methods, to what population can the findings of the study be generalized?

## [`ncbirths`](https://www.openintro.org/data/index.php?data=ncbirths)

1.  What are the observations / rows in this dataset?

2.  From what population was the sample drawn?

3.  For an observation to be included in the dataset, what *inclusion criteria* needed to be met?

4.  How were the observations who satisfied the inclusion criteria sampled from the population?

5.  Based on the inclusion criteria and sampling methods, to what population can the findings of the study be generalized?

## [`possum`](https://www.openintro.org/data/index.php?data=possum)

1.  What are the observations / rows in this dataset?

2.  From what population was the sample drawn?

3.  For an observation to be included in the dataset, what *inclusion criteria* needed to be met?

4.  How were the observations who satisfied the inclusion criteria sampled from the population?

5.  Based on the inclusion criteria and sampling methods, to what population can the findings of the study be generalized?

## [`evals`](https://moderndive.github.io/moderndive/reference/evals.html)

1.  What are the observations / rows in this dataset?

2.  From what population was the sample drawn?

3.  For an observation to be included in the dataset, what *inclusion criteria* needed to be met?

4.  How were the observations who satisfied the inclusion criteria sampled from the population?

5.  Based on the inclusion criteria and sampling methods, to what population can the findings of the study be generalized?

## [`gapminder`](https://cran.r-project.org/web/packages/gapminder/readme/README.html)

1.  What are the observations / rows in this dataset?

2.  From what population was the sample drawn?

3.  For an observation to be included in the dataset, what *inclusion criteria* needed to be met?

4.  How were the observations who satisfied the inclusion criteria sampled from the population?

5.  Based on the inclusion criteria and sampling methods, to what population can the findings of the study be generalized?
