---
title: "STAT 313: Applied Experimental Design and Regression Models"
tbl-colwidths: [5,10,35,5,5,5,5,5,5]
---

This page contains an outline of the topics, content, and assignments for the quarter. Note that this schedule will be updated as the quarter progresses, with all changes documented here.

::: column-screen-inset-right
+-------------------------+------------------------------------+---------------------------------------------------+----------------------------------------------+------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Week                    | Date                               | Topic                                             | Prepare                                      | Lecture Slides                                                                     | Activity                                                                                                                                                            | Lab                                                                                                                                  | Critique                                                                                                                  | Project                                                                                                                                                                                                             |
+:=======================:+====================================+===================================================+:============================================:+:==================================================================================:+:===================================================================================================================================================================:+:====================================================================================================================================:+:=========================================================================================================================:+:===================================================================================================================================================================================================================:+
| [0](weeks/week-0.qmd)   | Sun, March 31                      | Welcome to Stat 313 Course Set-up                 | [📖](weeks/week-0.qmd "Course Set-up")       |                                                                                    |                                                                                                                                                                     |                                                                                                                                      |                                                                                                                           |                                                                                                                                                                                                                     |
+-------------------------+------------------------------------+---------------------------------------------------+----------------------------------------------+------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [1](weeks/week-1.qmd)   | Mon, April 1 **(no class)**        | Course Structure & Statistics Review              | [📖](weeks/week-1.qmd "Week 1 Coursework")   | [🖥](slides/week1-day1-alt.qmd "Week 1 Review Lecture Slides")                      |                                                                                                                                                                     |                                                                                                                                      |                                                                                                                           |                                                                                                                                                                                                                     |
+-------------------------+------------------------------------+---------------------------------------------------+----------------------------------------------+------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                         | Wed, April 3                       | Introduction to Data                              |                                              | [🎥](https://www.youtube.com/watch?v=_f3latmOhew "Video on How to Work in Quarto") | [📋](activity/week-1-quarto.qmd "Links to video, textbook, and tutorial resources")                                                                                 | [💻](labs/lab-1.qmd "Lab 1") </br> Due April 8 </br> [Lab 1 Feedback](labs/grading-guides/lab1_feedback.md "Lab 1 Feedback")         |                                                                                                                           |                                                                                                                                                                                                                     |
+-------------------------+------------------------------------+---------------------------------------------------+----------------------------------------------+------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [2](weeks/week-2.qmd)   | Mon, April 8                       | Visualizing & Summarizing Numerical Variables     | [📖](weeks/week-2.qmd "Week 2 Coursework")   | [🖥](slides/week2-day1.qmd "Week 2 Review Lecture Slides")                          | [📋](https://bit.ly/week-2-code-along "Code Along Activity")                                                                                                        |                                                                                                                                      |                                                                                                                           |                                                                                                                                                                                                                     |
+-------------------------+------------------------------------+---------------------------------------------------+----------------------------------------------+------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                         | Wed, April 10                      | The Flaws of Averages                             |                                              | [🖥](slides/week2-day2.qmd "Week 2 Lab Warm-up Lecture Slides")                     |                                                                                                                                                                     | [💻](labs/lab-2.qmd "Lab 2") </br> Due April 15 </br> [Lab 2 Feedback](labs/grading-guides/lab-2-grading-guide.qmd "Lab 2 Feedback") |                                                                                                                           |                                                                                                                                                                                                                     |
+-------------------------+------------------------------------+---------------------------------------------------+----------------------------------------------+------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [3](weeks/week-3.qmd)   | Mon, April 15                      | Incorporating Categorical Variables               | [📖](weeks/week-3.qmd "Week 3 Courswork")    | [🖥](slides/week3-day1.qmd "Week 3 Review Lecture Slides")                          |                                                                                                                                                                     |                                                                                                                                      |                                                                                                                           |                                                                                                                                                                                                                     |
+-------------------------+------------------------------------+---------------------------------------------------+----------------------------------------------+------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                         | Wed, April 17                      | Ethics & Categorical Variables                    |                                              | [🖥](slides/week3-day2.qmd "Week 3 Review Lab Slides")                              |                                                                                                                                                                     | [💻](labs/lab-3.qmd "Lab 3") </br> Due April 22 </br> [Lab 3 Feedback](labs/grading-guides/lab-3-grading-guide.qmd "Lab 3 Feedback") |                                                                                                                           |                                                                                                                                                                                                                     |
+-------------------------+------------------------------------+---------------------------------------------------+----------------------------------------------+------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                         | Mon, April 22                      | ***Statistical Critique Due***                    |                                              |                                                                                    |                                                                                                                                                                     |                                                                                                                                      | [✍](critique/critique-1.qmd "Statistical Critique 1")\                                                                    |                                                                                                                                                                                                                     |
|                         |                                    |                                                   |                                              |                                                                                    |                                                                                                                                                                     |                                                                                                                                      | </br> [Statistical Critique 1 Feedback](critique/grading-guides/critique-1-grading.qmd "Statistical Critique 1 Feedback") |                                                                                                                                                                                                                     |
+-------------------------+------------------------------------+---------------------------------------------------+----------------------------------------------+------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [4](weeks/week-4.qmd)   | Mon, April 22                      | Introduction to Linear Regression                 | [📖](weeks/week-4.qmd "Week 4 Coursework")   | [🖥](slides/week4-day1.qmd "Week 4 Review Lecture Slides")                          |                                                                                                                                                                     |                                                                                                                                      |                                                                                                                           |                                                                                                                                                                                                                     |
+-------------------------+------------------------------------+---------------------------------------------------+----------------------------------------------+------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                         | Wed, April 24                      | The Ugly History of Linear Regression             |                                              | [🖥](slides/week4-day2.qmd "Week 4 Review Lab Slides")                              |                                                                                                                                                                     | [💻](labs/lab-4.qmd "Lab 4") </br> Due April 29 </br> [Lab 4 Feedback](labs/grading-guides/lab-4-grading-guide.qmd "Lab 4 Feedback") |                                                                                                                           |                                                                                                                                                                                                                     |
+-------------------------+------------------------------------+---------------------------------------------------+----------------------------------------------+------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                         | Mon, April 29                      | ***Midterm Project Proposal***                    |                                              |                                                                                    |                                                                                                                                                                     |                                                                                                                                      |                                                                                                                           | [📁 STAT 313](project/midterm-project/midterm-proposal-313.qmd "Midterm Project Proposal")                                                                                                                          |
+-------------------------+------------------------------------+---------------------------------------------------+----------------------------------------------+------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [5](weeks/week-5.qmd)   | Mon, April 29                      | Introduction to Multiple Linear Regression        | [📖](weeks/week-5.qmd "Week 5 Coursework")   | [🖥](slides/week5-day1.qmd "Week 5 Review Lecture Slides")                          | [📋](activity/week-5-sample-selection.qmd "Sample Selection & Scope of Inference Activity")                                                                         |                                                                                                                                      |                                                                                                                           |                                                                                                                                                                                                                     |
+-------------------------+------------------------------------+---------------------------------------------------+----------------------------------------------+------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                         | Wed, May 1                         | Work Day -- Coding a Multiple Linear Regression   |                                              | [🖥](slides/week5-day2.qmd "Midterm Project Warm-up Slides")                        | [📋](activity/week-5-model-justification.qmd "Model Justification Critique")                                                                                        |                                                                                                                                      |                                                                                                                           |                                                                                                                                                                                                                     |
+-------------------------+------------------------------------+---------------------------------------------------+----------------------------------------------+------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                         | Sun, May 5                         | ***Midterm Project First Draft Due***             |                                              |                                                                                    |                                                                                                                                                                     |                                                                                                                                      |                                                                                                                           | Grading Rubric: [✅](project/midterm-project/midterm-project-grading-rubric.qmd "Midterm Project Grading Rubric")                                                                                                   |
|                         |                                    |                                                   |                                              |                                                                                    |                                                                                                                                                                     |                                                                                                                                      |                                                                                                                           |                                                                                                                                                                                                                     |
|                         |                                    |                                                   |                                              |                                                                                    |                                                                                                                                                                     |                                                                                                                                      |                                                                                                                           | Feedback: [📣](project/midterm-project-help/midterm-project-feedback.qmd "Midterm Project Feedback Guide")                                                                                                          |
+-------------------------+------------------------------------+---------------------------------------------------+----------------------------------------------+------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [6](weeks/week-6.qmd)   | Mon, May 6                         | Variable Selection in Multiple Linear Regression  | [📖](weeks/week-6.qmd "Week 6 Coursework")   | [🖥](slides/week6-day1.qmd "Week 6 Review Lecture Slides")                          | [📋](activity/week-6-model-selection.qmd "Model Selection Activity")                                                                                                |                                                                                                                                      |                                                                                                                           |                                                                                                                                                                                                                     |
+-------------------------+------------------------------------+---------------------------------------------------+----------------------------------------------+------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                         | Wed, May 8                         | Machine Learning                                  |                                              | [🖥](slides/week6-day2.qmd "Week 6 Lab Review Slides")                              |                                                                                                                                                                     | [💻](labs/lab-6.qmd "Lab 6") </br> Due May 13 </br> [Lab 6 Feedback](labs/grading-guides/lab-6-grading-guide.qmd "Lab 6 Feedback")   |                                                                                                                           |                                                                                                                                                                                                                     |
+-------------------------+------------------------------------+---------------------------------------------------+----------------------------------------------+------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                         | Sun, May 12                        | ***Midterm Project Final Version Due***           |                                              |                                                                                    |                                                                                                                                                                     |                                                                                                                                      |                                                                                                                           | Grading Rubric: [✅](project/midterm-project/midterm-project-grading-rubric.qmd "Midterm Project Grading Rubric")                                                                                                   |
+-------------------------+------------------------------------+---------------------------------------------------+----------------------------------------------+------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [7](weeks/week-7.qmd)   | Mon, May 13                        | Sampling Variability                              | [📖](weeks/week-7.qmd "Week 7 Coursework")   | [🖥](slides/week7-day1.qmd "Week 7 Review Lecture Slides")                          | [📋](activity/week-7-sampling-activity.qmd "Exploring Sampling Concepts")                                                                                           |                                                                                                                                      |                                                                                                                           |                                                                                                                                                                                                                     |
+-------------------------+------------------------------------+---------------------------------------------------+----------------------------------------------+------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                         | Wed, May 15                        | Confidence Intervals                              |                                              | [🖥](slides/week7-day2.qmd "Week 7 Lab Review Slides")                              |                                                                                                                                                                     | [💻](labs/lab-7.qmd "Lab 7") </br> Due May 20 </br> [Lab 7 Feedback](labs/grading-guides/lab-7-grading-guide.qmd "Lab 7 Feedback")   |                                                                                                                           |                                                                                                                                                                                                                     |
+-------------------------+------------------------------------+---------------------------------------------------+----------------------------------------------+------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [8](weeks/week-8.qmd)   | Mon, May 20\                       | p-values & Hypothesis Tests                       | [📖](weeks/week-8.qmd "Week 8 Coursework")   | [🖥](slides/week8-day1.qmd "Week 8 Review Lecture Slides")                          | [📋](activity/week-8-grade-check.qmd "Grade Check-in")                                                                                                              |                                                                                                                                      |                                                                                                                           |                                                                                                                                                                                                                     |
|                         | \                                  |                                                   |                                              |                                                                                    |                                                                                                                                                                     |                                                                                                                                      |                                                                                                                           |                                                                                                                                                                                                                     |
|                         | *Class Held Asynchronously*        |                                                   |                                              |                                                                                    |                                                                                                                                                                     |                                                                                                                                      |                                                                                                                           |                                                                                                                                                                                                                     |
+-------------------------+------------------------------------+---------------------------------------------------+----------------------------------------------+------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                         | Wed, May 22                        | Simulation-based Methods vs. Theory-based Methods |                                              | [🖥](slides/week8-day2.qmd "Week 8 Lab Review Slides")                              |                                                                                                                                                                     | [💻](labs/lab-8.qmd "Lab 8") </br> Due May 27 </br> [Lab 8 Feedback](labs/grading-guides/lab-8-grading-guide.qmd "Lab 8 Feedback")   |                                                                                                                           |                                                                                                                                                                                                                     |
+-------------------------+------------------------------------+---------------------------------------------------+----------------------------------------------+------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                         | Mon, May 27                        | ***Statistical Critique 2*** ***Due***            |                                              |                                                                                    |                                                                                                                                                                     |                                                                                                                                      | [✍](critique/critique-2.qmd "Statistical Critique 2")                                                                     |                                                                                                                                                                                                                     |
+-------------------------+------------------------------------+---------------------------------------------------+----------------------------------------------+------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [9](weeks/week-9.qmd)   | Mon, May 27                        |                                                   | [📖](weeks/week-9.qmd "Week 9 Coursework")   |                                                                                    | \                                                                                                                                                                   |                                                                                                                                      |                                                                                                                           |                                                                                                                                                                                                                     |
|                         |                                    |                                                   |                                              |                                                                                    |                                                                                                                                                                     |                                                                                                                                      |                                                                                                                           |                                                                                                                                                                                                                     |
|                         | *No Class, School Holiday*         |                                                   |                                              |                                                                                    |                                                                                                                                                                     |                                                                                                                                      |                                                                                                                           |                                                                                                                                                                                                                     |
+-------------------------+------------------------------------+---------------------------------------------------+----------------------------------------------+------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                         | Tues, May 28                       | One-Way Analysis of Variance (OWA)                |                                              | [🖥](slides/week9-day1.qmd "One-way ANOVA Review")                                  |                                                                                                                                                                     |                                                                                                                                      |                                                                                                                           |                                                                                                                                                                                                                     |
|                         |                                    |                                                   |                                              |                                                                                    |                                                                                                                                                                     |                                                                                                                                      |                                                                                                                           |                                                                                                                                                                                                                     |
|                         | *Classes follow a Monday Schedule* |                                                   |                                              |                                                                                    |                                                                                                                                                                     |                                                                                                                                      |                                                                                                                           |                                                                                                                                                                                                                     |
+-------------------------+------------------------------------+---------------------------------------------------+----------------------------------------------+------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                         | Wed, May 29                        | Inference for OWA & Model Selection               |                                              | [🖥](slides/week9-day2.qmd "Coding a One-way ANOVA")                                | Assessing Independence: [📋](project/final-project-help/assess_independence.qmd "Help on Assessing Independence")                                                   |                                                                                                                                      |                                                                                                                           |                                                                                                                                                                                                                     |
+-------------------------+------------------------------------+---------------------------------------------------+----------------------------------------------+------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                         | Sun, June 2                        | ***Final Project First Draft Due***               |                                              |                                                                                    |                                                                                                                                                                     |                                                                                                                                      |                                                                                                                           | Instructions: [📁](project/final-project/final-project-directions.qmd "Final Project Directions") </br> Grading Rubric: [✅](project/final-project/final-project-grading-rubric.qmd "Final Project Grading Rubric") |
+-------------------------+------------------------------------+---------------------------------------------------+----------------------------------------------+------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [10](weeks/week-10.qmd) | Mon, June 3                        | Two-Way ANOVA (TWA) Models                        | [📖](weeks/week-10.qmd "Week 10 Coursework") | [🖥](slides/week10-day1.qmd "Week 10 Review Slides")                                | One-way to Two-way Model Selection Process: [📋](project/final-project-help/owa-to-twa-model-selection-process.qmd "Model Selection Process for the Final Project") |                                                                                                                                      |                                                                                                                           |                                                                                                                                                                                                                     |
+-------------------------+------------------------------------+---------------------------------------------------+----------------------------------------------+------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                         | Wed, June 5                        | Last Day of STAT 313                              |                                              | [🖥](slides/week10-day2.qmd "Final Class Debrief")                                  |                                                                                                                                                                     |                                                                                                                                      |                                                                                                                           | What **should not** be in your project: [📋](project/final-project-help/no-gos.qmd "Things that don't belong in your report!")                                                                                      |
+-------------------------+------------------------------------+---------------------------------------------------+----------------------------------------------+------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                         | Sun, June 9                        | ***Final Project Final Version Due***             |                                              |                                                                                    |                                                                                                                                                                     |                                                                                                                                      |                                                                                                                           | Grading Rubric: [✅](project/final-project/final-project-grading-rubric.qmd "Final Project Grading Rubric")                                                                                                         |
+-------------------------+------------------------------------+---------------------------------------------------+----------------------------------------------+------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Finals Week             |                                    | Final Presentations                               |                                              |                                                                                    |                                                                                                                                                                     |                                                                                                                                      |                                                                                                                           | Presentation Instructions:[📁](project/final-presentations/presentation-instructions.qmd "Final Presentation Instructions")                                                                                         |
+-------------------------+------------------------------------+---------------------------------------------------+----------------------------------------------+------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                         | STAT 313-01                        | Wed, June 12 10:10am - 1:00pm                     |                                              |                                                                                    |                                                                                                                                                                     |                                                                                                                                      |                                                                                                                           |                                                                                                                                                                                                                     |
+-------------------------+------------------------------------+---------------------------------------------------+----------------------------------------------+------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                         | STAT 313-02                        | Tues, June 11 7:10am - 10:00am                    | Yes, your final is at 7:10am. 😫             |                                                                                    |                                                                                                                                                                     |                                                                                                                                      |                                                                                                                           |                                                                                                                                                                                                                     |
+-------------------------+------------------------------------+---------------------------------------------------+----------------------------------------------+------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
:::
