---
title: "Week 10: Two-Way ANOVA"
format: 
  html: 
    theme: minty
    fontsize: 1em
    mainfont: sans-serif
    number-sections: true
    number-depth: 2
    section-divs: true
    code-block-bg: "#76b5c5"
    highlight-style: monochrome
    embed-resources: true
editor: visual
execute: 
  echo: true
  warning: false
  message: false
---

```{r}
#| include: false
library(tidyverse)
library(emo)
library(gridExtra)
```

Welcome!

This week we explore one final area of ANOVA, a situation where we have multiple explanatory variables. This is called a **two-way ANOVA**. A two-way ANOVA extends the one-way ANOVA to situations with two categorical explanatory variables. This new methods allows researchers to simultaneously study two variables that might explain variability in the responses and explore whether the impacts of one explanatory variable change depending on the level of the other explanatory variable.

# Prepare

## Textbook Reading

As two-way ANOVA is an extension of one-way ANOVA, this week's reading is rather short. I've written a guided tutorial to walk you through the components of a two-way ANOVA. The tutorial also has some coding exercises embedded in it, so it also counts as your R tutorial for the week.

[Click here to access the textbook reading and R tutorial](https://rstudio.csm.calpoly.edu/two-way-anova/#section-two-way-anova)

### Reading Guide -- Due Tuesday by noon

::: callout-note
# Submission

Submit a screenshot of the completion page at the end of the reading.
:::

## Concept Quiz -- Due Tuesday by noon

**1.  Match each two-way ANOVA model to its correct description.**

::: columns
::: {.column width="40%"}

</br>

**additive model**

</br>
</br>
</br>

**interaction model**
:::

::: {.column width="60%"}
The relationship between one factor and the response changes depending on the level of another factor.

</br>

The relationship between one factor and the response remains the same across all levels of another factor.

</br>

There is a significant relationship between each factor and the response.
:::
:::

</br>

**2.  Match each two-way ANOVA model to its multiple linear regression counterpart.**

::: columns
::: {.column width="45%"}
**additive model**

**interaction model**
:::

::: {.column width="10%"}
:::

:::{.column width="45%"} 
different slopes

parallel slopes
:::
:::

</br>

**3.  If there is evidence of an interaction when visualizing a two-way ANOVA model we will see...**

- differences in the centers of the distributions
- differences in the spreads of the distributions
- similar profiles of the distributions across the facets 
- differences in the profiles of the distributions across the facets

</br>

**4.  Which of the following are conditions of a two-way ANOVA model?**

-   independence of observations between the groups
-   independence of observations within each group
-   independence of variables
-   normally distributed responses within each group
-   normally distributed residuals
-   linear relationship between the explanatory and response variables
-   equal variance of residuals
-   equal variance of responses within each group

</br>

**5.  Which of the following is important to consider when assessing independence?**

-   If the same observational unit (e.g., person, penguin, tree) could be sampled multiple times

-   If observations could be biologically related (e.g., parents, siblings, etc.)

-   If observations could be spatially related (e.g., countries that border each other)

-   If there is a relationship between the observations and the response variable

</br>

**6.  An \[additive / interaction\] model is fit using a `*` symbol between the explanatory variables.**

</br>

**7.  When an additive model is fit, the interpretation of the p-value associated with each explanatory variable is \[conditional / independent\] on the other explanatory variable(s) in the model.**

</br>

**8.  If the null hypothesis is rejected in an additive two-way ANOVA model, what model should be fit instead?**

-   separate one-way ANOVA models
-   a one-way ANOVA model containing the variable with the smallest p-value (from the additive two-way ANOVA)
-   a mean only model
-   an interaction two-way ANOVA model
-   a simple linear regression

</br>

## R Tutorial -- Due Thursday by noon

The tutorial this week is embedded in the reading.

::: callout-note
# Submission

Submit a screenshot of the completion page at the end of the reading. Yes, this can be the same screenshot as your reading guide submission.
:::
