---
title: 'Week One: Foundations of Statistics'
subtitle: Winter 2023
format:
  html:
    theme: minty
    fontsize: 1em
    mainfont: "sans-serif"
    number-sections: true
    section-divs: true
    code-block-bg: '#76b5c5'
    highlight-style: monochrome
embed-resources: true
standalone: true
editor: visual
execute:
  echo: true
  warning: false
  message: false
---

```{r packages}
#| include: false

library(tidyverse)
library(flair)
library(emo)
library(unvotes)
library(lubridate)
library(DT)
```

Welcome!

In this coursework, you'll get a refresher on the foundational components of statistics and data, investigate how statistics is used in your major, and think critically about the philosophy of statistical inference.

## Learning Outcomes

By the end of this coursework you should be able to:

-   describe observations, variables, and data matrices

-   explain the different types of variables a study can have

-   illustrate the difference between explanatory and response variables

-   delineate the difference between a population and a sample

-   compare and contrast different sampling methods

-   outline what is necessary to make an experiment an "experiment"

-   characterize the differences between observational studies and experiments

-   describe the difference between little "s" statistics and big "S" Statistics

-   outline what "dichotomous thinking" is

-   illustrate how dichotomous thinking is used in Statistics

-   explain issues with using the term "significant" in Statistics

## This Week's TODOs

`r emo::ji("play button")` Watch Video: 9 minutes

`r emo::ji("book")` Readings: 60-75 minutes

`r emo::ji("computer")` Activities: 15 minutes

`r emo::ji("check")` Check-ins: 2 (submit on Canvas)

`r emo::ji("scroll")` Group Discussion Homework: 6 Questions

------------------------------------------------------------------------

# Data Refresher

Let's start off by reading a refresher on some of the foundational concepts for data!

`r emo::ji("book")` [**Required Reading:** *Introduction to Modern Statistics* -- Hello Data](https://openintro-ims.netlify.app/data-hello.html)

`r emo::ji("book")` [**Required Reading:** *Introduction to Modern Statistics* -- Study Design](https://openintro-ims.netlify.app/data-design.html)

`r emo::ji("book")` [**Required Reading:** statistics versus Statistics](https://critical-inference.com/statistics-vs-statistics/)

## `r emo::ji("pen")` Week 1 Reading Guide

Access the Word and HTML versions of the Week 1 Reading Guide on Canvas, under the Week 1 module.

## `r emo::ji("check")` Check-in

1.  What are the different types of variables that can appear in a dataset? (select all that apply)

-   discrete numerical
-   ordinal categorical
-   nominal categorical
-   continuous numerical
-   discrete categorical

2.  Just because a variable has numeric values, does not mean it is a numeric variable. Which of the following variables appear numerical but behave like a categorical variable? (select all that apply)

-   zip code
-   GPA
-   height
-   year in school

3.  Which of the following statements are true about observational studies and experiments? (select all that apply)

-   Experiments randomly assign the explanatory variable
-   Observational studies randomly assign the explanatory variable
-   Observational studies can make causal statements about the relationship between the explanatory and response variables
-   Experiments can make causal statements about the relationship between the explanatory and response variables

4.  What are different methods for sampling from a population? (select all that apply)

-   simple random sampling
-   stratified random sampling
-   cluster sampling
-   multistage sampling
-   convenience sampling

5.  Cluster sampling and stratified sampling both rely on grouping observations, but have important differences. Match each method to how observations are randomly sampled.

::: columns
::: {.column width="35%"}
**stratified sampling**

**cluster sampling**
:::

::: {.column width="35%"}
*groups of observations are created, groups are randomly selected, every observation in the selected group is sampled*

*groups of observations are created, observations within a group are randomly sampled*
:::
:::

------------------------------------------------------------------------

# Statistics in Your Field

`r emo::ji("play button")` [**Required Video:** How to Find a Peer Reviewed Journal Article (6 minutes)](https://www.youtube.com/watch?v=ui8ibJ0Pkhs)

Now let's investigate how statistics is used in your discipline.

Find a peer-reviewed article from a journal in your field that performs a statistical analysis somewhere in the paper. You **do not** need to be familiar with the analysis they do. That being said, if you want to find a paper that uses a statistical method we'll cover in this class, look for a paper that uses "regression" or "ANOVA."

The Library is a great resource for this! The following website <https://csu-calpoly.primo.exlibrisgroup.com/discovery/jsearch?vid=01CALS_PSU:01CALS_PSU> has a list of journals by discipline that are available through the library.

## `r emo::ji("check")` Check-in

Upload a PDF of your journal article to the Canvas assignment portal.

</br>

------------------------------------------------------------------------

# The Philosophy of Statistical Inference

`r emo::ji("play button")` [**Required Video:** Philosophy of Statistics (3 minutes)](https://www.youtube.com/watch?v=K511BpyoTzU)

`r emo::ji("book")` [**Required Reading:** Our love of dichotomizing](https://critical-inference.com/our-love-of-dichotomizing/)

`r emo::ji("book")` [**Required Reading:** Science is Human](https://critical-inference.com/science-is-human/)

`r emo::ji("book")` [**Required Reading:** *Do We Really Need the S-word?*](https://www.americanscientist.org/article/do-we-really-need-the-s-word)

</br>

## Conceptual Questions

Throughout the week, you will be asked to reflect on the following questions:

-   What is **S**tatistics?

-   What are two similarities and two differences between Statistics and Mathematics?

-   What is the role of Statistics in the progression of science?

-   How is dichotomous thinking used in Statistics? What are two benefits and drawbacks of dichotomous thinking?

-   What does it mean for an analysis to be "objective"? Do you believe statistical analyses can be objective? Why or why not?

-   What are 4-5 synonyms of "significant" that come to your mind?

-   What are two issues that you see with using the term "significant" to denote "small" p-values?
