---
title: "Work Day: Coding a Multiple Linear Regression"
format: 
  revealjs:
    embed-resources: true
    standalone: true
editor: visual
---

##  {background-color="#B6CADA"}

::: {style="font-size: 3em; color: #000000;"}
Revisions
:::

</br>

::: {style="font-size: 1.5em; color: #000000;"}
**One** per week -- Due by Monday at 8am

**Always** accompanied by reflections
:::

. . .

</br>

::: {style="font-size: 1.5em; color: #000000;"}
**Week 6** will have the opportunity for [**two**]{.underline} revisions.
:::

##  {background-color="#B6CADA"}

::: {style="font-size: 2em; color: #000000;"}
Step 1
:::

::: columns
::: {.column width="45%"}
[Two Numerical Variables]{.underline}

</br>

-   Visualize the model with **both** variables -- `color` gradient

-   Visualize **two** simple linear regression models -- one for each variable
:::

::: {.column width="5%"}
:::

::: {.column width="45%"}
[One Categorical & One Numerical Variable]{.underline}

</br>

-   Visualize the model using `geom_smooth(method = "lm")`

-   Visualize the model using `geom_parallel_lines()`
:::
:::

##  {background-color="#D4D4D4"}

::: {style="font-size: 2em; color: #000000;"}
Step 2
:::

::: columns
::: {.column width="45%"}
[Two Numerical Variables]{.underline}

::: {style="color: #0F4C81; font-size: 0.95em"}
-   If there appears to be a relationship with the colors -- include **both** variables!

-   If the colors are equally dispersed throughout the plot -- choose the **one** variable that has the **stronger** relationship!
:::
:::

::: {.column width="5%"}
:::

::: {.column width="45%"}
[One Categorical & One Numerical Variable]{.underline}

::: {style="color: #0F4C81; font-size: 0.95em"}
-   Compare the plots! Which looks like a better representation of the relationship?
:::
:::
:::

##  {background-color="#D4D4D4"}

::: {style="font-size: 2em; color: #000000;"}
Step 3 -- Fit the regression model with `lm()`
:::

::: columns
::: {.column width="45%"}
[Two Numerical Variables]{.underline}

::: {style="color: #0F4C81"}
-   Are both variables included? Use a `+` to separate them!
:::
:::

::: {.column width="5%"}
:::

::: {.column width="45%"}
[One Categorical & One Numerical Variable]{.underline}

::: {style="color: #0F4C81"}
-   Are the slopes different? Use a `*` to separate the variables!

-   Are the slopes similar? Use a `+` to separate the variables!
:::
:::
:::

##  {background-color="#D4D4D4"}

::: {style="font-size: 2em; color: #000000;"}
Step 4: Get the coefficients with `get_regression_table()`
:::

##  {background-color="#B6CADA"}

::: {style="font-size: 2em; color: #000000;"}
**Hermeneutics** hərmə'n(y)o͞odiks
:::

> *the study of interpretation*

</br>

. . .

> "Philosophically, hermeneutics concerns the meaning of interpretation--its basic nature, scope and validity, and its place within and implications for human existance."

##  {background-color="#D4D4D4"}

::: {style="font-size: 2em; color: #0F4C81;"}
**Statistical Hermeneutics**
:::

> "The study of the interpretation of results and conclusions based on statistical theory, methods, and reasoning."

. . .

-   The complexities in interpretations of statistical models, results, etc. are often downplayed and taken for granted.

-   It is not often that we are hit with an *explicit* call to discuss our *implicit* interpretations of the statements that arise from our use of statistical methods and results.

##  {background-color="#D4D4D4"}

::: {style="font-size: 2em; color: #0F4C81;"}
Better for Science
:::

> "Modern science despite all of the methodological and technological sophistication, has failed to account for the basic epistemic foundation on which it lies."

. . .

-   Hermeneutics possesses a positive attitude toward the finitude of human understanding.

    -   The concern is not to eradicate our finitude, but to recognize the consequences of our limits.
