---
title: "Confidence Intervals -- Real Life Sampling Distributions"
format: 
  revealjs:
    standalone: true
    embed-resources: true
editor: visual
---

```{r set-up}
library(tidyverse)
library(infer)
library(scales)
library(stringr)
library(palmerpenguins)
```

::: {style="font-size: 4em; color: #000000;"}
What if I only have one sample?
:::

## 

::: {style="font-size: 2em; color: #000000;"}
Approximate the variability you'd expect to see in other samples!
:::

. . .

<center>

::: {style="font-size: 3em; color: #0F4C81;"}
**Bootstrapping!**
:::

## 

::: {style="font-size: 2em; color: #000000;"}
A Bootstrap Resample
:::

. . .

-   Assumes the original sample is "representative" of observations in the population.

. . .

-   Uses the original sample to generate new samples that might have occurred with additional sampling.

</br>

. . .

::: {style="font-size: 1em; color: #0F4C81;"}
We can use the statistics from these bootstrap samples to approximate the true sampling distribution!
:::

##  {background-color="#B6CADA"}

::: {style="font-size: 5em; color: #000000;"}
Why???
:::

## 

::: {style="font-size: 2em; color: #000000;"}
Estimating a population parameter
:::

. . .

-   We are interested in knowing how a statistic varies from sample to sample.

. . .

-   Knowing a statistic's behavior helps us make better / more informed decisions!

. . .

-   This helps us estimate what values are more or less likely for the population parameter to have.

##  {background-color="#B6CADA"}

::: {style="font-size: 2em; color: #000000;"}
Confidence Intervals
:::

. . .

> Capture a range of plausible values for the population parameter.

. . .

</br>

> Are more likely to capture the population parameter than a *point estimate*.

