---
title: "Stat Critique 1 Grading Guide"
---

## Pop Visualization (NYT) & Scientific Visualization

### 1. Visualization included!

### 2. Aesthetics are correctly identified

::: callout-tip
# Double Encoding

It's okay if they only mention one of the aesthetics that a variable is associated with when it is mapped to multiple aesthetics.
:::

**Growing**

-   Doesn't name variables mapped to each aesthetic (e.g., only says the x-axis, y-axis, and color are used)

*Feedback:* We want you to state specifically the names of the *variables* mapped to each aesthetic!

-   Says a color aesthetic is used but the *same* color is used for every observation

*Feedback:* Careful! Aesthetics are places where *variables* are being incorporated into the plot. Is the color in this plot associated with a variable?

-   Misses an aesthetic that is being used

*Feedback for general plots:* You've got a great start, but there are some aesthetics in this plot that are missing from your description. Technically, there are [multiple plots / multiple colors / multiple lines] not just one. What variable is associated with these separate [plots / colors / lines]?

*Feedback for maps:* You've got a great start, but there are some aesthetics in this plot that are missing from your description. Technically, we have "hidden" x- and y-variables. What variables are associated with the location of a state on the map?

### 3. Offers two aspects the visualization does well

**Growing**

-   Only says one thing the visualization does well

*Feedback:* Careful! You were asked to provide **TWO** aspects of the visualization that are done well

-   At least one statement about what the visualization does well is unclear

*Feedback:* I'm having a hard time understanding what specific aspect you believe the visualization does well.

### 4. Offers two aspects of the visualization that could be improved

**Growing**

-   Only says one thing the visualization does well

*Feedback:* Careful! You were asked to provide **TWO** aspects of the visualization that are done well

-   At least one statement about what the visualization does well is unclear

*Feedback:* I'm having a hard time understanding what specific aspect you believe the visualization does well.
