{
  "hash": "453e01de4f44fda36b6b53ba8398594f",
  "result": {
    "markdown": "---\ntitle: \"One-Way ANOVA to Two-Way ANOVA Model Selection Process\"\nformat: \n  html: \n    standalone: true\neditor: visual\nexecute: \n  warning: false\n  message: false\n---\n\n\n\n\nWe will be using a \"forward\" selection process for deciding on the \"best\" ANOVA model. Meaning, we will start with a simple model and keep adding complexity until it seems like the complexity isn't \"worth it.\" \n\n\n# Step 1 -- Fit an One-Way ANOVA Model for Each Categorical Variable\n\n## Plot the model\n\n\n::: {.cell layout-nrow=\"1\" layout-align=\"center\"}\n::: {.cell-output-display}\n![](owa-to-twa-model-selection-process_files/figure-html/twa-plot-1.png){fig-align='center' width=672}\n:::\n\n::: {.cell-output-display}\n![](owa-to-twa-model-selection-process_files/figure-html/twa-plot-2.png){fig-align='center' width=672}\n:::\n:::\n\n\n**What are we looking for?**\n\nWe are looking to see if the mean of the response variable (IMDB rating) differs between the explanatory variable groups (genre or era). This is akin to looking for evidence that the slope of the regression line is not 0! \n\nFor these data we are looking to see if at least one of the genres has a different mean IMDB rating **or** if at least one of the eras has a different mean movie rating. \n\n## Fit the model(s)\n\n\n::: {.cell}\n\n```{.r .cell-code}\naov(rating ~ era, data = movies) %>% \n  tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 6\n  term         df  sumsq meansq statistic p.value\n  <chr>     <dbl>  <dbl>  <dbl>     <dbl>   <dbl>\n1 era           3   4.59   1.53     0.669   0.575\n2 Residuals    52 119.     2.28    NA      NA    \n```\n:::\n\n```{.r .cell-code}\naov(rating ~ genre, data = movies) %>% \n  tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 6\n  term         df  sumsq meansq statistic p.value\n  <chr>     <dbl>  <dbl>  <dbl>     <dbl>   <dbl>\n1 genre         1   4.68   4.68      2.13   0.150\n2 Residuals    54 119.     2.20     NA     NA    \n```\n:::\n:::\n\n\n## Perform a Hypothesis Test\n\nThe `era` line of the ANOVA table is testing if the mean movie rating is different for at least one era. It has the following hypotheses:\n\n$H_0$: The mean movie rating is the same for **every** era\n\n$H_A$: The mean movie rating is different for **at least one** era\n\nWith a p-value of 0.575 (from an F-statistic of 0.669 with 3 and 52 degrees of freedom) at a significance level of 0.1, I fail to reject the null hypothesis. Thus, the data have unconvincing evidence that the mean movie rating differs for at least one era.\n\nThe `genre` line of the ANOVA table is testing if the mean movie rating is different for at least genre. It has the following hypotheses:\n\n$H_0$: The mean movie rating is the same for **every** genre\n\n$H_A$: The mean movie rating is different for **at least one** genre\n\nWith a p-value of 0.015(from an F-statistic of 2.127 with 1 and 54 degrees of freedom) at a significance level of 0.1, I fail to reject the null hypothesis. Thus, the data have unconvincing evidence that the mean movie rating differs for at least one genre.\n\n::: {.callout-tip}\n# Categorical variables with two levels\nTechnically, if your categorical variable has only two levels, your alternative hypothesis is testing if there is a difference between the levels. But! This **is not** the case if your variable has more than two levels! \n:::\n\n# Step 2: Decide How to Proceed \n\nYou will decide what model to fit next depending on the results of your one-way ANOVA models.\n\n- If you failed to reject the null hypothesis for **both** one-way ANOVA models (like I did above)...   \n  * You **do not** fit any additional models. \n  \n- If you rejected the null hypothesis for **at least one** of the one-way ANOVA models...\n  * your next step is to fit an additive two-way ANOVA model \n\n::: {.callout-caution}  \n# Additive two-way ANOVA\nIn Week 10 we will learn about additive and interaction two-way ANOVA models, so you will have the tools to fit these additional models then!\n:::\n\n<!-- # Step 2: Fit an Additive Two-Way ANOVA -->\n\n<!-- We are looking to see if the mean of $y$ differs across the values of explanatory variable 1 and / or explanatory variable 2. This is akin to fitting a parallel slopes model in a multiple linear regression, where the y-intercept is the estimated change in the mean of $y$ for each group and the slope is the estimated relationship between the explanatory variable and the mean of $y$. -->\n\n<!-- For these data we are looking to see if the genres have differences in the mean movie ratings **and** if the eras have differences in the mean movie rating. -->\n\n<!-- ## Plot the model -->\n\n<!-- ```{r twa-plot} -->\n<!-- #| echo: false -->\n<!-- #| fig-align: center -->\n\n<!-- movies %>%  -->\n<!--   ggplot(aes(y = era, x = rating, fill = genre)) +  -->\n<!--   geom_density_ridges(alpha = 0.5, scale = 1) + -->\n<!--   labs(y = \"Era\",  -->\n<!--        x = \"IMDB Rating\",  -->\n<!--        fill = \"Genre\") +  -->\n<!--   theme(axis.title = element_text(size = 18),  -->\n<!--         axis.text = element_text(size = 16),  -->\n<!--         legend.text = element_text(size = 16), -->\n<!--         legend.title = element_text(size = 18)) -->\n<!-- ``` -->\n\n\n<!-- ## Fit the Model -->\n\n<!-- *Notice I'm using a `+` for an interaction model!* -->\n\n<!-- ```{r} -->\n<!-- aov(rating ~ era + genre, data = movies) %>%  -->\n<!--   tidy() -->\n<!-- ``` -->\n\n<!-- ## Perform a Hypothesis Test -->\n\n<!-- For an additive two-way ANOVA, we have **two** hypothesis tests, one test per explanatory variable. -->\n\n<!-- ### Hypothesis Test for `genre` -->\n\n<!-- The `genre` line of the ANOVA table is testing if the mean movie rating is the same for all genres. It has the following hypotheses: -->\n\n<!-- $H_0$: The mean movie rating is the same for every genre, given the era of the movie -->\n\n<!-- $H_A$: The mean movie rating is different for at least one genre, given the era of the movie -->\n\n<!-- *Notice the hypotheses are similar to a multiple linear regression with two explanatory variables, where the test for each variable is conditional on the other variable(s) included in the model.* -->\n\n<!-- With a p-value of 0.178 (from an F-statistic of 1.86 with 1 and 51 degrees of freedom) at a significance level of 0.1, I fail to reject the null hypothesis. Thus, the data have unconvincing evidence that at least one genre has a different mean movie rating, given the era of the movie. -->\n\n<!-- ### Hypothesis Test for `era` -->\n\n<!-- The `era` line of the ANOVA table is testing if the mean movie rating is the same for all eras. It has the following hypotheses: -->\n\n<!-- $H_0$: The mean movie rating is the same for every era, given the genre of the movie -->\n\n<!-- $H_A$: The mean movie rating is different for at least one era, given the genre of the movie -->\n\n<!-- With a p-value of 0.568 (from an F-statistic of 0.68 with 3 and 51 degrees of freedom) at a significance level of 0.1, I fail to reject the null hypothesis. Thus, the data have unconvincing evidence that at least one era has a different mean movie rating, given the genre of the movie. -->\n\n\n",
    "supporting": [
      "owa-to-twa-model-selection-process_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}