---
title: "Week 3 Reading Guide: Adding in Categorical Variables"
format: docx
editor: visual
---

## IMS -- Chapter 4, Section 6

In Figure 4.8, which data display do you prefer?

</br>

What is a strength of the stacked boxplots?

</br>

What is a weakness of the stacked boxplots?

</br>

What is a strength of stacked histograms?

</br>

What is a weakness of stacked histograms?

</br>

What is a **ridge plot**?

</br>

## Chapter 3 -- Data Wrangling

## The Pipe (`%>%`)

How would you write the following pipe operation in **one** line?

```         
x %>% 
  f() %>% 
  g() %>% 
  h()
```

::: callout-tip
Think about how

```         
x %>% 
  f() 
```

can be written as f(x).
:::

## `filter()`

What does the `filter()` function do?

</br>

How would you describe the following `filter()` statement **in words**?

```         
filter(origin == "JFK" | dest == "SEA", 
       month >= 10)
```

</br>

What does the `%in%` do in the following code?

```         
filter(dest %in% c("SEA", "SFO", "PDX", "BTV", "BDL")
```

</br>

## `summarize()`

What does the `summarize()` function do?

</br>

You will write lines of code that look like:

```         
  summarize(mean = mean(temp, na.rm = TRUE), 
            std_dev = sd(temp, na.rm = TRUE))
```

What does the name (e.g., `mean`, `std_dev`) on the right hand side of the `=` sign correspond to?

</br>

What does the code (e.g., `mean(temp, na.rm = TRUE)`) on the left hand side of the `=` sign correspond to?

</br>

## `group_by()`

What does the `group_by()` function do?

</br>

When you `group_by()` a variable before `summarize()` what happens?

</br>

What happens when you group by more than one variable in `group_by()`?

</br>

## `mutate()`

What does the `mutate()` function do?

</br>

Suppose we wanted to create a new variable in the `penguins` dataset that took the original `body_mass_g` variable and converted it to kilograms. How would that code look?

</br>

## `arrange()`

What does the `arrange()` function do?

</br>

What order are the rows organized by default when you use `arrange()`?

</br>

What would you do if you wanted the rows to be organized in descending order?

</br>
