---
title: "Week 6 Reading Guide Part 2 -- Study Design"
---

## Chapter 2: Sampling & Experimental Design

### Section 2.1.1: Populations & Samples

What is a population?

</br>

If a census was performed, how were observations sampled?

</br>

How is a sample different from a population?

</br>

### Section 2.1.2: Parameters & Statistics

What is a statistic?

</br>

What is a parameter?

</br>

What is the relationship between a statistic and a parameter?

</br>

### Section 2.1.3: Anecdotal Evidence

What is anecdotal evidence?

</br>

### Section 2.1.4: Sampling from a Population

What does it mean for something to be biased?

</br>

How can a sample be biased?

</br>

How are observations sampled when a researcher uses a simple random sample?

</br>

What does it mean for a sample to be "representative" of the population?

</br>

What does it mean for a study to have non-response bias?

</br>

What does it mean for a study to have response bias?

</br>

How are observations sampled when a researcher uses a convenience sample?

</br>

#### Notes

-   Someone must first be *chosen* to be in a study and refuse to participate in order to have **non-response bias**.

-   There must be a valid reason for someone to lie or be untruthful to justify saying **response bias** is present. Yes, anyone could lie at any time to any question. Response bias is when those lies are **predictable** and **systematic** based on outside influences. An example would be surveying Cal Poly students and asking them if they have ever driven drunk.

</br>

True or False: Convenience sampling tends to result in non-response bias.

</br>

True or False: Volunteer sampling tends to result in response bias.

</br>

### Section 2.1.5: Four Sampling Methods

How are observations sampled when a researcher uses a stratified sampling method?

</br>

What is a strata and how is it used in stratified sampling?

</br>

How are observations sampled when a researcher uses a cluster sampling method?

</br>

How are clusters made in cluster sampling?

</br>

How are clusters similar to and different from strata?

</br>

How are observations sampled when a researcher uses a multistage sampling method?

</br>

#### Notes

Ideally, how should we sample cases from our target population? Using what sampling method?

</br>

True or False: Random sampling helps to resolve selection bias, but has no impact on non-response or response bias.

</br>

### Section 2.2.1: Principles of Experimental Design

What does it me for an experiment to control for a specific variable?

</br>

What is a control and how is it used in an experiment?

</br>

What is randomization and how is it used in an experiment?

</br>

What is a confounding variable?

</br>

What does it mean for an experiment to have replication?

</br>

What is a replicate?

</br>

What is blocking and how is it used in an experiment?

</br>

What are blocks?

</br>

### Section 2.2.2: Reducing Bias in Human Experiments

In an experiment, what is a treatment group?

</br>

In an experiment, what is a control group?

</br>

What does it mean for an experiment to be blind?

</br>

What does it mean for an experiment to be double blind?

</br>

What is a placebo effect?

</br>

### Section 2.3: Observational Studies

What is a prospective study?

</br>

What is a retrospective study?

</br>

#### Notes

What are the four principles of a well-designed randomized experiment?

</br>

True or False: Observational studies can show an association between two variables, but cannot determine a causal relationship.

</br>

True or False: In order for an experiment to be valid, a placebo must be used.

</br>

True or False: If random sampling of the target population is used, and no other types of bias is suspected, results from the sample can be generalized to the entire target population.

</br>

True or False: If random sampling of the target population is used, and no other types of bias are suspected, results from the sample can be inferred as a causal relationship between the explanatory and response variables.

