---
title: "Lab 6 Grading Guide"
format: 
  html:
    self-contained: true
editor: visual
---

Q1 - 

Q2 -

Q3 - 

Q4 - 

Q5 - 

Q6 - 

::: {.callout-note}
# Model Selection Order

Based on my code, the model selection process should go:

`eval_completion` $\rightarrow$ `pic_color` $\rightarrow$ `gender`

Then, in Step 4 they will need to choose between `age` and `bty_avg`. Here is how their respective models should go:

`age` $\rightarrow$ `rank` $\rightarrow$ DONE

- No variables add at least 1% (0.01) to previous model

`bty_avg` $\rightarrow$ DONE

- No variables add at least 1% (0.01) to previous model
:::

## Question 1 

**To earn a Success:**

- fits other 6 models (rank, pic_outfit, pic_color, large_class, eval_completion, cls_level)
- finds other 6 adjusted $R^2$ values
- states top model includes **eval_completion** variable

*If they do not state the top model or what variable was chosen:*

> When comparing multiple models it is important to explicitly state what model was selected as the top model. This can be a simple statement like, "The top model was selected to have the following variables: ....". 

## Question 2

**To earn a Success:**

- fits 11 models that **include the variable chosen in #1 as an explanatory variable**
- finds 11 adjusted $R^2$ values
- states top model includes **eval_completion** & **pic_color** variables

*If they do not state the top model or what new variable was chosen:*

> When comparing multiple models it is important to explicitly state what model was selected as the top model. This can be a simple statement like, "The top model was selected to have the following variables: ....". 

OR 

> You need to state **every** variable that is included in your top model, not the name of the model that was fit. 

OR 

> Careful! Your model contains more variables than just gender! What are **all** the variables included in your top model?

## Question 3

**To earn a Success:**

- modifies code to fit models that **include the variables chosen in #1 and #2 as an explanatory variables**
- states top model includes **all** the variables they've chosen

*If they don't include a variable from #1 or #2 as an explanatory variable*

> Careful! You need to deciding what variable to add, given the variables you have already chosen! The variables you chose in #1 and #2 need to be included in the models you are comparing. 

*If they do not state the top model or what new variable was chosen:*

> When comparing multiple models it is important to explicitly state what model was selected as the top model. This can be a simple statement like, "The top model was selected to have the following variables: ....". 

OR 

> You need to state **every** variable that is included in your top model, not the name of the model that was fit. 

OR 

> Careful! Your model contains more variables than just gender! What are **all** the variables included in your top model?


## Question 4

**To earn a Success:**

- modifies code to fit models that **include the variables chosen in #1, #2, and #3 as an explanatory variables**
- states top model includes **all** the variables they've chosen

*If they don't include a variable from #1, #2, or #3 as an explanatory variable*

> Careful! You need to deciding what variable to add, given the variables you have already chosen! The variables you chose in #1, #2 AND #3 need to be included in the models you are comparing. 

*If they do not state the top model or what new variable was chosen:*

> When comparing multiple models it is important to explicitly state what model was selected as the top model. This can be a simple statement like, "The top model was selected to have the following variables: ....". 

## Question 5

**To earn a Success:**

- modifies code to fit models that **include the variables chosen in #1, #2, #3, and #4 as an explanatory variables**
- states top model includes **all** the variables they've chosen

*If they don't include a variable from #1, #2, #3, or #4 as an explanatory variable*

> Careful! You need to deciding what variable to add, given the variables you have already chosen! The variables you chose in #1, #2, #3 AND #4 need to be included in the models you are comparing. 

*If they do not state the top model or what new variable was chosen:*

> When comparing multiple models it is important to explicitly state what model was selected as the top model. This can be a simple statement like, "The top model was selected to have the following variables: ....". 

## Question 6

**To earn a Success:**

- includes **all** variables from top model in regression

*If the model fit here differs from their top model, they __must__ state why they fit a different model.*


