{
  "hash": "f3a0bf0e569e4b619b0210b195e69c01",
  "result": {
    "markdown": "---\ntitle: \"Introduction to Multiple Linear Regression\"\nformat: \n  revealjs:\n    embed-resources: true\n    standalone: true\neditor: visual\n---\n\n\n\n\n##  {background-color=\"#D4D4D4\"}\n\n::: {style=\"font-size: 3em; color: #000000;\"}\nBefore...\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](week5-day1_files/figure-revealjs/old-slr-1.png){width=960}\n:::\n:::\n\n\n##  {background-color=\"#D4D4D4\"}\n\n::: {style=\"font-size: 3em; color: #000000;\"}\nNow...\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](week5-day1_files/figure-revealjs/two-mlr-1.png){width=960}\n:::\n:::\n\n\n##  {background-color=\"#B6CADA\"}\n\n</br> </br>\n\n<center>\n\n::: {style=\"font-size: 6em; color: #000000;\"}\nHow?\n:::\n\n</center>\n\n##  {background-color=\"#D4D4D4\"}\n\n::: {style=\"font-size: 2em; color: #000000;\"}\nOffsets!\n:::\n\n::: columns\n::: {.column width=\"75%\"}\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"false\"}\nsmoke_lm <- lm(weight ~ weeks * habit, data = ncbirths)\n\nget_regression_table(smoke_lm)\n```\n:::\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 4 × 3\n  term              estimate std_error\n  <chr>                <dbl>     <dbl>\n1 intercept           -5.94      0.484\n2 weeks                0.341     0.013\n3 habit: smoker       -1.86      1.63 \n4 weeks:habitsmoker    0.039     0.042\n```\n:::\n:::\n\n:::\n\n::: {.column width=\"5%\"}\n:::\n\n::: {.column width=\"20%\"}\nThe \\* means the variables are interacting!\n:::\n:::\n\n. . .\n\n</br>\n\n::: {style=\"font-size: 1.1em; color: #0F4C81;\"}\nWhat is the regression equation for non-smoker mothers?\n:::\n\n. . .\n\n::: {style=\"font-size: 1.1em; color: #0F4C81;\"}\nWhat is the regression equation for smoker mothers?\n:::\n\n##  {background-color=\"#B6CADA\"}\n\n<center>\n\n::: {style=\"font-size: 3em; color: #000000;\"}\nWhat if we have a second numerical explanatory variable?\n:::\n\n</center>\n\n##  {background-color=\"#D4D4D4\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](week5-day1_files/figure-revealjs/mlr-two-num-1.png){width=960}\n:::\n:::\n\n\n##  {background-color=\"#D4D4D4\"}\n\n::: {style=\"font-size: 2em; color: #000000;\"}\nMultiple slopes\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"false\"}\nage_lm <- lm(weight ~ weeks + mage, data = ncbirths)\n\nget_regression_table(age_lm)\n```\n:::\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 3\n  term      estimate std_error\n  <chr>        <dbl>     <dbl>\n1 intercept   -6.68      0.492\n2 weeks        0.346     0.012\n3 mage         0.02      0.006\n```\n:::\n:::\n\n\n. . .\n\n</br>\n\n::: {style=\"font-size: 1.25em; color: #0F4C81;\"}\nHow do you interpret the value of 0.346?\n:::\n\n. . .\n\n::: {style=\"font-size: 1.25em; color: #0F4C81;\"}\nHow do you interpret the value of 0.02?\n:::\n\n##  {background-color=\"#B6CADA\"}\n\n<center>\n\n::: {style=\"font-size: 2.5em; color: #000000;\"}\nBut how do we decide if the interaction model is \"best\" without a p-value??????\n:::\n\n</center>\n\n##  {background-color=\"#D4D4D4\"}\n\n::: {style=\"font-size: 2em; color: #000000;\"}\nWhen investigating if a relationship differs...\n:::\n\n. . .\n\n::: {style=\"font-size: 1.25em; color: #0F4C81;\"}\nAlways start with the \"interaction\" / different slopes model.\n:::\n\n. . .\n\n::: {style=\"font-size: 1.25em; color: #b76352;\"}\nIf the slopes look different, you're done!\n:::\n\n. . .\n\n::: {style=\"font-size: 1.25em; color: #34605f;\"}\nIf the slopes look similar, then fit the \"additive\" / parallel slopes model.\n:::\n\n## \n\n::: {style=\"font-size: 2em; color: #000000;\"}\nDifferent Enough?\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](week5-day1_files/figure-revealjs/unnamed-chunk-1-1.png){width=960}\n:::\n:::\n\n\n## \n\n::: {style=\"font-size: 2em; color: #000000;\"}\nBehind the Plot\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = MA_schools, \n       mapping = aes(y = average_sat_math, \n                       x = perc_disadvan, \n                       color = size)) + \n  geom_point() +\n  geom_smooth(method = \"lm\") + \n  labs(x = \"Percent Economically Disadvantaged\", \n       y = \"Average SAT Math\", \n       color = \"Size of School\")\n```\n:::\n\n\n</br>\n\n`geom_smooth()` allows for *both* the intercepts and the slopes to differ\n\n## \n\n::: {style=\"font-size: 2em; color: #000000;\"}\nWhat about now?\n:::\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 3\n  term                     estimate std_error\n  <chr>                       <dbl>     <dbl>\n1 intercept                 594.       13.3  \n2 perc_disadvan              -2.93      0.294\n3 size: medium              -17.8      15.8  \n4 size: large               -13.3      13.8  \n5 perc_disadvan:sizemedium    0.146     0.371\n6 perc_disadvan:sizelarge     0.189     0.323\n```\n:::\n:::\n\n\n. . .\n\n::: {style=\"font-size: 3em; color: #B6CADA;\"}\n🤨\n:::\n\n##  {background-color=\"#B6CADA\"}\n\n::: {style=\"font-size: 2em; color: #000000;\"}\nWho is baseline?\n:::\n\n![](images/baseline.jpg)\n\n## \n\n::: {style=\"font-size: 2em; color: #000000;\"}\nDeciphering groups -- Small schools\n:::\n\n![](images/small_coefficients.jpg)\n\n. . .\n\n$$\\widehat{SAT}_{small} = 594 - 2.93 \\times \\text{percent disadvan}$$\n\n## \n\n::: {style=\"font-size: 2em; color: #000000;\"}\nDeciphering groups -- Medium schools\n:::\n\n![](images/medium_coefficients.jpg)\n\n. . .\n\n$$\\widehat{SAT}_{medium} = (594 - 17.8) + (- 2.93 + 0.146) \\times \\text{percent disadvan}$$\n\n. . .\n\n$$\\widehat{SAT}_{medium} = 576.2 - 2.784 \\times \\text{percent disadvan}$$\n\n## \n\n::: {style=\"font-size: 2em; color: #000000;\"}\nDeciphering groups -- Large schools\n:::\n\n![](images/large_coefficients.jpg)\n\n. . .\n\n$$\\widehat{SAT}_{large} = (594 - 13.3) + (- 2.93 + 0.189) \\times \\text{percent disadvan}$$\n\n. . .\n\n$$\\widehat{SAT}_{large} = 580.7 - 2.741 \\times \\text{percent disadvan}$$\n\n##  {background-color=\"#B6CADA\"}\n\n::: {style=\"font-size: 2em; color: #000000;\"}\nWhat if they're not very different?\n:::\n\n::: columns\n::: {.column width=\"45%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](week5-day1_files/figure-revealjs/unnamed-chunk-4-1.png){width=960}\n:::\n:::\n\n:::\n\n::: {.column width=\"5%\"}\n:::\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](week5-day1_files/figure-revealjs/unnamed-chunk-5-1.png){width=960}\n:::\n:::\n\n:::\n:::\n\n## \n\n::: {style=\"font-size: 2em; color: #000000;\"}\nParallel Slopes\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"false\"}\nlm(average_sat_math ~ perc_disadvan + size, data = MA_schools)\n```\n:::\n\n\n</br>\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 4 × 3\n  term          estimate std_error\n  <chr>            <dbl>     <dbl>\n1 intercept       588.       7.61 \n2 perc_disadvan    -2.78     0.106\n3 size: medium    -11.9      7.54 \n4 size: large      -6.36     6.92 \n```\n:::\n:::\n\n\n##  {background-color=\"#B6CADA\"}\n\n::: {style=\"font-size: 2em; color: #000000;\"}\nGroup equations -- Baseline\n:::\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 4 × 3\n  term          estimate std_error\n  <chr>            <dbl>     <dbl>\n1 intercept       588.       7.61 \n2 perc_disadvan    -2.78     0.106\n3 size: medium    -11.9      7.54 \n4 size: large      -6.36     6.92 \n```\n:::\n:::\n\n\n. . .\n\n$$\\widehat{SAT}_{small} = 588 - 2.78 \\times \\text{percent disadvantaged}$$\n\n##  {background-color=\"#B6CADA\"}\n\n::: {style=\"font-size: 2em; color: #000000;\"}\nGroup equations -- Offsets\n:::\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 4 × 3\n  term          estimate std_error\n  <chr>            <dbl>     <dbl>\n1 intercept       588.       7.61 \n2 perc_disadvan    -2.78     0.106\n3 size: medium    -11.9      7.54 \n4 size: large      -6.36     6.92 \n```\n:::\n:::\n\n\n. . .\n\n$$\\widehat{SAT}_{medium} = (588 - 11.9) - 2.78 \\times \\text{percent disadvan}$$\n\n. . .\n\n$$\\widehat{SAT}_{medium} = 576.1 - 2.78 \\times \\text{percent disadvan}$$\n\n. . .\n\n$$\\widehat{SAT}_{large} = (588 - 6.36) - 2.78 \\times \\text{percent disadvan}$$\n\n. . .\n\n$$\\widehat{SAT}_{large} = 581.64 - 2.78 \\times \\text{percent disadvan}$$\n",
    "supporting": [
      "week5-day1_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}