---
title: "Chapter 2: Data Visualization"
format: html
editor: visual
---

**This week covers Sections 2.1 - 2.7**

## 2.1.1 Components of the grammar

What is a `geom`? How is it used in a visualization?

</br>

What is an `aes`? How is it used in a visualization?

</br>

What are `aes`thetics associated with? i.e. How are they assigned to different aspects of a plot?

</br>

## 2.1.2 The `gapminder` data

What does each row of the `gapminder` data correspond to?

</br>

What `geom` is used in Figure 2.1?

</br>

What `aes`thetics are used in Figure 2.1?

</br>

## The **ggplot2** package

What are the required inputs for the `ggplot()` function?

</br> </br>

What symbol is used to add layers to a ggplot?

</br>

## 2.2 5NG

What are the five key named graphs?

</br> </br>

## 2.3 Scatterplots

What does the `data =` argument of the `ggplot()` function do?

</br>

What does the `mapping =` argument of the `ggplot()` function do?

</br>

What does the `aes()` function do?

</br>

What does the `+` between the two lines (`ggplot()` and `geom_point()`) do?

</br>

What plot do you get when you don't include `geom_point()`?

</br>

### 2.3.2 Overplotting

How can you change the transparency of points?

</br>

What is the difference between `geom_point()` and `geom_jitter()`?

</br>

## 2.4 Linegraphs

What `geom` do you use to make a linegraph?

</br>

## 2.5 Histograms

How are bins used in a histogram?

</br>

What does the height of each bin represent?

</br>

What `geom` do you use to make a histogram?

</br>

How many bins are chosen by default?

</br>

What are two ways you can adjust the number of bins in a histogram?

</br> </br>

## 2.6 Facets

What is a facet?

</br> </br>

How do you include facets in a visualization?

</br> </br>

## 2.7 Boxplots

What are the five numbers used to create a boxplot?

</br>

What `geom` do you use to make a boxplot?

</br>
