---
title: "Final Project Presentations"
format: html
editor: visual
---

During finals week each of you will give a 3-minute presentation on **one** aspect of your final project you found the most interesting. Notice, you need to pick one aspect, since your presentation is so short.

Here are some examples of what you could choose:

-   The relationships you saw in the visualizations
-   The design of the study
-   The model you found best represents the relationships between variables you selected

Of course you could choose other topics, the only requirement is that your topic is related to what you did in your final project.

## Slides

For your presentation you are allowed to make **two** slides:

1.  A title slide (make it fun!) with your name
2.  A content slide

**Slides are due by [5pm the night before your final exam timeslot]{.underline}. If you do not submit slides by the deadline, you will not be allowed to present.**

-   STAT 313-02 – slides are due by Monday (March ) by 5pm

-   STAT 313-01 – lides are due by Wednesday (March ) by 5pm

-   STAT 513-01 – slides are due by Wednesday (March ) by 5pm

::: callout-caution
Your slides **must be submitted as a PDF**. Make sure they are saved in the correct orientation! I do not have the time to open PowerPoint slides and convert them to a PDF. So, if you **do not submit your slides as a PDF**, you will not be allowed to present.
:::

## Presentations

For ease, I will randomly order the presentations. If you have a strong preference for when you would like to present, you can request a position. However, I cannot guarantee that I can accommodate every request.

**I will publish the order of presentations by 8am the day of the final exam.**
