<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.549">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>STAT 313 / 513 - Winter 2024 - Week 8 – Hypothesis Test for Slope &amp; Inference Conditions</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../../site_libs/htmlwidgets-1.6.2/htmlwidgets.js"></script>
<link href="../../site_libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet">
<script src="../../site_libs/datatables-binding-0.27/datatables.js"></script>
<script src="../../site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<link href="../../site_libs/dt-core-1.12.1/css/jquery.dataTables.min.css" rel="stylesheet">
<link href="../../site_libs/dt-core-1.12.1/css/jquery.dataTables.extra.css" rel="stylesheet">
<script src="../../site_libs/dt-core-1.12.1/js/jquery.dataTables.min.js"></script>
<link href="../../site_libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet">
<script src="../../site_libs/crosstalk-1.2.0/js/crosstalk.min.js"></script>
<script src="../../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">Week 8 – Hypothesis Test for Slope &amp; Inference Conditions</li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
      <a href="../../index.html" class="sidebar-logo-link">
      <img src="../../images/cp-stat-hex.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
      <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/atheobold/stat-313-website" title="GitHub organization" class="quarto-navigation-tool px-1" aria-label="GitHub organization"><i class="bi bi-github"></i></a>
    <a href="https://posit.cloud/spaces/352796/join?access_code=1UXvC0avaZPdFlXCzQUZqFAUdLgGFehApPhyVxjo" title="" class="quarto-navigation-tool px-1" aria-label="RStudio Cloud"><i class="bi bi-cloud-fill"></i></a>
    <a href="https://canvas.calpoly.edu" title="Cal Poly Canvas" class="quarto-navigation-tool px-1" aria-label="Cal Poly Canvas"><i class="bi bi-person-fill"></i></a>
</div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false">
 <span class="menu-text">Course information</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../course-overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Overview</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../course-syllabus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Syllabus</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../course-support.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Support</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../course-team.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Teaching team</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Schedule</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false">
 <span class="menu-text">Computing</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../computing-access.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Access</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false">
 <span class="menu-text">R Resources</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../course_resources.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">R Resources</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="false">
 <span class="menu-text">Projects</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../project/midterm-project-directions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Midterm Project Description</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../project/final-project-directions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Final Project Description</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="false">
 <span class="menu-text">Weekly materials</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../weeks/week-0.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 0</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../weeks/week-1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../weeks/week-2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../weeks/week-3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 3</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../weeks/week-4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 4</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../weeks/week-5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 5</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../weeks/week-6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 6</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../weeks/week-7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 7</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../weeks/week-8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 8</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../weeks/week-9.Rmd" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 9</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../weeks/week-10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 10</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#reading-guide" id="toc-reading-guide" class="nav-link active" data-scroll-target="#reading-guide"><span class="header-section-number">0.1</span> Reading Guide</a></li>
  <li><a href="#birth-weights-mothers-age" id="toc-birth-weights-mothers-age" class="nav-link" data-scroll-target="#birth-weights-mothers-age"><span class="header-section-number">1</span> Birth weights &amp; mother’s age</a>
  <ul class="collapse">
  <li><a href="#observed-data" id="toc-observed-data" class="nav-link" data-scroll-target="#observed-data"><span class="header-section-number">1.1</span> Observed data</a></li>
  <li><a href="#research-question" id="toc-research-question" class="nav-link" data-scroll-target="#research-question"><span class="header-section-number">1.2</span> Research question</a></li>
  <li><a href="#sec-ht-activity" id="toc-sec-ht-activity" class="nav-link" data-scroll-target="#sec-ht-activity"><span class="header-section-number">1.3</span> Simulating data</a></li>
  <li><a href="#shuffling-10-times" id="toc-shuffling-10-times" class="nav-link" data-scroll-target="#shuffling-10-times"><span class="header-section-number">1.4</span> Shuffling 10 times</a></li>
  <li><a href="#what-just-happened" id="toc-what-just-happened" class="nav-link" data-scroll-target="#what-just-happened"><span class="header-section-number">1.5</span> What just happened?</a></li>
  </ul></li>
  <li><a href="#sec-understanding-ht" id="toc-sec-understanding-ht" class="nav-link" data-scroll-target="#sec-understanding-ht"><span class="header-section-number">2</span> Hypothesis tests</a></li>
  <li><a href="#infer-workflow-ht" id="toc-infer-workflow-ht" class="nav-link" data-scroll-target="#infer-workflow-ht"><span class="header-section-number">3</span> Conducting a hypothesis test using <strong>infer</strong></a>
  <ul class="collapse">
  <li><a href="#specify-variables" id="toc-specify-variables" class="nav-link" data-scroll-target="#specify-variables"><span class="header-section-number">3.1</span> <code>specify()</code> variables</a></li>
  <li><a href="#hypothesize-the-null" id="toc-hypothesize-the-null" class="nav-link" data-scroll-target="#hypothesize-the-null"><span class="header-section-number">3.2</span> <code>hypothesize()</code> the null</a></li>
  <li><a href="#generate-replicates" id="toc-generate-replicates" class="nav-link" data-scroll-target="#generate-replicates"><span class="header-section-number">3.3</span> <code>generate()</code> replicates</a></li>
  <li><a href="#calculate-summary-statistics" id="toc-calculate-summary-statistics" class="nav-link" data-scroll-target="#calculate-summary-statistics"><span class="header-section-number">3.4</span> <code>calculate()</code> summary statistics</a></li>
  <li><a href="#visualize-the-p-value" id="toc-visualize-the-p-value" class="nav-link" data-scroll-target="#visualize-the-p-value"><span class="header-section-number">3.5</span> <code>visualize()</code> the p-value</a></li>
  </ul></li>
  <li><a href="#sec-ht-interpretation" id="toc-sec-ht-interpretation" class="nav-link" data-scroll-target="#sec-ht-interpretation"><span class="header-section-number">4</span> Interpreting a hypothesis test</a>
  <ul class="collapse">
  <li><a href="#sec-trial" id="toc-sec-trial" class="nav-link" data-scroll-target="#sec-trial"><span class="header-section-number">4.1</span> Two possible outcomes</a></li>
  <li><a href="#sec-errors" id="toc-sec-errors" class="nav-link" data-scroll-target="#sec-errors"><span class="header-section-number">4.2</span> Types of errors</a></li>
  <li><a href="#sec-choosing-alpha" id="toc-sec-choosing-alpha" class="nav-link" data-scroll-target="#sec-choosing-alpha"><span class="header-section-number">4.3</span> How do we choose alpha?</a></li>
  </ul></li>
  <li><a href="#comparing-infer-workflows" id="toc-comparing-infer-workflows" class="nav-link" data-scroll-target="#comparing-infer-workflows"><span class="header-section-number">5</span> Comparison with confidence intervals</a></li>
  <li><a href="#theory-based-hypothesis-tests-confidence-intervals" id="toc-theory-based-hypothesis-tests-confidence-intervals" class="nav-link" data-scroll-target="#theory-based-hypothesis-tests-confidence-intervals"><span class="header-section-number">6</span> Theory-based hypothesis tests &amp; confidence intervals</a>
  <ul class="collapse">
  <li><a href="#regression-interp" id="toc-regression-interp" class="nav-link" data-scroll-target="#regression-interp"><span class="header-section-number">6.1</span> Interpreting regression tables</a>
  <ul class="collapse">
  <li><a href="#regression-se" id="toc-regression-se" class="nav-link" data-scroll-target="#regression-se"><span class="header-section-number">6.1.1</span> Standard error</a></li>
  <li><a href="#regression-test-statistic" id="toc-regression-test-statistic" class="nav-link" data-scroll-target="#regression-test-statistic"><span class="header-section-number">6.1.2</span> Test statistic</a></li>
  <li><a href="#p-value" id="toc-p-value" class="nav-link" data-scroll-target="#p-value"><span class="header-section-number">6.1.3</span> p-value</a></li>
  <li><a href="#confidence-interval" id="toc-confidence-interval" class="nav-link" data-scroll-target="#confidence-interval"><span class="header-section-number">6.1.4</span> Confidence interval</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">6.2</span> Conclusion</a></li>
  <li><a href="#everything-is-one-test" id="toc-everything-is-one-test" class="nav-link" data-scroll-target="#everything-is-one-test"><span class="header-section-number">6.3</span> Everything is one test</a></li>
  </ul></li>
  <li><a href="#sec-conditions" id="toc-sec-conditions" class="nav-link" data-scroll-target="#sec-conditions"><span class="header-section-number">7</span> Checking Model Conditions</a>
  <ul class="collapse">
  <li><a href="#conditions-for-regression" id="toc-conditions-for-regression" class="nav-link" data-scroll-target="#conditions-for-regression"><span class="header-section-number">7.1</span> Conditions for regression</a>
  <ul class="collapse">
  <li><a href="#residuals-refresher" id="toc-residuals-refresher" class="nav-link" data-scroll-target="#residuals-refresher"><span class="header-section-number">7.1.1</span> Residuals refresher</a></li>
  <li><a href="#linearity-of-relationship" id="toc-linearity-of-relationship" class="nav-link" data-scroll-target="#linearity-of-relationship"><span class="header-section-number">7.1.2</span> Linearity of relationship</a></li>
  <li><a href="#independence-of-residuals" id="toc-independence-of-residuals" class="nav-link" data-scroll-target="#independence-of-residuals"><span class="header-section-number">7.1.3</span> Independence of residuals</a></li>
  <li><a href="#normality-of-residuals" id="toc-normality-of-residuals" class="nav-link" data-scroll-target="#normality-of-residuals"><span class="header-section-number">7.1.4</span> Normality of residuals</a></li>
  <li><a href="#equality-of-variance" id="toc-equality-of-variance" class="nav-link" data-scroll-target="#equality-of-variance"><span class="header-section-number">7.1.5</span> Equality of variance</a></li>
  <li><a href="#what-is-the-conclusion" id="toc-what-is-the-conclusion" class="nav-link" data-scroll-target="#what-is-the-conclusion"><span class="header-section-number">7.1.6</span> What’s the conclusion?</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">8</span> References</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/atheobold/stat-313-website/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Week 8 – Hypothesis Test for Slope &amp; Inference Conditions</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>In this week’s coursework we are <strong>finally</strong> talking about p-values! What we learned last week should have helped make the connection between a sampling distribution and a bootstrap (resampling) distribution. Hopefully, you understand that we create confidence intervals based the statistics we saw in other samples.</p>
<p>This week we are going to connect these ideas to the framework of hypothesis testing. Hypothesis testing requires an additional component we didn’t see last week—the null hypothesis. We will learn how we integrate the null hypothesis in our resampling procedure to create a sampling distribution that could have happened if the null hypothesis was true. We will use this distribution to compare what we saw in our data and evaluate the plausibility of competing hypotheses.</p>
<p>This reading will walk you through the general framework for understanding hypothesis tests. By understanding this general framework, you’ll be able to adapt it to many different scenarios. The same can be said for confidence intervals. There was one general framework that applies to all confidence intervals. I believe this focus on the conceptual framework is better for long-term learning than focusing on specific details for specific instances.</p>

<div class="no-row-height column-margin column-container"><div class="">
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>This week’s reading is a compilation of <a href="https://moderndive.com/8-confidence-intervals.html">Chapter 8</a> from <em>ModernDive</em> <span class="citation" data-cites="kim2020">(<a href="#ref-kim2020" role="doc-biblioref">Kim et al. 2020</a>)</span>, <a href="openintro-ims.netlify.app/inf-model-slr.html">Chapter 24</a> from <em>Introduction to Modern Statistics</em> <span class="citation" data-cites="ims">(<a href="#ref-ims" role="doc-biblioref">Çetinkaya-Rundel and Hardin 2023</a>)</span>, with a smattering of my own ideas.</p>
</div>
</div>
</div></div><section id="reading-guide" class="level2" data-number="0.1">
<h2 data-number="0.1" class="anchored" data-anchor-id="reading-guide"><span class="header-section-number">0.1</span> Reading Guide</h2>
<p>Download the reading guide as a <a href="reading_guide/week8-reading-guide.docx">Word Document here</a></p>
</section>
<section id="birth-weights-mothers-age" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Birth weights &amp; mother’s age</h1>
<p>Last week we considered the question of assessing the relationship between a baby’s birth weight and the age of the mother. To explore this relationship, we used the <a href="http://openintrostat.github.io/openintro/reference/births14.html"><code>births14</code></a> dataset–a random sample of 1,000 cases from a large public dataset of all US birth records released in 2014.</p>
<div class="cell">
<div class="cell-output-display">
<div class="datatables html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-6166d559454ecd730d7d" style="width:100%;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-6166d559454ecd730d7d">{"x":{"filter":"none","vertical":false,"caption":"<caption>A sample of 10 rows from the births14 dataset.<\/caption>","data":[["1","2","3","4","5","6","7","8","9","10"],[284,848,918,101,623,905,645,934,400,900],[27,32,20,27,34,31,24,27,34,37],[7.25,8.56,8.62,8.73,6.94,6.75,8.46,4.28,7.69,7.87],[26,32,21,29,37,25,21,34,36,null],["younger mom","younger mom","younger mom","younger mom","younger mom","younger mom","younger mom","younger mom","younger mom","mature mom"],[41,39,40,41,42,40,39,33,38,41],["full term","full term","full term","full term","full term","full term","full term","premie","full term","full term"],[16,12,17,10,9,3,9,5,10,12],[40,39,25,17,40,30,58,15,28,51],["not low","not low","not low","not low","not low","not low","not low","low","not low","not low"],["female","male","male","male","female","female","male","male","female","male"],["nonsmoker","nonsmoker","nonsmoker","nonsmoker","nonsmoker","nonsmoker","nonsmoker","smoker","nonsmoker","nonsmoker"],["married","married","not married","not married","married","married","not married","not married","married","not married"],["white","white","white","white","white","white","white","white","white","white"]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>ID<\/th>\n      <th>mage<\/th>\n      <th>weight<\/th>\n      <th>fage<\/th>\n      <th>mature<\/th>\n      <th>weeks<\/th>\n      <th>premie<\/th>\n      <th>visits<\/th>\n      <th>gained<\/th>\n      <th>lowbirthweight<\/th>\n      <th>sex<\/th>\n      <th>habit<\/th>\n      <th>marital<\/th>\n      <th>whitemom<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"columnDefs":[{"className":"dt-right","targets":[1,2,3,4,6,8,9]},{"orderable":false,"targets":0}],"order":[],"autoWidth":false,"orderClasses":false}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<section id="observed-data" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="observed-data"><span class="header-section-number">1.1</span> Observed data</h2>
<p><a href="#fig-births-slr" class="quarto-xref">Figure&nbsp;1</a> visualizes the relationship between <code>mage</code> and <code>weight</code> for this sample of 1,000 birth records.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> births14, </span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> mage, <span class="at">y =</span> weight)) <span class="sc">+</span> </span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>() <span class="sc">+</span> </span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>) <span class="sc">+</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Mother's Age"</span>, </span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Birth Weight of Baby (lbs)"</span>) <span class="sc">+</span> </span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  my_theme</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-births-slr" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-births-slr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="week8-reading_files/figure-html/fig-births-slr-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-births-slr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Weight of baby at birth (in lbs) as explained by mother’s age.
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#tbl-births-slr" class="quarto-xref">Table&nbsp;1</a> displays the estimated regression coefficients for modeling the relationship between <code>mage</code> and <code>weight</code> for this sample of 1,000 birth records.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>births_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(weight <span class="sc">~</span> mage, <span class="at">data =</span> births14)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">get_regression_table</span>(births_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div id="tbl-births-slr" class="cell quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-births-slr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: The least squares estimates of the intercept and slope for modeling the relationship between baby’s birth weight and mother’s age.
</figcaption>
<div aria-describedby="tbl-births-slr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">intercept</td>
<td style="text-align: right;">6.793</td>
</tr>
<tr class="even">
<td style="text-align: left;">mage</td>
<td style="text-align: right;">0.014</td>
</tr>
</tbody>
</table>


</div>
</div>
</figure>
</div>
</div>
<p>Based on these coefficients, the estimated regression equation is:</p>
<p><span class="math display">\[ \widehat{\text{birth weight}} = -6.793 + 0.014 \times \text{mother's age}\]</span></p>
<p>Based on the regression equation, it appear that for every year older a mother is, we would expect the mean birth weight to increase by approximately 0.014 lbs. This seems like a small value, which is confirmed when we increase the mother’s age by 10-years, which is associated with a 0.14 lb increase in birth weight.</p>
</section>
<section id="research-question" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="research-question"><span class="header-section-number">1.2</span> Research question</h2>
<p>This raises the question of whether this change is “large<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> enough” to suggest that there <strong>is</strong> a relationship between the birth weight of a baby and the age of the mother. Could we obtain a slope statistic of 0.014 occur just by chance, in a hypothetical world where there is no relationship between a baby’s birth weight and a mother’s age? In other words, what role does <em>sampling variation</em> play in this hypothetical world? To answer this question, we’ll again rely on a computer to run <em>simulations</em>.</p>
</section>
<section id="sec-ht-activity" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="sec-ht-activity"><span class="header-section-number">1.3</span> Simulating data</h2>
<p>First, try to imagine a hypothetical universe where there is no relationship between the birth weight of a baby and a mother’s age. In such a hypothetical universe, the birth weight of a baby would be entirely determined from other variables (e.g., genetics, mother’s habits, etc.)</p>
<p>Bringing things back to the <code>births14</code> data frame, the <code>mage</code> variable would thus be an irrelevant label, as is has no relationship with the birth weight of the baby. Since is has no bearing on the birth weight, we could randomly reassign these ages by “shuffling” them!</p>
<p>To illustrate this idea, let’s narrow our focus to six arbitrarily chosen birth records (of the 1,000) <a href="#tbl-shuffled-mage" class="quarto-xref">Table&nbsp;2</a>. The <code>weight</code> column displays the birth weight of the baby. The <code>mage</code> column displays the age of the mother. However, in our hypothesized universe there is no relationship between a baby’s birth weight and a mother’s age, so it would be of no consequence to randomly “shuffle” the values of <code>mage</code>. The <code>shuffled_mage</code> column shows one such possible random shuffling.</p>
<div class="cell">
<div id="tbl-shuffled-mage" class="cell quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-shuffled-mage-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: One example of shuffling mage variable.
</figcaption>
<div aria-describedby="tbl-shuffled-mage-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">ID</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">weight</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mage</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">shuffled_mage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">726</td>
<td style="text-align: right;">8.75</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">26</td>
</tr>
<tr class="even">
<td style="text-align: right;">602</td>
<td style="text-align: right;">8.53</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">22</td>
</tr>
<tr class="odd">
<td style="text-align: right;">326</td>
<td style="text-align: right;">6.81</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">24</td>
</tr>
<tr class="even">
<td style="text-align: right;">79</td>
<td style="text-align: right;">7.01</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">18</td>
</tr>
<tr class="odd">
<td style="text-align: right;">974</td>
<td style="text-align: right;">6.03</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">32</td>
</tr>
<tr class="even">
<td style="text-align: right;">884</td>
<td style="text-align: right;">6.32</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">28</td>
</tr>
</tbody>
</table>


</div>
</div>
</figure>
</div>
</div>
<p>Again, such random shuffling of the <code>mage</code> label only makes sense in our hypothesized universe where there is no relationship between the birth weight of a baby and a mother’s age. How could we extend this shuffling of the <code>mage</code> variable to all 1,000 birth records by hand?</p>
<p>One way would be writing the 1,000 <code>weight</code>s and <code>mage</code>s on a set of 1,000 cards. We would then rip each card in half, as we are assuming there is no relationship between these variables. We would then be left with 1,000 <code>weight</code> cards in one hat and 1,000 <code>mage</code> cards in a <em>different</em> hat. You could then draw one card out of the <code>weight</code> hat and one card out of the <code>mage</code> hat and staple them together to make a new (<code>weight</code>, <code>mage</code>) ordered pair. This process of drawing one card out of each hat and stapling them together would be repeated until we had paired each <code>mage</code> card with a new <code>weight</code> card.</p>
<p>I’ve done one such reshuffling and plotted the original dataset and the shuffled dataset side-by-side in <a href="#fig-original-shuffle-comparison" class="quarto-xref">Figure&nbsp;2</a>. It appears that the slope of the regression line for the shuffled data is much less steep (closer to horizontal) than in the original data.</p>
<div class="cell" data-layout-nrow="1">
<div id="fig-original-shuffle-comparison" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-original-shuffle-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-original-shuffle-comparison" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-original-shuffle-comparison-1" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-original-shuffle-comparison-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="week8-reading_files/figure-html/fig-original-shuffle-comparison-1.png" class="img-fluid figure-img" data-ref-parent="fig-original-shuffle-comparison" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-original-shuffle-comparison-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Original values of mother’s age
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-original-shuffle-comparison" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-original-shuffle-comparison-2" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-original-shuffle-comparison-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="week8-reading_files/figure-html/fig-original-shuffle-comparison-2.png" class="img-fluid figure-img" data-ref-parent="fig-original-shuffle-comparison" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-original-shuffle-comparison-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Shuffled values of mother’s age
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-original-shuffle-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Scatterplots of relationship between baby’s birth weight and mother’s age.
</figcaption>
</figure>
</div>
</div>
<p>Let’s compare these slope estimates between the two datasets:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>shuffled_births14 <span class="sc">%&gt;%</span> </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">specify</span>(<span class="at">response =</span> weight, <span class="at">explanatory =</span> mage) <span class="sc">%&gt;%</span> </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">calculate</span>(<span class="at">stat =</span> <span class="st">"slope"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Response: weight (numeric)
Explanatory: mage (numeric)
# A tibble: 1 × 1
    stat
   &lt;dbl&gt;
1 0.0142</code></pre>
</div>
</div>
<p>So, in this hypothetical universe where there is no relationship between a baby’s birth weight and a mother’s age, we obtained a slope of 0.014.</p>
<p>Notice that this slope statistic is not the same as the slope statistic of 0.014 that we originally observed. This is once again due to <em>sampling variation</em>. How can we better understand the effect of this sampling variation? By repeating this shuffling several times!</p>
</section>
<section id="shuffling-10-times" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="shuffling-10-times"><span class="header-section-number">1.4</span> Shuffling 10 times</h2>
<p>Alright, I’ve carried out the process of shuffling the dataset 9 more times. <a href="#tbl-ten-shuffled-mage" class="quarto-xref">Table&nbsp;3</a> displays the results of these shufflings.</p>
<div class="cell">
<div id="tbl-ten-shuffled-mage" class="cell quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ten-shuffled-mage-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: One example of shuffling mage variable.
</figcaption>
<div aria-describedby="tbl-ten-shuffled-mage-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">ID</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">weight</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mage</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">shuffle1</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">shuffle2</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">shuffle3</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">shuffle4</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">shuffle5</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">shuffle6</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">shuffle7</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">shuffle8</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">shuffle9</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">shuffle10</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">744</td>
<td style="text-align: right;">10.13</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">37</td>
<td style="text-align: right;">35</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">37</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">31</td>
</tr>
<tr class="even">
<td style="text-align: right;">426</td>
<td style="text-align: right;">5.94</td>
<td style="text-align: right;">36</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">27</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">36</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">34</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">26</td>
</tr>
<tr class="odd">
<td style="text-align: right;">144</td>
<td style="text-align: right;">5.07</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">36</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">27</td>
<td style="text-align: right;">37</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">38</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">34</td>
<td style="text-align: right;">20</td>
</tr>
<tr class="even">
<td style="text-align: right;">132</td>
<td style="text-align: right;">5.97</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">27</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">27</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">29</td>
<td style="text-align: right;">27</td>
</tr>
<tr class="odd">
<td style="text-align: right;">244</td>
<td style="text-align: right;">6.50</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">36</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">39</td>
<td style="text-align: right;">36</td>
</tr>
<tr class="even">
<td style="text-align: right;">581</td>
<td style="text-align: right;">7.28</td>
<td style="text-align: right;">29</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">27</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">38</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">35</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">27</td>
<td style="text-align: right;">27</td>
<td style="text-align: right;">14</td>
</tr>
</tbody>
</table>


</div>
</div>
</figure>
</div>
</div>
<!-- lineup plot -->
<p>For each of these 10 shuffles, I computed the slope statistic, and in <a href="#fig-ten-shuffles" class="quarto-xref">Figure&nbsp;3</a> I display their distribution in a histogram. I’ve also marked the observed slope statistic with a dark red line.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-ten-shuffles" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ten-shuffles-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="week8-reading_files/figure-html/fig-ten-shuffles-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ten-shuffles-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Distribution of shuffled slope statistics.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Before we discuss the distribution of the histogram, we need to remember one key detail: this histogram represents relationship between a baby’s birth weight and mother’s age that one would observe in our hypothesized universe where there is no relationship between these variables.</p>
<p>Observe first that the histogram is roughly centered at 0, which makes sense. A slope of 0 means there is no relationship between a baby’s birth weight and mother’s age, which is exactly what our hypothetical universe assumes!</p>
<p>However, while the values are centered at 0, there is variation about 0. This is because even in a hypothesized universe of no relationship between a baby’s birth weight and mother’s age, you will still likely observe a slight relationship because of chance sampling variation. Looking at the histogram in <a href="#fig-ten-shuffles" class="quarto-xref">Figure&nbsp;3</a>, such differences could even be as extreme as 0.02.</p>
<p>Turning our attention to what we observed in the <code>births14</code> dataset: the observed slope of 0.014 is is marked with a vertical dark line. Ask yourself: in a hypothesized world of no relationship between a baby’s birth weight and mother’s age, how likely would it be that we observe this slope statistic? That’s hard to say! It looks like there is only one statistic larger than the observed statistic out of ten, but that means we would expect to see a statistic bigger than what we saw 10% of the time in this hypothetical universe. To me, something happening 10% of the time doesn’t seem like a rare event.</p>
</section>
<section id="what-just-happened" class="level2" data-number="1.5">
<h2 data-number="1.5" class="anchored" data-anchor-id="what-just-happened"><span class="header-section-number">1.5</span> What just happened?</h2>
<p>What we just demonstrated in this activity is the statistical procedure known as hypothesis testing using a permutation test. The term ““permutation” is the mathematical term for “shuffling”: taking a series of values and reordering them randomly, as you did with the <code>mage</code> values.</p>
<p>In fact, permutations are another form of resampling, like the bootstrap method you performed last week. While the bootstrap method involves resampling <em>with</em> replacement, permutation methods involve resampling <em>without</em> replacement.</p>
<p>Think back to the exercise involving the slips of paper representing the 1,000 birth records from last week. After sampling a paper, you put the paper back into the hat. However, in this scenario, once we drew a <code>weight</code> and <code>age</code> card they were stapled together and never redrawn.</p>
<p>In our example, we saw that the observed slope in the <code>births14</code> dataset was somewhat inconsistent with the hypothetical universe, but only slightly. Thus, I would not be inclined to say that the observed relationship between a baby’s birth weight and a mother’s age (seen in the <code>births14</code> dataset) is that different from what I would expect to see if there was no relationship between these variables.</p>
</section>
</section>
<section id="sec-understanding-ht" class="level1 page-columns page-full" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Hypothesis tests</h1>
<p>Much like the terminology, notation, and definitions relating to sampling you saw last week, there are a lot of terminology, notation, and definitions related to hypothesis testing as well. Learning these may seem like a very daunting task at first. However, with practice, practice, and more practice, anyone can master them.</p>
<p>First, a <strong>hypothesis</strong> is a statement about the value of an unknown population parameter. In our example, our population parameter of interest is the slope of the relationship between baby’s birth weight and mother’s age for <strong>every</strong> baby born in the US in 2014. This parameter is notated with <span class="math inline">\(\beta_1\)</span>. Hypothesis tests can involve any of the population parameters. You may have seen hypothesis tests for means or proportions previously, and later in this class we will discuss tests for many means (ANOVA).</p>
<p>Second, a <strong>hypothesis test</strong> consists of a test between two competing hypotheses: (1) a <strong>null hypothesis</strong> <span class="math inline">\(H_0\)</span> (pronounced “H-naught”) versus (2) an <strong>alternative hypothesis</strong> <span class="math inline">\(H_A\)</span> (sometimes denoted <span class="math inline">\(H_1\)</span>).</p>
<p>Generally the null hypothesis is a claim that there is “no effect” or “no relationship.” In many cases, the null hypothesis represents the status quo or a situation that nothing interesting is happening. Furthermore, generally the alternative hypothesis is the claim the experimenter or researcher wants to establish or find evidence to support. It is viewed as a “competing” hypothesis to the null hypothesis <span class="math inline">\(H_0\)</span>. In our birth weights example, an appropriate hypothesis test would be:</p>
<center>
<p><span class="math inline">\(H_0:\)</span> there is no relationship between a baby’s birth weight and a mother’s age</p>
<p><span class="math inline">\(H_A:\)</span> there is a relationship between a baby’s birth weight and a mother’s age</p>
</center>
<p>Note some of the choices we have made. First, we set the null hypothesis <span class="math inline">\(H_0\)</span> to be that there is no relationship between a baby’s birth weight and a mother’s age and the competing alternative hypothesis <span class="math inline">\(H_A\)</span> to be that there is a relationship between a baby’s birth weight and a mother’s age. While it would not be wrong in principle to reverse the two, it is a convention in statistical inference that the null hypothesis is set to reflect a “null” situation where “nothing is going on.”</p>
<p>As we discussed earlier, in this case, <span class="math inline">\(H_0\)</span> corresponds to there being no relationship between a baby’s birth weight and a mother’s age. Furthermore, we set <span class="math inline">\(H_A\)</span> to be that there is a relationship between a baby’s birth weight and a mother’s age, which does not state what direction that relationship may be. This is called a <strong>two-sided alternative</strong>, whereas an alternative hypothesis which indicates the direction of the relationship (e.g., as age increases birth weight decreases) is called a <strong>one-sided alternative</strong>.</p>
<p>We can re-express the formulation of our hypothesis test using the mathematical notation for our population parameter of interest, the slope of the relationship between a baby’s birth weight and a mother’s age for all babies born in the US in 2014 – <span class="math inline">\(\beta_1\)</span>:</p>
<center>
<p><span class="math inline">\(H_0: \beta_1 = 0\)</span></p>
<p><span class="math inline">\(H_A: \beta_1 \neq 0\)</span></p>
</center>
<p>Observe how the alternative hypothesis <span class="math inline">\(H_A\)</span> is two-sided with <span class="math inline">\(\beta_1 \neq 0\)</span>. Had we opted for a one-sided alternative, we would have set <span class="math inline">\(\beta_1 &gt; 0\)</span> or <span class="math inline">\(\beta_1 &gt; 0\)</span>. To keep things simple for now, we’ll stick with the simpler two-sided alternative. We will discuss why I believe it is better for science to do two-sided tests later this week in your Statistical Critique.</p>
<p>Third, a <strong>test statistic</strong> is a <em>point estimate / sample statistic</em> formula used for hypothesis testing. Note that a sample statistic is merely a summary statistic based on a sample of observations. Fourth, the <strong>observed test statistic</strong> is the value of the test statistic that we observed in real life. In our case, we computed this value using the data saved in the <code>births14</code> data frame. It was the observed slope for the relationship between baby birth weights and mother’s age <span class="math inline">\(b_1 =\)</span> 0.014.</p>
<p>Fifth, the <strong>null distribution</strong> is the sampling distribution of the test statistic <em>assuming the null hypothesis</em> <span class="math inline">\(H_0\)</span> is true. Ooof! That’s a long one! Let’s unpack it slowly. The key to understanding the null distribution is that the null hypothesis <span class="math inline">\(H_0\)</span> is <em>assumed</em> to be true. We’re not saying that <span class="math inline">\(H_0\)</span> is true at this point, we’re only assuming it to be true for hypothesis testing purposes. In our case, this corresponds to our hypothesized universe of no relationship between baby birth weights and mother’s age. Assuming the null hypothesis <span class="math inline">\(H_0\)</span>, also stated as “Under <span class="math inline">\(H_0\)</span>,” how does the test statistic vary due to sampling variation? In our case, how will the slope statistics <span class="math inline">\(b_1\)</span> vary due to sampling under <span class="math inline">\(H_0\)</span>? Recall from last week that distributions displaying how point estimates vary due to sampling variation are called <em>sampling distributions</em>. The only additional thing to keep in mind about null distributions is that they are sampling distributions <em>assuming the null hypothesis</em> <span class="math inline">\(H_0\)</span> is true.</p>
<p>In our case, we previously visualized a null distribution in <a href="#fig-ten-shuffles" class="quarto-xref">Figure&nbsp;3</a>, which we re-display in <a href="#fig-ten-shuffles-revised" class="quarto-xref">Figure&nbsp;4</a> using our new notation and terminology. It is the distribution of the 10 sample slopes computed <em>assuming</em> a hypothetical universe of no relationship between baby birth weights and mother’s age. I’ve marked the value of the observed test statistic of 0.014 with a vertical line.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-ten-shuffles-revised" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ten-shuffles-revised-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="week8-reading_files/figure-html/fig-ten-shuffles-revised-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ten-shuffles-revised-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Null distribution and observed test statistic.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Sixth, the <span class="math inline">\(p\)</span>-value is the probability of obtaining a test statistic just as extreme or more extreme than the observed test statistic <em>assuming the null hypothesis</em> <span class="math inline">\(H_0\)</span> is true. Double ooof! Let’s unpack this slowly as well. You can think of the <span class="math inline">\(p\)</span>-value as a quantification of “surprise”: assuming <span class="math inline">\(H_0\)</span> is true, how surprised are we with what we observed? Or in our case, in our hypothesized universe of no relationship between baby birth weights and mother’s age, how surprised are we that we observed a slope statistic 0.014 from our collected samples assuming <span class="math inline">\(H_0\)</span> is true? Very surprised? Somewhat surprised? Not surprised?</p>
<p>The <span class="math inline">\(p\)</span>-value quantifies this probability, or in the case of our 10 slope statistics in <a href="#fig-ten-shuffles-revised" class="quarto-xref">Figure&nbsp;4</a>, what proportion had a more “extreme” result? Here, extreme is defined in terms of the alternative hypothesis <span class="math inline">\(H_A\)</span> that there is a relationship between baby birth weights and mother’s age, which does not state a direction. So, we need to look for statistics in <strong>both tails</strong>, for positive relationships and negative relationships.</p>

<div class="no-row-height column-margin column-container"><div class="">
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Accepting the null
</div>
</div>
<div class="callout-body-container callout-body">
<p>Careful! Failing to reject the null hypothesis is not the same as accepting the null hypothesis! You cannot state that someone is innocent just because there was not sufficient evidence they were guilty.</p>
</div>
</div>
</div></div><p>In this case, 1 times out of 10, we obtained a difference in proportion greater than or equal to the observed slope of 0.014. As I suggested before, this event doesn’t seem that rare as it could occur 10% of the time. As our observed slope is not vastly different from what we would expect to occur if the null was true, we should <em>fail to reject</em> the hypothesized universe.</p>
<p>Seventh and lastly, in many hypothesis testing procedures, it is commonly recommended to set the <strong>significance level</strong> of the test beforehand. It is denoted by the Greek letter <span class="math inline">\(\alpha\)</span> (pronounced “alpha”). This value acts as a cutoff on the <span class="math inline">\(p\)</span>-value, where if the <span class="math inline">\(p\)</span>-value falls below <span class="math inline">\(\alpha\)</span>, we would “reject the null hypothesis <span class="math inline">\(H_0\)</span>.” Alternatively, if the <span class="math inline">\(p\)</span>-value does not fall below <span class="math inline">\(\alpha\)</span>, we would “fail to reject <span class="math inline">\(H_0\)</span>.”</p>
<p>While different fields tend to use different values of <span class="math inline">\(\alpha\)</span>, some commonly used values for <span class="math inline">\(\alpha\)</span> are 0.1, 0.01, and 0.05; with 0.05 being the choice people often make without putting much thought into it. We’ll talk more about <span class="math inline">\(\alpha\)</span> significance levels in <a href="#sec-ht-interpretation" class="quarto-xref">Section&nbsp;4</a>, but first let’s fully conduct the hypothesis test corresponding to our <code>births14</code> example using the <code>infer</code> package.</p>
</section>
<section id="infer-workflow-ht" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Conducting a hypothesis test using <strong>infer</strong></h1>
<p>Last week, you learned how to to construct confidence intervals using the <strong>infer</strong> R package. The infer package contains a workflow for constructing confidence intervals which emphasizes each of the steps in the underlying process. In <a href="#fig-infer-ci" class="quarto-xref">Figure&nbsp;5</a>, we see that this workflow is comprised of functions whose names describe what they do:</p>
<ol type="1">
<li><code>specify()</code> the variables of interest in your data frame.</li>
<li><code>generate()</code> replicates of bootstrap resamples with replacement.</li>
<li><code>calculate()</code> the summary statistic of interest.</li>
<li><code>visualize()</code> the resulting bootstrap distribution and confidence interval.</li>
</ol>
<div id="fig-infer-ci" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-infer-ci-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/whole_process_ci.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-infer-ci-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Process for constructing <strong>confidence intervals</strong> with the infer package.
</figcaption>
</figure>
</div>
<p>This week, we’ll see how we can modify this process to instead conduct hypothesis tests. You’ll notice that the basic outline of the workflow is almost identical, except for an additional <code>hypothesize()</code> step between the <code>specify()</code> and <code>generate()</code> steps, as can be seen in <a href="#fig-infer-ht" class="quarto-xref">Figure&nbsp;6</a>.</p>
<div id="fig-infer-ht" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-infer-ht-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/whole_process_ht.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-infer-ht-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Process for conducting <strong>hypothesis tests</strong> with the infer package.
</figcaption>
</figure>
</div>
<p>Throughout this section, we’ll use a pre-specified significance level <span class="math inline">\(\alpha\)</span> = 0.05 for our hypothesis tests. I’ll leave the discussion on the choice of this <span class="math inline">\(\alpha\)</span> value until later on in <a href="#sec-choosing-alpha" class="quarto-xref">Section&nbsp;4.3</a>.</p>
<section id="specify-variables" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="specify-variables"><span class="header-section-number">3.1</span> <code>specify()</code> variables</h2>
<p>Recall that we use the <code>specify()</code> verb to specify the response variable and, if needed, any explanatory variables for our study. In this case, since we are interested in the linear relationship between a baby’s birth weight and a mother’s age, we set <code>weight</code> as the response variable and <code>mage</code> as the explanatory variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>births14 <span class="sc">%&gt;%</span> </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">specify</span>(<span class="at">response =</span> weight, <span class="at">explanatory =</span> mage) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Response: weight (numeric)
Explanatory: mage (numeric)
# A tibble: 1,000 × 2
   weight  mage
    &lt;dbl&gt; &lt;dbl&gt;
 1   6.96    34
 2   8.86    31
 3   7.51    36
 4   6.19    16
 5   6.75    31
 6   6.69    26
 7   6.13    36
 8   6.74    24
 9   8.94    32
10   9.12    26
# ℹ 990 more rows</code></pre>
</div>
</div>
<p>Again, notice how the <code>births14</code> data itself doesn’t change, but the <code>Response: weight (numeric)</code> and <code>Explanatory: mage (numeric)</code> <em>meta-data</em> do. This is similar to how the <code>group_by()</code> verb from <code>dplyr</code> doesn’t change the data, but only adds “grouping” meta-data, as we saw in Week 3.</p>
</section>
<section id="hypothesize-the-null" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="hypothesize-the-null"><span class="header-section-number">3.2</span> <code>hypothesize()</code> the null</h2>
<p>In order to conduct hypothesis tests using the <code>infer</code> workflow, we need a new step not present for confidence intervals: <code>hypothesize()</code>. Recall from <a href="#sec-understanding-ht" class="quarto-xref">Section&nbsp;2</a> that our hypothesis test was</p>
<center>
<p><span class="math inline">\(H_0: \beta_1 = 0\)</span></p>
<p><span class="math inline">\(H_A: \beta_1 \neq 0\)</span></p>
</center>
<p>In other words, the null hypothesis <span class="math inline">\(H_0\)</span> corresponding to our “hypothesized universe” stated that there was no relationship between a baby’s birth weight and a mother’s age. We set this null hypothesis <span class="math inline">\(H_0\)</span> in our <code>infer</code> workflow using the <code>hypothesize()</code> function. We do, however, need to declare what we are assuming about the relationship between our variables. For our regression we are assuming there is no relationship between our variables or that they are<code>"independent"</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>births14 <span class="sc">%&gt;%</span> </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">specify</span>(<span class="at">response =</span> weight, <span class="at">explanatory =</span> mage) <span class="sc">%&gt;%</span> </span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">hypothesize</span>(<span class="at">null =</span> <span class="st">"independence"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Response: weight (numeric)
Explanatory: mage (numeric)
Null Hypothesis: independence
# A tibble: 1,000 × 2
   weight  mage
    &lt;dbl&gt; &lt;dbl&gt;
 1   6.96    34
 2   8.86    31
 3   7.51    36
 4   6.19    16
 5   6.75    31
 6   6.69    26
 7   6.13    36
 8   6.74    24
 9   8.94    32
10   9.12    26
# ℹ 990 more rows</code></pre>
</div>
</div>
<p>Again, the data has not changed yet. In fact, we’ve just added one additional piece of <em>meta-data</em> the null hypothesis we are assuming.</p>
</section>
<section id="generate-replicates" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="generate-replicates"><span class="header-section-number">3.3</span> <code>generate()</code> replicates</h2>
<p>After we <code>hypothesize()</code> the null hypothesis, we <code>generate()</code> replicates of “shuffled” datasets assuming the null hypothesis is true. We do this by repeating the shuffling exercise you performed in <a href="#sec-ht-activity" class="quarto-xref">Section&nbsp;1.3</a> several times. Instead of merely doing it 10 times, let’s use the computer to repeat this 1000 times by setting <code>reps = 1000</code> in the <code>generate()</code> function. However, unlike for confidence intervals where we generated replicates using <code>type = "bootstrap"</code> resampling with replacement, we’ll now perform shuffles/permutations by setting <code>type = "permute"</code>. Recall that shuffles / permutations are a kind of resampling, but unlike the bootstrap method, they involve resampling <em>without</em> replacement.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>births_generate <span class="ot">&lt;-</span> births14 <span class="sc">%&gt;%</span> </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">specify</span>(<span class="at">response =</span> weight, <span class="at">explanatory =</span> mage) <span class="sc">%&gt;%</span> </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">hypothesize</span>(<span class="at">null =</span> <span class="st">"independence"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">generate</span>(<span class="at">reps =</span> <span class="dv">1000</span>, <span class="at">type =</span> <span class="st">"permute"</span>)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>births_generate</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Response: weight (numeric)
Explanatory: mage (numeric)
Null Hypothesis: independence
# A tibble: 1,000,000 × 3
# Groups:   replicate [1,000]
   weight  mage replicate
    &lt;dbl&gt; &lt;dbl&gt;     &lt;int&gt;
 1   6.56    34         1
 2   9       31         1
 3   6.96    36         1
 4   7.8     16         1
 5   8.39    31         1
 6   6.56    26         1
 7   8.95    36         1
 8   7.94    24         1
 9   8.52    32         1
10   6.13    26         1
# ℹ 999,990 more rows</code></pre>
</div>
</div>
<p>Observe that the resulting data frame has 1,000,000 rows. This is because we performed shuffles / permutations for each of the 1000 rows 1000 times and <span class="math inline">\(1,000,000 = 1000 \cdot 1000\)</span>. If you explore the <code>births_generate</code> data frame, you would notice that the variable <code>replicate</code> indicates which resample each row belongs to. So it has the value <code>1</code> 1000 times, the value <code>2</code> 1000 times, all the way through to the value 1000 1000 times.</p>
</section>
<section id="calculate-summary-statistics" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="calculate-summary-statistics"><span class="header-section-number">3.4</span> <code>calculate()</code> summary statistics</h2>
<p>Now that we have generated 1000 replicates of “shuffles” assuming the null hypothesis is true, let’s <code>calculate()</code> the appropriate summary statistic for each of our 1000 shuffles. From <a href="#sec-understanding-ht" class="quarto-xref">Section&nbsp;2</a>, point estimates related to hypothesis testing have a specific name: <em>test statistics</em>. Since the unknown population parameter of interest is the relationship between baby birth weights and mother’s ages for all births in the US in 2014, <span class="math inline">\(\beta_1\)</span>, the test statistic here is the sample slope, <span class="math inline">\(b_1\)</span>. For each of our 1000 shuffles, we can calculate this test statistic by setting <code>stat = "slope"</code>.</p>
<p>Let’s save the result in a data frame called <code>null_distribution</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>null_distribution <span class="ot">&lt;-</span> births14 <span class="sc">%&gt;%</span> </span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">specify</span>(<span class="at">response =</span> weight, <span class="at">explanatory =</span> mage) <span class="sc">%&gt;%</span> </span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">hypothesize</span>(<span class="at">null =</span> <span class="st">"independence"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">generate</span>(<span class="at">reps =</span> <span class="dv">1000</span>, <span class="at">type =</span> <span class="st">"permute"</span>)<span class="sc">%&gt;%</span> </span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">calculate</span>(<span class="at">stat =</span> <span class="st">"slope"</span>)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>null_distribution</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Response: weight (numeric)
Explanatory: mage (numeric)
Null Hypothesis: independence
# A tibble: 1,000 × 2
   replicate     stat
       &lt;int&gt;    &lt;dbl&gt;
 1         1  0.00258
 2         2  0.00641
 3         3 -0.00803
 4         4  0.00647
 5         5 -0.00373
 6         6 -0.0193 
 7         7 -0.00970
 8         8  0.00394
 9         9 -0.0201 
10        10 -0.00136
# ℹ 990 more rows</code></pre>
</div>
</div>
<p>Observe that we have 1000 values of <code>stat</code>, each representing one instance of <span class="math inline">\(b_1\)</span> in a hypothesized world of no relationship between these variables. Observe as well that we chose the name of this data frame carefully: <code>null_distribution</code>. Recall once again from <a href="#sec-understanding-ht" class="quarto-xref">Section&nbsp;2</a> that sampling distributions when the null hypothesis <span class="math inline">\(H_0\)</span> is assumed to be true have a special name: the <em>null distribution</em>.</p>
<p>What was the <em>observed</em> relationship between a baby’s birth weight and a mother’s age in the <code>births14</code> dataset? In other words, what was the <em>observed test statistic</em> <span class="math inline">\(b_1\)</span>? We could calculate this statistic two ways:</p>
<ol type="1">
<li>fitting a <code>lm()</code> and grabbing the coefficients using <code>get_regression_table()</code></li>
<li>using infer to <code>calculate()</code> the observed statistic</li>
</ol>
<p>Going with option two, the process would look like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>obs_slope <span class="ot">&lt;-</span> births14 <span class="sc">%&gt;%</span> </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">specify</span>(<span class="at">response =</span> weight, <span class="at">explanatory =</span> mage) <span class="sc">%&gt;%</span> </span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">calculate</span>(<span class="at">stat =</span> <span class="st">"slope"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> mage 
0.014 </code></pre>
</div>
</div>
</section>
<section id="visualize-the-p-value" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="visualize-the-p-value"><span class="header-section-number">3.5</span> <code>visualize()</code> the p-value</h2>
<p>The final step is to measure how surprised we are by a slope of 0.014 in a hypothesized universe where there is no relationship between a baby’s birth weight and a mother’s age. If the observed slope of 0.014 is highly unlikely, then we would be inclined to reject the validity of our hypothesized universe.</p>
<p>We start by visualizing the <em>null distribution</em> of our 1000 values of <span class="math inline">\(b_1\)</span> using <code>visualize()</code> in <a href="#fig-null-distribution-infer" class="quarto-xref">Figure&nbsp;7</a>. Recall that these are values of the sample slope assuming <span class="math inline">\(H_0\)</span> is true.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-null-distribution-infer" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-null-distribution-infer-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="week8-reading_files/figure-html/fig-null-distribution-infer-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-null-distribution-infer-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: Null distribution of slope statistic.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Let’s now add what happened in real life to <a href="#fig-null-distribution-infer" class="quarto-xref">Figure&nbsp;7</a>, the observed slope for the relationship between baby birth weights and mother’s ages of 0.014. Instead of merely adding a vertical line using <code>geom_vline()</code>, let’s use the <code>shade_p_value()</code> function with <code>obs_stat</code> set to the observed test statistic (observed slope statistic) value we saved in <code>obs_slope</code>.</p>
<p>Furthermore, we’ll set the <code>direction = "two-sided"</code> reflecting our alternative hypothesis <span class="math inline">\(H_A: \beta_1 \neq 0\)</span>, stating that there is a relationship between a baby’s birth weight and a mother’s age. As stated in <a href="#sec-understanding-ht" class="quarto-xref">Section&nbsp;2</a>, a two-sided hypothesis test does not make any assumptions about the direction of the relationship, meaning <span class="math inline">\(\beta_1 &lt; 0\)</span> and <span class="math inline">\(\beta_1 &gt; 0\)</span> are equally plausible. So, when calculating statistics that are “more extreme” than what we observed, we need to look in <em>both</em> tails.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">visualize</span>(null_distribution, <span class="at">bins =</span> <span class="dv">10</span>) <span class="sc">+</span> </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Permuted (Shuffled) Slope Statistic"</span>) <span class="sc">+</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">shade_p_value</span>(<span class="at">obs_stat =</span> obs_slope, <span class="at">direction =</span> <span class="st">"two-sided"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-null-distribution-infer-2" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-null-distribution-infer-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="week8-reading_files/figure-html/fig-null-distribution-infer-2-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-null-distribution-infer-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: Shaded histogram to show <span class="math inline">\(p\)</span>-value.
</figcaption>
</figure>
</div>
</div>
</div>
<p>In the resulting <a href="#fig-null-distribution-infer-2" class="quarto-xref">Figure&nbsp;8</a>, the solid dark line marks 0.014. However, what does the shaded-region correspond to? This is the <span class="math inline">\(p\)</span>-value. Recall the definition of the <span class="math inline">\(p\)</span>-value from <a href="#sec-understanding-ht" class="quarto-xref">Section&nbsp;2</a>:</p>
<blockquote class="blockquote">
<p>A <span class="math inline">\(p\)</span>-value is the probability of obtaining a test statistic just as or more extreme than the observed test statistic <em>assuming the null hypothesis</em> <span class="math inline">\(H_0\)</span> is true.</p>
</blockquote>
<p>So judging by the shaded region in <a href="#fig-null-distribution-infer-2" class="quarto-xref">Figure&nbsp;8</a>, it seems we would somewhat rarely observe a slope statistic of 0.014 or more extreme in a hypothesized universe where there is no relationship between a baby’s birth weight and a mother’s age. In other words, the <span class="math inline">\(p\)</span>-value is somewhat small. Hence, we might be inclined to reject this hypothesized universe, or using statistical language we would “reject <span class="math inline">\(H_0\)</span>.”</p>
<p>What fraction of the null distribution is shaded? In other words, what is the exact value of the <span class="math inline">\(p\)</span>-value? We can compute it using the <code>get_p_value()</code> function with the same arguments as the previous <code>shade_p_value()</code> code:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  p_value
    &lt;dbl&gt;
1   0.054</code></pre>
</div>
</div>
<p>Keeping the definition of a <span class="math inline">\(p\)</span>-value in mind, the probability of observing a slope statistic as large as 0.014 or something more extreme due to sampling variation alone in the null distribution is 0.054 = 5.4%. Since this <span class="math inline">\(p\)</span>-value is larger than our pre-specified significance level <span class="math inline">\(\alpha\)</span> = 0.05, we fail to reject the null hypothesis <span class="math inline">\(H_0: \beta_1 = 0\)</span>. In other words, this <span class="math inline">\(p\)</span>-value <strong>is not</strong> small enough to reject our hypothesized universe where there is no relationship between a baby’s birth weight and a mother’s age. Notice how our interpretation of this p-value does not state that we <em>accept</em> the null hypothesis. Rather, we have insufficient evidence to reject it. I will discuss these differences more in <a href="#sec-trial" class="quarto-xref">Section&nbsp;4.1</a>.</p>
<p>Observe that whether we reject the null hypothesis <span class="math inline">\(H_0\)</span> or not depends in large part on our choice of significance level <span class="math inline">\(\alpha\)</span>, as if we had chosen an <span class="math inline">\(\alpha\)</span> of 0.1, we would have had sufficient evidence to reject the null hypothesis. We’ll discuss this more in <a href="#sec-errors" class="quarto-xref">Section&nbsp;4.2</a>.</p>
</section>
</section>
<section id="sec-ht-interpretation" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Interpreting a hypothesis test</h1>
<p>Interpreting the results of hypothesis tests is one of the more challenging aspects of this method for statistical inference. In this section, we focus on ways to help with deciphering the process and address some common misconceptions.</p>
<section id="sec-trial" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="sec-trial"><span class="header-section-number">4.1</span> Two possible outcomes</h2>
<p>In <a href="#sec-understanding-ht" class="quarto-xref">Section&nbsp;2</a>, we mentioned that given a pre-specified significance level <span class="math inline">\(\alpha\)</span> there are two possible outcomes of a hypothesis test:</p>
<ul>
<li>If the <span class="math inline">\(p\)</span>-value is less than <span class="math inline">\(\alpha\)</span>, then we <em>reject</em> the null hypothesis <span class="math inline">\(H_0\)</span> in favor of <span class="math inline">\(H_A\)</span>.</li>
<li>If the <span class="math inline">\(p\)</span>-value is greater than or equal to <span class="math inline">\(\alpha\)</span>, we <em>fail to reject</em> the null hypothesis <span class="math inline">\(H_0\)</span>.</li>
</ul>
<p>Unfortunately, the latter result is often misinterpreted as “accepting the null hypothesis <span class="math inline">\(H_0\)</span>.” While at first glance it may seem that the statements “failing to reject <span class="math inline">\(H_0\)</span>” and “accepting <span class="math inline">\(H_0\)</span>” are equivalent, there actually is a subtle difference. Saying that we “accept the null hypothesis <span class="math inline">\(H_0\)</span>” is equivalent to stating that “we think the null hypothesis <span class="math inline">\(H_0\)</span> is true.” However, saying that we “fail to reject the null hypothesis <span class="math inline">\(H_0\)</span>” is saying something else: “While <span class="math inline">\(H_0\)</span> might still be false, we don’t have enough evidence to say so.” In other words, there is an absence of enough proof. However, the absence of proof is not proof of absence. 🧐</p>
<p>To further shed light on this distinction, let’s use the United States criminal justice system as an analogy. A criminal trial in the United States is a similar situation to hypothesis tests whereby a choice between two contradictory claims must be made about a defendant who is on trial:</p>
<ol type="1">
<li>The defendant is truly either “innocent” or “guilty.”</li>
<li>The defendant is presumed “innocent until proven guilty.”</li>
<li>The defendant is found guilty only if there is <em>strong evidence</em> that the defendant is guilty. The phrase “beyond a reasonable doubt” is often used as a guideline for determining a cutoff for when enough evidence exists to find the defendant guilty.</li>
<li>The defendant is found to be either “not guilty” or “guilty” in the ultimate verdict.</li>
</ol>
<p>In other words, <em>not guilty</em> verdicts are not suggesting the defendant is <em>innocent</em>, but instead that “while the defendant may still actually be guilty, there wasn’t enough evidence to prove this fact.” Now let’s make the connection with hypothesis tests:</p>
<ol type="1">
<li>Either the null hypothesis <span class="math inline">\(H_0\)</span> or the alternative hypothesis <span class="math inline">\(H_A\)</span> is true.</li>
<li>Hypothesis tests are conducted assuming the null hypothesis <span class="math inline">\(H_0\)</span> is true.</li>
<li>We reject the null hypothesis <span class="math inline">\(H_0\)</span> in favor of <span class="math inline">\(H_A\)</span> only if the evidence found in the sample suggests that <span class="math inline">\(H_A\)</span> is true. The significance level <span class="math inline">\(\alpha\)</span> is used as a guideline to set the threshold on just how strong of evidence we require.</li>
<li>We ultimately decide to either “fail to reject <span class="math inline">\(H_0\)</span>” or “reject <span class="math inline">\(H_0\)</span>.”</li>
</ol>
<p>So while gut instinct may suggest “failing to reject <span class="math inline">\(H_0\)</span>” and “accepting <span class="math inline">\(H_0\)</span>” are equivalent statements, they are not. “Accepting <span class="math inline">\(H_0\)</span>” is equivalent to finding a defendant innocent. However, courts do not find defendants “innocent,” but rather they find them “not guilty.” Putting things differently, defense attorneys do not need to prove that their clients are innocent, rather they only need to prove that clients are not “guilty beyond a reasonable doubt”.</p>
<p>So going back to the <code>births14</code> dataset, recall that our hypothesis test was <span class="math inline">\(H_0: \beta_1 = 0\)</span> versus <span class="math inline">\(H_A: \beta_1 \neq 0\)</span> and that we used a pre-specified significance level of <span class="math inline">\(\alpha\)</span> = 0.05. We found a <span class="math inline">\(p\)</span>-value of 0.054. Since the <span class="math inline">\(p\)</span>-value was smaller than <span class="math inline">\(\alpha\)</span> = 0.05, we rejected <span class="math inline">\(H_0\)</span>. In other words, we found needed levels of evidence in this particular sample to say that <span class="math inline">\(H_0\)</span> is false at the <span class="math inline">\(\alpha\)</span> = 0.05 significance level. We also state this conclusion using non-statistical language: we found enough evidence in this data to suggest that there was gender discrimination at play.</p>
</section>
<section id="sec-errors" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="sec-errors"><span class="header-section-number">4.2</span> Types of errors</h2>
<p>Unfortunately, there is some chance a jury or a judge can make an incorrect decision in a criminal trial by reaching the wrong verdict. For example, finding a truly innocent defendant “guilty”. Or on the other hand, finding a truly guilty defendant “not guilty.” This can often stem from the fact that prosecutors don’t have access to all the relevant evidence, but instead are limited to whatever evidence the police can find.</p>
<p>The same holds for hypothesis tests. We can make incorrect decisions about a population parameter because we only have a sample of data from the population and thus sampling variation can lead us to incorrect conclusions.</p>
<p>There are two possible erroneous conclusions in a criminal trial: either (1) a truly innocent person is found guilty or (2) a truly guilty person is found not guilty. Similarly, there are two possible errors in a hypothesis test: either (1) rejecting <span class="math inline">\(H_0\)</span> when in fact <span class="math inline">\(H_0\)</span> is true, called a <strong>Type I error</strong> or (2) failing to reject <span class="math inline">\(H_0\)</span> when in fact <span class="math inline">\(H_0\)</span> is false, called a <strong>Type II error</strong>. Another term used for “Type I error” is “false positive,” while another term for “Type II error” is “false negative.”</p>
<p>This risk of error is the price researchers pay for basing inference on a sample instead of performing a census on the entire population. But as we’ve seen in our numerous examples and activities so far, censuses are often very expensive and other times impossible, and thus researchers have no choice but to use a sample. Thus in any hypothesis test based on a sample, we have no choice but to tolerate some chance that a Type I error will be made and some chance that a Type II error will occur.</p>
<p>To help understand the concepts of Type I error and Type II errors, we apply these terms to our criminal justice analogy in <a href="#fig-trial-errors-table" class="quarto-xref">Figure&nbsp;9</a>.</p>
<div id="fig-trial-errors-table" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-trial-errors-table-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/gt_error_table.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-trial-errors-table-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9: Type I and Type II errors in criminal trials.
</figcaption>
</figure>
</div>
<p>Thus a Type I error corresponds to incorrectly putting a truly innocent person in jail, whereas a Type II error corresponds to letting a truly guilty person go free. Let’s show the corresponding table in <a href="#fig-trial-errors-table-ht" class="quarto-xref">Figure&nbsp;10</a> for hypothesis tests.</p>
<div id="fig-trial-errors-table-ht" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-trial-errors-table-ht-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/gt_error_table_ht.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-trial-errors-table-ht-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10: Type I and Type II errors in hypothesis tests.
</figcaption>
</figure>
</div>
</section>
<section id="sec-choosing-alpha" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="sec-choosing-alpha"><span class="header-section-number">4.3</span> How do we choose alpha?</h2>
<p>If we are using a sample to make inferences about a population, we run the risk of making errors. For confidence intervals, a corresponding “error” would be constructing a confidence interval that does not contain the true value of the population parameter. For hypothesis tests, this would be making either a Type I or Type II error. Obviously, we want to minimize the probability of either error; we want a small probability of making an incorrect conclusion:</p>
<ul>
<li>The probability of a Type I Error occurring is denoted by <span class="math inline">\(\alpha\)</span>. The value of <span class="math inline">\(\alpha\)</span> is called the <em>significance level</em> of the hypothesis test, which we defined in <a href="#sec-understanding-ht" class="quarto-xref">Section&nbsp;2</a>.</li>
<li>The probability of a Type II Error is denoted by <span class="math inline">\(\beta\)</span>. The value of <span class="math inline">\(1-\beta\)</span> is known as the <em>power</em> of the hypothesis test.</li>
</ul>
<p>In other words, <span class="math inline">\(\alpha\)</span> corresponds to the probability of incorrectly rejecting <span class="math inline">\(H_0\)</span> when in fact <span class="math inline">\(H_0\)</span> is true. On the other hand, <span class="math inline">\(\beta\)</span> corresponds to the probability of incorrectly failing to reject <span class="math inline">\(H_0\)</span> when in fact <span class="math inline">\(H_0\)</span> is false.</p>
<p>Ideally, we want <span class="math inline">\(\alpha = 0\)</span> and <span class="math inline">\(\beta = 0\)</span>, meaning that the chance of making either error is 0. However, this can never be the case in any situation where we are sampling for inference. There will always be the possibility of making either error when we use sample data. Furthermore, these two error probabilities are inversely related. As the probability of a Type I error goes down, the probability of a Type II error goes up.</p>
<p>What is typically done in practice is to fix the probability of a Type I error by pre-specifying a significance level <span class="math inline">\(\alpha\)</span> and then try to minimize <span class="math inline">\(\beta\)</span>. In other words, we will tolerate a certain fraction of incorrect rejections of the null hypothesis <span class="math inline">\(H_0\)</span>, and then try to minimize the fraction of incorrect non-rejections of <span class="math inline">\(H_0\)</span>.</p>
<p>So for example if we used <span class="math inline">\(\alpha\)</span> = 0.01, we would be using a hypothesis testing procedure that in the long run would incorrectly reject the null hypothesis <span class="math inline">\(H_0\)</span> one percent of the time. This is analogous to setting the confidence level of a confidence interval.</p>
<p>So what value should you use for <span class="math inline">\(\alpha\)</span>? Different fields have different conventions, but some commonly used values include 0.10, 0.05, 0.01, and 0.001. However, it is important to keep in mind that if you use a relatively small value of <span class="math inline">\(\alpha\)</span>, then all things being equal, <span class="math inline">\(p\)</span>-values will have a harder time being less than <span class="math inline">\(\alpha\)</span>. Thus we would reject the null hypothesis less often. In other words, we would reject the null hypothesis <span class="math inline">\(H_0\)</span> only if we have <em>very strong</em> evidence to do so. This is known as a “conservative” test.</p>
<p>On the other hand, if we used a relatively large value of <span class="math inline">\(\alpha\)</span>, then all things being equal, <span class="math inline">\(p\)</span>-values will have an easier time being less than <span class="math inline">\(\alpha\)</span>. Thus we would reject the null hypothesis more often. In other words, we would reject the null hypothesis <span class="math inline">\(H_0\)</span> even if we only have <em>mild</em> evidence to do so. This is known as a “liberal” test.</p>
</section>
</section>
<section id="comparing-infer-workflows" class="level1 page-columns page-full" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Comparison with confidence intervals</h1>
<p>One of the great things about the <code>infer</code> package is that we can jump seamlessly between conducting hypothesis tests and constructing confidence intervals with minimal changes! Recall the code from the previous section that creates the null distribution, which in turn is needed to compute the <span class="math inline">\(p\)</span>-value:</p>
<p>To create the corresponding bootstrap distribution needed to construct a 95% confidence interval for <span class="math inline">\(\beta_1\)</span>, we only need to make two changes. First, we remove the <code>hypothesize()</code> step since we are no longer assuming a null hypothesis <span class="math inline">\(H_0\)</span> is true. We can do this by deleting or commenting out the <code>hypothesize()</code> line of code. Second, we switch the <code>type</code> of resampling in the <code>generate()</code> step to be <code>"bootstrap"</code> instead of <code>"permute"</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>bootstrap_distribution <span class="ot">&lt;-</span> births14 <span class="sc">%&gt;%</span> </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">specify</span>(<span class="at">response =</span> weight, <span class="at">explanatory =</span> mage) <span class="sc">%&gt;%</span> </span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Change 1 - Remove hypothesize():</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="co">#hypothesize(null = "independence") %&gt;% </span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Change 2 - Switch type from "permute" to "bootstrap":</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">generate</span>(<span class="at">reps =</span> <span class="dv">1000</span>, <span class="at">type =</span> <span class="st">"bootstrap"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">calculate</span>(<span class="at">stat =</span> <span class="st">"slope"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Using this <code>bootstrap_distribution</code>, let’s first compute the percentile-based confidence intervals, the same way we did last week:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  lower_ci upper_ci
     &lt;dbl&gt;    &lt;dbl&gt;
1 0.000174   0.0284</code></pre>
</div>
</div>
<p>Using our shorthand interpretation for 95% confidence intervals we learned last week, we are 95% “confident” that the relationship between baby birth weights and mother’s ages for all babies born in the US in 2014 is between (0.0002, 0.0284). Let’s visualize <code>bootstrap_distribution</code> and this percentile-based 95% confidence interval for <span class="math inline">\(\beta_1\)</span> in <a href="#fig-bootstrap-distribution-percentile" class="quarto-xref">Figure&nbsp;11</a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-bootstrap-distribution-percentile" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-bootstrap-distribution-percentile-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="week8-reading_files/figure-html/fig-bootstrap-distribution-percentile-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bootstrap-distribution-percentile-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11: Percentile-based 95% confidence interval.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Notice a key value that is not included in the 95% confidence interval for <span class="math inline">\(\beta_1\)</span>: the value 0. In other words, a difference of 0 is not included in our net, suggesting that the slope of the regression line is not 0.</p>

<div class="no-row-height column-margin column-container"><div class="">
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>If there is no linear relationship between two variables, then as <span class="math inline">\(x\)</span> increases nothing should happen with <span class="math inline">\(y\)</span>. This corresponds to the slope of the regression line being 0.</p>
</div>
</div>
</div></div><p>Since the bootstrap distribution appears to be roughly normally shaped, we can also use the standard error method as we did last week. In this case, we must specify the <code>point_estimate</code> argument as the observed slope statistic of 0.014. This value acts as the center of the confidence interval.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
   lower_ci upper_ci
      &lt;dbl&gt;    &lt;dbl&gt;
1 -0.000150   0.0281</code></pre>
</div>
</div>
<p>Let’s visualize <code>bootstrap_distribution</code> again, but now the standard error based 95% confidence interval for <span class="math inline">\(\beta_1\)</span> in <a href="#fig-bootstrap-distribution-se" class="quarto-xref">Figure&nbsp;12</a>. Notice how the value 0 <strong>is</strong> included in our confidence interval, suggesting that there is not sufficient evidence to say there is a relationship between a baby’s birth weight and a mother’s age. This is the same conclusion we reached with our p-value!</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-bootstrap-distribution-se" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-bootstrap-distribution-se-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="week8-reading_files/figure-html/fig-bootstrap-distribution-se-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bootstrap-distribution-se-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12: Standard error-based 95% confidence interval.
</figcaption>
</figure>
</div>
</div>
</div>
<!-- ## Statistical versus practical significance -->
<!-- You might be wondering, how could we have rejected the null hypothesis that $\beta_1 = 0$, when the lower bound of our confidence interval is **really** close to 0. That's a great question! This question gets at the heart of the difference between statistical and practical significance. -->
<!-- Statistical significance is defined by a $p$-value being smaller than some predetermined $\alpha$ threshold. However, the size of a p-value is not synonymous with the "effect size". By this I mean, a study can obtain a small $p$-value but have the estimated effect of the variable(s) be so small they would not be practically meaningful. In the context of the `births14` data, our hypothesis test concluded that there is a relationship between baby birth weights and mother's ages. Yet, based on the confidence interval, the estimated increase in birth weight for a 10-year increase in age is at most 0.2 lbs. I would not believe that the medical profession needs to provide medical interventions for younger mothers whose babies would have lower birth weights. -->
<!-- This is why I frequently favor confidence intervals over hypothesis tests, as they allow for you to assess *both* the statistical significance--by checking if the null hypothesized value is included in the interval---**and** the practical significance--by assessing the size of the estimated effect. -->
<!-- For example, suppose Cal Poly administrators are interested in studying the relationship between a student's GPA and the number of sporting events they attend. The administrators fit the regression model^[Well, likely their statistician or data scientist does. 😆] and find that there is a relationship between going to one a -->
</section>
<section id="theory-based-hypothesis-tests-confidence-intervals" class="level1 page-columns page-full" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Theory-based hypothesis tests &amp; confidence intervals</h1>
<p>We’ve so far focused only on obtaining confidence intervals and p-values using simulation-based methods, where we resampled from our original dataset. There is, however, another method we could have used to do both these things. This method is called a “theory-based” method, which relies on probability models, probability distributions, and a few assumptions to approximate the sampling and null distributions. This is in contrast to the approaches we’ve used thus far, where we relied on computer simulations to construct the bootstrap and null distribution.</p>
<p>These traditional theory-based methods have been used for decades mostly because researchers didn’t have access to computers that could run thousands of calculations quickly and efficiently. Now that computing power is much cheaper and more accessible, simulation-based methods are much more feasible. However, researchers in many fields continue to use theory-based methods. Hence, I make it a point to include an example here. As we’ll see in this section, any theory-based method is ultimately an approximation to the simulation-based method.</p>
<section id="regression-interp" class="level2 page-columns page-full" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="regression-interp"><span class="header-section-number">6.1</span> Interpreting regression tables</h2>
<p>Previously, when we interpreted a regression table, like the one shown in <a href="#tbl-regression" class="quarto-xref">Table&nbsp;4</a>, we focused entirely on the <code>term</code> and <code>estimate</code> columns. Let’s now shift our attention to the remaining columns: <code>std_error</code>, <code>statistic</code>, <code>p_value</code>, <code>lower_ci</code> and <code>upper_ci</code>.</p>
<div class="cell">
<div id="tbl-regression" class="cell quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-regression-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Regression table for estimated coefficients from regression on birth weight and mother’s age.
</figcaption>
<div aria-describedby="tbl-regression-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std_error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p_value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">lower_ci</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">upper_ci</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">intercept</td>
<td style="text-align: right;">6.793</td>
<td style="text-align: right;">0.208</td>
<td style="text-align: right;">32.651</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">6.385</td>
<td style="text-align: right;">7.201</td>
</tr>
<tr class="even">
<td style="text-align: left;">mage</td>
<td style="text-align: right;">0.014</td>
<td style="text-align: right;">0.007</td>
<td style="text-align: right;">1.987</td>
<td style="text-align: right;">0.047</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.028</td>
</tr>
</tbody>
</table>


</div>
</div>
</figure>
</div>
</div>
<p>R, the programming language has been around since roughly 1997, a period when computers were not able to run the simulations we can today. Thus, the calculations R provides in the <code>std_error</code>, <code>statistic</code>, <code>p_value</code>, <code>lower_ci</code> and <code>upper_ci</code> columns <strong>are not</strong> found using simulation-based methods. Rather, R uses a theory-based approach using mathematical formulas. These formulas were derived in a time when computers didn’t exist, so it would’ve been incredibly labor intensive to run extensive simulations.</p>
<section id="regression-se" class="level3" data-number="6.1.1">
<h3 data-number="6.1.1" class="anchored" data-anchor-id="regression-se"><span class="header-section-number">6.1.1</span> Standard error</h3>
<p>The third column of the regression table in <a href="#tbl-regression" class="quarto-xref">Table&nbsp;4</a>, <code>std_error</code>, corresponds to the <em>standard error</em> of our estimates. Recall the definition of <strong>standard error</strong> we saw last week:</p>
<blockquote class="blockquote">
<p>The <em>standard error</em> is the standard deviation of any point estimate computed from a sample.</p>
</blockquote>
<p>So what does this mean in terms of the fitted slope <span class="math inline">\(b_1\)</span> = 0.014? This value is just one possible value of the fitted slope resulting from <em>this particular sample</em> of <span class="math inline">\(n\)</span> = 1000 birth records. However, if we collected a different sample of <span class="math inline">\(n\)</span> = 1000 birth records, we will almost certainly obtain a different fitted slope <span class="math inline">\(b_1\)</span>. This is due to <em>sampling variability</em>.</p>
<p>Say we hypothetically collected 1000 such birth records, computed the 1000 resulting values of the fitted slope <span class="math inline">\(b_1\)</span>, and visualized them in a histogram. This would be a visualization of the <em>sampling distribution</em> of <span class="math inline">\(b_1\)</span>, which we defined last week. Further recall that the standard deviation of the <em>sampling distribution</em> of <span class="math inline">\(b_1\)</span> has a special name: the <em>standard error</em>.</p>
<p>Last week, we used the <code>infer</code> package to construct the bootstrap distribution for <span class="math inline">\(b_1\)</span> in this case. Recall that the bootstrap distribution is an <em>approximation</em> to the sampling distribution in that they have a similar shape. Since they have a similar shape, they have similar <em>standard errors</em>. However, unlike the sampling distribution, the bootstrap distribution is constructed from a <em>single</em> sample, which is a practice more aligned with what’s done in real life.</p>
<p>Rather than resampling from our original sample to create a bootstrap distribution, we could have instead used theory-based methods to estimated the standard error of the sampling distribution. In particular, there is a formula for the standard error of the fitted slope <span class="math inline">\(b_1\)</span>:</p>
<p><span class="math display">\[\text{SE}_{b_1} = \dfrac{\dfrac{s_y}{s_x} \cdot \sqrt{1-r^2}}{\sqrt{n-2}}\]</span></p>
<p>As with many formulas in statistics, there’s a lot going on here, so let’s first break down what each symbol represents. First <span class="math inline">\(s_x\)</span> and <span class="math inline">\(s_y\)</span> are the <em>sample standard deviations</em> of the explanatory variable <code>mage</code> and the response variable <code>weight</code>, respectively. Second, <span class="math inline">\(r\)</span> is the sample <em>correlation coefficient</em> between <code>mage</code> and <code>weight</code>. This was computed as 0.063. Lastly, <span class="math inline">\(n\)</span> is the number of pairs of points (birth weight, mother’s age) in the <code>births14</code> data frame, here 1000.</p>
<p>To put this formula into words, the standard error of <span class="math inline">\(b_1\)</span> depends on the relationship between the variability of the response variable and the variability of the explanatory variable as measured in the <span class="math inline">\(s_y / s_x\)</span> term. Next, it looks into how the two variables relate to each other in the <span class="math inline">\(\sqrt{1-r^2}\)</span> term.</p>
<p>However, the most important observation to make in the previous formula is that there is an <span class="math inline">\(n - 2\)</span> in the denominator. In other words, as the sample size <span class="math inline">\(n\)</span> increases, the standard error <span class="math inline">\(\text{SE}_{b_1}\)</span> decreases. Just as we demonstrated last week, when we increase our sample size the amount of sampling variation of the fitted slope <span class="math inline">\(b_1\)</span> will depend on the sample size <span class="math inline">\(n\)</span>. In particular, as the sample size increases, both the sampling and bootstrap distributions narrow and the standard error <span class="math inline">\(\text{SE}_{b_1}\)</span> decreases. Hence, our estimates of <span class="math inline">\(b_1\)</span> for the true population slope <span class="math inline">\(\beta_1\)</span> get more and more <em>precise</em>.</p>
</section>
<section id="regression-test-statistic" class="level3 page-columns page-full" data-number="6.1.2">
<h3 data-number="6.1.2" class="anchored" data-anchor-id="regression-test-statistic"><span class="header-section-number">6.1.2</span> Test statistic</h3>
<p>The fourth column of the regression table in <a href="#tbl-regression" class="quarto-xref">Table&nbsp;4</a>, <code>statistic</code>, corresponds to a <em>test statistic</em> relating to the following <em>hypothesis test</em>:</p>
<center>
<p><span class="math inline">\(H_0: \beta_1 = 0\)</span></p>
<p><span class="math inline">\(H_A: \beta_1 \neq 0\)</span></p>
</center>
<p>Here, our <em>null hypothesis</em> <span class="math inline">\(H_0\)</span> assumes that the population slope <span class="math inline">\(\beta_1\)</span> is 0. If the population slope <span class="math inline">\(\beta_1\)</span> is truly 0, then this is saying that there is <em>no relationship</em> between a baby’s birth weight and a mother’s age for <em>all</em> births in the US in 2014. In other words, <span class="math inline">\(x\)</span> = mother’s age would have no associated effect on <span class="math inline">\(y\)</span> = baby’s birth weight.</p>
<p>The <em>alternative hypothesis</em> <span class="math inline">\(H_A\)</span>, on the other hand, assumes that the population slope <span class="math inline">\(\beta_1\)</span> is not 0, meaning it could be either positive or negative. This suggests either a positive or negative relationship between a baby’s birth weight and a mother’s age. Recall we called such alternative hypotheses <em>two-sided</em>.</p>

<div class="no-row-height column-margin column-container"><div class="">
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Caution
</div>
</div>
<div class="callout-body-container callout-body">
<p>By convention, all hypothesis testing for regression assumes two-sided alternatives.</p>
</div>
</div>
</div></div><p>The <code>statistic</code> column in the regression table is a tricky one, however. It corresponds to a standardized <em>t-test statistic</em>. The <em>null distribution</em> can be mathematically proven to be a <span class="math inline">\(t\)</span>-distribution, under specific conditions (described in <a href="#sec-conditions" class="quarto-xref">Section&nbsp;7</a>). R uses the following <span class="math inline">\(t\)</span>-statistic as the test statistic for hypothesis testing:</p>
<p><span class="math display">\[
t = \dfrac{ b_1 - \beta_1}{ \text{SE}_{b_1}}
\]</span></p>
<p>And since the null hypothesis <span class="math inline">\(H_0: \beta_1 = 0\)</span> is assumed during the hypothesis test, the <span class="math inline">\(t\)</span>-statistic becomes</p>
<p><span class="math display">\[
t = \dfrac{ b_1 - 0}{ \text{SE}_{b_1}} = \dfrac{ b_1 }{ \text{SE}_{b_1}}
\]</span></p>
<p>What are the values of <span class="math inline">\(b_1\)</span> and <span class="math inline">\(\text{SE}_{b_1}\)</span>? They are in the <code>estimate</code> and <code>std_error</code> column of the regression table in <a href="#tbl-regression" class="quarto-xref">Table&nbsp;4</a>. Thus the value of 1.987 in the table is computed as 0.014 / 0.007 = 2. Note there is a difference due to some rounding error here.</p>
</section>
<section id="p-value" class="level3" data-number="6.1.3">
<h3 data-number="6.1.3" class="anchored" data-anchor-id="p-value"><span class="header-section-number">6.1.3</span> p-value</h3>
<p>The fifth column of the regression table in <a href="#tbl-regression" class="quarto-xref">Table&nbsp;4</a>, <code>p_value</code>, corresponds to the <em>p-value</em> of the hypothesis test <span class="math inline">\(H_0: \beta_1 = 0\)</span> versus <span class="math inline">\(H_A: \beta_1 \neq 0\)</span>.</p>
<p>Again recalling our terminology, notation, and definitions related to hypothesis tests we introduced in <a href="#sec-understanding-ht" class="quarto-xref">Section&nbsp;2</a>, let’s focus on the definition of the <span class="math inline">\(p\)</span>-value:</p>
<blockquote class="blockquote">
<p>A <em>p-value</em> is the probability of obtaining a test statistic just as extreme or more extreme than the observed test statistic <em>assuming the null hypothesis</em> <span class="math inline">\(H_0\)</span> is true.</p>
</blockquote>
<p>Recall that you can intuitively think of the <span class="math inline">\(p\)</span>-value as quantifying how “extreme” the observed fitted slope of <span class="math inline">\(b_1\)</span> = 0.014 is in a “hypothesized universe” where there is no relationship between a baby’s birth weight and a mother’s age.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>If you’re a bit rusty on the <span class="math inline">\(t\)</span>-distribution, <a href="https://www.jmp.com/en_us/statistics-knowledge-portal/t-test/t-distribution.html#:~:text=The%20shape%20of%20the%20t,more%20like%20a%20z%2Ddistribution">here</a> is an article describing how degrees of freedom relate to the shape of the <span class="math inline">\(t\)</span>-distribution.</p>
</div>
</div>
<p>More precisely, however, the <span class="math inline">\(p\)</span>-value corresponds to how extreme the observed test statistic of 0.014 is when compared to the appropriate <em>null distribution</em>. Recall from <a href="#sec-understanding-ht" class="quarto-xref">Section&nbsp;2</a>, that a null distribution is the sampling distribution of the test statistic <em>assuming the null hypothesis</em> <span class="math inline">\(H_0\)</span> is true. It can be mathematically proven that a <span class="math inline">\(t\)</span>-distribution with degrees of freedom equal to <span class="math inline">\(df = n - 2 = 1000 - 2 = 998\)</span> is a reasonable approximation to the null distribution, if certain conditions for inference are not violated. We will discuss these conditions shortly in <a href="#sec-conditions" class="quarto-xref">Section&nbsp;7</a>.</p>
</section>
<section id="confidence-interval" class="level3" data-number="6.1.4">
<h3 data-number="6.1.4" class="anchored" data-anchor-id="confidence-interval"><span class="header-section-number">6.1.4</span> Confidence interval</h3>
<p>The two rightmost columns of the regression table in <a href="#tbl-regression" class="quarto-xref">Table&nbsp;4</a>, <code>lower_ci</code> and <code>upper_ci</code>, correspond to the endpoints of the 95% <em>confidence interval</em> for the population slope <span class="math inline">\(\beta_1\)</span>. What are the calculations that went into computing the two endpoints of the 95% confidence interval for <span class="math inline">\(\beta_1\)</span>?</p>
<p>Recall from the SE method for constructing confidence intervals, for any distribution that resemble a Normal Distribution<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>, we could use the empiracle rule to create a 95% confidence interval:</p>
<center>
<span class="math inline">\(b_1 \pm SE_{b_1} \times\)</span> 1.96
</center>
<p><br></p>
<p>What is the value of the standard error <span class="math inline">\(SE_{b_1}\)</span>? It is in fact in the third column of the regression table in <a href="#tbl-regression" class="quarto-xref">Table&nbsp;4</a>: 0.007. Plugging in the respective values, we have:</p>
<center>
<p>0.014 <span class="math inline">\(\pm\)</span> 0.007 <span class="math inline">\(\times\)</span> 1.96</p>
<p>0.014 <span class="math inline">\(\pm\)</span> 0.01372</p>
<p>(0.00028, 0.02772)</p>
</center>
<p><br></p>
<p>This closely matches the <span class="math inline">\((0,0.028)\)</span> confidence interval in the last two columns of <a href="#tbl-regression" class="quarto-xref">Table&nbsp;4</a>, with slight differences due to rounding.</p>
<p>Much like p-values, the results of this confidence interval also are only valid if the conditions for inference are not violated.</p>
</section>
</section>
<section id="conclusion" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="conclusion"><span class="header-section-number">6.2</span> Conclusion</h2>
<p>Don’t worry if you’re feeling a little overwhelmed at this point. There is a lot of background theory to understand before you can fully make sense of the equations for theory-based methods. That being said, theory-based methods and simulation-based methods for constructing confidence intervals and conducting hypothesis tests often yield consistent results. As mentioned before, in my opinion, two large benefits of simulation-based methods over theory-based are that (1) they are easier for people new to statistical inference to understand, and (2) they also work in situations where theory-based methods and mathematical formulas don’t exist.</p>
</section>
<section id="everything-is-one-test" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="everything-is-one-test"><span class="header-section-number">6.3</span> Everything is one test</h2>
<p>While this is a lot to digest, especially the first time you encounter hypothesis testing, the nice thing is that once you understand this general framework, then you can understand <em>any</em> hypothesis test. In a famous blog post, computer scientist Allen Downey called this the <a href="http://allendowney.blogspot.com/2016/06/there-is-still-only-one-test.html">“There is only one test”</a> framework, for which he created the flowchart displayed in <a href="#fig-htdowney" class="quarto-xref">Figure&nbsp;13</a>.</p>
<div id="fig-htdowney" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-htdowney-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/there_is_only_one_test.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-htdowney-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13: Allen Downey’s hypothesis testing framework.
</figcaption>
</figure>
</div>
<p>Notice its similarity with the “hypothesis testing with <code>infer</code>” diagram you saw in <a href="#fig-infer-ht" class="quarto-xref">Figure&nbsp;6</a>. That’s because the <code>infer</code> package was explicitly designed to match the “There is only one test” framework. So if you can understand the framework, you can easily generalize these ideas for all hypothesis testing scenarios.</p>
</section>
</section>
<section id="sec-conditions" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Checking Model Conditions</h1>
<p>Recall last week how we stated that we could only use the standard-error-based method for constructing confidence intervals if the bootstrap distribution was bell shaped. Similarly, there are certain conditions that cannot be violated for the results of our hypothesis tests and confidence intervals to have meaning.</p>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Caution
</div>
</div>
<div class="callout-body-container callout-body">
<p>Notice how I’m saying the conditions cannot be viola ted and not that the conditions need to be met? To me, this language is very similar to the difference between failing to reject the null and accepting the null. Let’s pose these two options as hypotheses:</p>
<p><span class="math inline">\(H_0\)</span>: the conditions are met</p>
<p><span class="math inline">\(H_A\)</span>: the conditions are violated</p>
<p>If we have insufficient evidence to say that the conditions are violated, then that’s all we can say. We cannot say that the conditions are met, as that would be equivalent to saying that we’ve accepted our null hypothesis!</p>
</div>
</div>
<section id="conditions-for-regression" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="conditions-for-regression"><span class="header-section-number">7.1</span> Conditions for regression</h2>
<p>For inference for regression, there are four conditions that cannot be violated. Note the first four letters of these conditions are highlighted in bold in what follows: <strong>LINE</strong>. This can serve as a nice reminder of what to check for whenever you perform linear regression.</p>
<ol type="1">
<li><strong>L</strong>inearity of relationship between variables</li>
<li><strong>I</strong>ndependence of the residuals</li>
<li><strong>N</strong>ormality of the residuals</li>
<li><strong>E</strong>quality of variance of the residuals</li>
</ol>
<p>Conditions <strong>L</strong>, <strong>N</strong>, and <strong>E</strong> can be verified through what is known as a <em>residual analysis</em>. Condition <strong>I</strong> can only be verified through an understanding of how the data was collected.</p>
<section id="residuals-refresher" class="level3" data-number="7.1.1">
<h3 data-number="7.1.1" class="anchored" data-anchor-id="residuals-refresher"><span class="header-section-number">7.1.1</span> Residuals refresher</h3>
<p>Recall our definition of a residual: it is the <em>observed value</em> minus the <em>fitted value</em> denoted by <span class="math inline">\(y - \widehat{y}\)</span>. Recall that residuals can be thought of as the error or the “lack-of-fit” between the observed value <span class="math inline">\(y\)</span> and the fitted value <span class="math inline">\(\widehat{y}\)</span> on the regression line in <a href="#fig-births-slr" class="quarto-xref">Figure&nbsp;1</a>. In <a href="#fig-residual-example" class="quarto-xref">Figure&nbsp;14</a>, we illustrate one particular residual out of 1000 using an arrow, as well as its corresponding observed and fitted values using a circle and a square, respectively.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-residual-example" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-residual-example-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="week8-reading_files/figure-html/fig-residual-example-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-residual-example-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14: Example of observed value, fitted value, and residual.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Furthermore, we can automate the calculation of all <span class="math inline">\(n\)</span> = 1000 residuals by applying the <code>get_regression_points()</code> function to our saved regression model in <code>births_lm</code>. Observe how the resulting values of <code>residual</code> are roughly equal to <code>mage - mage_hat</code> (there is potentially a slight difference due to rounding error).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit regression model:</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>births_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(weight <span class="sc">~</span> mage, <span class="at">data =</span> births14)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Get regression points:</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>regression_points <span class="ot">&lt;-</span> <span class="fu">get_regression_points</span>(births_lm)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>regression_points</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,000 × 5
      ID weight  mage weight_hat residual
   &lt;int&gt;  &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;    &lt;dbl&gt;
 1     1   6.96    34       7.28   -0.317
 2     2   8.86    31       7.23    1.63 
 3     3   7.51    36       7.31    0.204
 4     4   6.19    16       7.02   -0.831
 5     5   6.75    31       7.23   -0.484
 6     6   6.69    26       7.16   -0.473
 7     7   6.13    36       7.31   -1.18 
 8     8   6.74    24       7.14   -0.395
 9     9   8.94    32       7.25    1.69 
10    10   9.12    26       7.16    1.96 
# ℹ 990 more rows</code></pre>
</div>
</div>
<p>A <em>residual analysis</em> is used to verify conditions <strong>L</strong>, <strong>N</strong>, and <strong>E</strong> and can be performed using appropriate data visualizations. While there are more sophisticated statistical approaches that can also be done, we’ll focus on the much simpler approach of looking at plots.</p>
</section>
<section id="linearity-of-relationship" class="level3" data-number="7.1.2">
<h3 data-number="7.1.2" class="anchored" data-anchor-id="linearity-of-relationship"><span class="header-section-number">7.1.2</span> Linearity of relationship</h3>
<p>The first condition is that the relationship between the outcome variable <span class="math inline">\(y\)</span> and the explanatory variable <span class="math inline">\(x\)</span> must be <strong>L</strong>inear. Recall the scatterplot in <a href="#fig-births-slr" class="quarto-xref">Figure&nbsp;1</a> where we had the explanatory variable <span class="math inline">\(x\)</span> as mother’s age and the outcome variable <span class="math inline">\(y\)</span> as baby’s birth weight. Would you say that the relationship between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> is linear? It’s hard to say because of the scatter of the points about the line. In my opinion, this relationship is “linear enough.”</p>
<p>Let’s present an example where the relationship between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> is clearly not linear in <a href="#fig-non-linear" class="quarto-xref">Figure&nbsp;15</a>. In this case, the points clearly follow a curved relationship, more closely resembling a <a href="https://www.rapidtables.com/math/algebra/logarithm/logarithm-graph.html">logarithmic scale</a>. In this case, any results from an inference for regression would not be valid.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-non-linear" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-non-linear-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="week8-reading_files/figure-html/fig-non-linear-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-non-linear-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;15: Example of a clearly non-linear relationship.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="independence-of-residuals" class="level3" data-number="7.1.3">
<h3 data-number="7.1.3" class="anchored" data-anchor-id="independence-of-residuals"><span class="header-section-number">7.1.3</span> Independence of residuals</h3>
<p>The second condition is that the residuals must be <strong>I</strong>ndependent. In other words, the different observations in our data must be independent of one another.</p>
<p>For the <code>evals</code> dataset, while there is data on 463 courses, these 463 courses were actually taught by 94 unique instructors. In other words, the same professor is often included more than once in our data. For a professor in the <code>evals</code> data who taught multiple classes, it seems reasonable to expect that their teaching scores will be related to each other. If a professor gets a high <code>score</code> in one class, chances are fairly good they’ll get a high <code>score</code> in another. This dataset thus provides different information than if we had 463 unique instructors teaching the 463 courses.</p>
<p>In this case, we say there exists <em>dependence</em> between observations. So in this case, the independence condition is violated. The most appropriate analysis would take into account that we have <em>repeated measures</em> for the same profs, but that is beyond the scope of this class. What we could do, however, is devise a method to collapse the multiple observations for each professor into <strong>one</strong> observation. This could be done a variety of ways:</p>
<ul>
<li>randomly selecting one observation per professor</li>
<li>taking the mean of their scores<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></li>
<li>selecting the maximum / minimum / median value</li>
</ul>
</section>
<section id="normality-of-residuals" class="level3" data-number="7.1.4">
<h3 data-number="7.1.4" class="anchored" data-anchor-id="normality-of-residuals"><span class="header-section-number">7.1.4</span> Normality of residuals</h3>
<p>The third condition is that the residuals should follow a <strong>N</strong>ormal distribution. Furthermore, the center of this distribution should be 0. In other words, sometimes the regression model will make positive errors: <span class="math inline">\(y - \widehat{y} &gt; 0\)</span>. Other times, the regression model will make equally negative errors: <span class="math inline">\(y - \widehat{y} &lt; 0\)</span>. However, <em>on average</em> the errors should equal 0 and their shape should be similar to that of a bell.</p>
<p>The simplest way to check the normality of the residuals is to look at a histogram, which we visualize in <a href="#fig-model1residualshist" class="quarto-xref">Figure&nbsp;16</a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>regression_points <span class="ot">&lt;-</span> <span class="fu">get_regression_points</span>(births_lm)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> regression_points, </span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> residual)) <span class="sc">+</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="fl">0.25</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Residual"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-model1residualshist" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-model1residualshist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="week8-reading_files/figure-html/fig-model1residualshist-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-model1residualshist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;16: Histogram of residuals from regression model for baby birth weight as predicted by mother’s age.
</figcaption>
</figure>
</div>
</div>
</div>
<p>This histogram shows that we have more negative residuals than negative. Since the residual <span class="math inline">\(y-\widehat{y}\)</span> is negative when <span class="math inline">\(y &lt; \widehat{y}\)</span>, it seems our regression model’s fitted baby birth weights (<span class="math inline">\(\widehat{y}\)</span>) tend to <em>overestimate</em> the birth weight <span class="math inline">\(y\)</span>. Furthermore, this histogram has a <em>left-skew</em> in that there is a longer tail on the left. This is another way to say the residuals exhibit a <em>negative skew</em>.</p>
<p>Is this a problem? Again, there is a certain amount of subjectivity in the response. In my opinion, while there is a slight skew to the residuals, I don’t believe it is so bad that I would say this condition is violated. On the other hand, others might disagree with our assessment.</p>
<p>Let’s present examples where the residuals clearly do and don’t follow a normal distribution in <a href="#fig-normal-residuals" class="quarto-xref">Figure&nbsp;17</a>. In this case of the model yielding the clearly non-normal residuals on the right, any results from an inference for regression would not be valid.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-normal-residuals" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-normal-residuals-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="week8-reading_files/figure-html/fig-normal-residuals-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-normal-residuals-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;17: Example of clearly normal and clearly not normal residuals.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="equality-of-variance" class="level3" data-number="7.1.5">
<h3 data-number="7.1.5" class="anchored" data-anchor-id="equality-of-variance"><span class="header-section-number">7.1.5</span> Equality of variance</h3>
<p>The fourth and final condition is that the residuals should exhibit <strong>E</strong>qual variance across all values of the explanatory variable <span class="math inline">\(x\)</span>. In other words, the value and spread of the residuals should not depend on the value of the explanatory variable <span class="math inline">\(x\)</span>.</p>
<p>Recall the scatterplot in <a href="#fig-births-slr" class="quarto-xref">Figure&nbsp;1</a>: we had the explanatory variable <span class="math inline">\(x\)</span> of mother’s age on the x-axis and the outcome variable <span class="math inline">\(y\)</span> of baby’s birth weight on the y-axis. Instead, let’s create a scatterplot that has the same values on the x-axis, but now with the residual <span class="math inline">\(y-\widehat{y}\)</span> on the y-axis as seen in <a href="#fig-equal-var" class="quarto-xref">Figure&nbsp;18</a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> regression_points, </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> mage, <span class="at">y =</span> residual)) <span class="sc">+</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Mother's Age"</span>, <span class="at">y =</span> <span class="st">"Residual"</span>) <span class="sc">+</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">size =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-equal-var" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-equal-var-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="week8-reading_files/figure-html/fig-equal-var-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-equal-var-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;18: Plot of residuals over mother’s age.
</figcaption>
</figure>
</div>
</div>
</div>
<p>You can think of <a href="#fig-equal-var" class="quarto-xref">Figure&nbsp;18</a> a modified version of the plot with the regression line in <a href="#fig-births-slr" class="quarto-xref">Figure&nbsp;1</a>, but with the regression line flattened out to <span class="math inline">\(y=0\)</span>. Looking at this plot, would you say that the spread of the residuals around the line at <span class="math inline">\(y=0\)</span> is constant across all values of the explanatory variable <span class="math inline">\(x\)</span> of mother’s age? This question is rather qualitative and subjective in nature, thus different people may respond with different answers. For example, some people might say that there is slightly more variation in the residuals for ages between 20 and 40 than for ages below 20 and above 40. However, it can be argued that there isn’t a <em>drastic</em> non-constancy. Moreover, this could be an artifact of having smaller numbers of younger / older mothers in the sample.</p>
<p>In <a href="#fig-non-equal-variance-residuals" class="quarto-xref">Figure&nbsp;19</a> I present an example where the residuals clearly do not have equal variance across all values of the explanatory variable <span class="math inline">\(x\)</span>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-non-equal-variance-residuals" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-non-equal-variance-residuals-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="week8-reading_files/figure-html/fig-non-equal-variance-residuals-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-non-equal-variance-residuals-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;19: Example of clearly non-equal variance.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Observe how the spread of the residuals increases as the value of <span class="math inline">\(x\)</span> increases. This is a situation known as <em>heteroskedasticity</em>. Any inference for regression based on a model yielding such a pattern in the residuals would not be valid.</p>
</section>
<section id="what-is-the-conclusion" class="level3" data-number="7.1.6">
<h3 data-number="7.1.6" class="anchored" data-anchor-id="what-is-the-conclusion"><span class="header-section-number">7.1.6</span> What’s the conclusion?</h3>
<p>Let’s list our four conditions for inference for regression again and indicate whether or not they were violated in our analysis:</p>
<ol type="1">
<li><strong>L</strong>inearity of relationship between variables: No</li>
<li><strong>I</strong>ndependence of residuals: No</li>
<li><strong>N</strong>ormality of residuals: Slight left-skew, but not too concerning</li>
<li><strong>E</strong>quality of variance: No</li>
</ol>
<p>So what does this mean for the results of our confidence intervals and hypothesis tests in <a href="#sec-ht-interpretation" class="quarto-xref">Section&nbsp;4</a>? Since none of the conditions were viola ted, we can have faith in the confidence intervals and <span class="math inline">\(p\)</span>-values calculated before. If, however, any of these conditions were violated, we would need to pause and reconsider our model.</p>
<p>When the <strong>I</strong>ndependence condition is violated, there exist dependencies between the observations in the dataset. To remedy this, you will need to use a statistical model which accounts for this dependency structure. One such technique is called hierarchical/multilevel modeling, which you may learn about in more advanced statistics courses.</p>
<p>When conditions <strong>L</strong>, <strong>N</strong>, <strong>E</strong> are violated, it often means there is a shortcoming in our model. For example, it may be the case that using only a single explanatory variable is insufficient. We may need to incorporate more explanatory variables in a multiple regression model as we did in previously, or perhaps use a transformation of one or more of your variables, or use an entirely different modeling technique. To learn more about addressing such shortcomings, you’ll have to take a class on or read up on more advanced regression modeling methods.</p>
<p>The conditions for inference in regression problems are a key part of regression analysis that are of vital importance to the processes of constructing confidence intervals and conducting hypothesis tests. However, it is often the case with regression analysis in the real world that some of these conditions may be violated. Furthermore, as you saw, there is a level of subjectivity in the residual analyses to verify the <strong>L</strong>, <strong>N</strong>, and <strong>E</strong> conditions. So what can you do? As a statistics educator, I advocate for transparency in communicating all results. This lets the stakeholders of any analysis know about a model’s shortcomings or whether the model is “good enough.” So while this checking of assumptions has lead to some fuzzy “it depends” results, we decided as authors to show you these scenarios to help prepare you for difficult statistical decisions you may need to make down the road.</p>
</section>
</section>
</section>
<section id="references" class="level1" data-number="8">




</section>


<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">8 References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-ims" class="csl-entry" role="listitem">
Çetinkaya-Rundel, Mine, and Jo Hardin. 2023. <em>Introduction to Modern Statistics</em>. OpenIntro. <a href="https://openintro-ims.netlify.app/">https://openintro-ims.netlify.app/</a>.
</div>
<div id="ref-kim2020" class="csl-entry" role="listitem">
Kim, Albert Y., Chester Ismay, Starry Zhou, Marium Tapal, Dorothy Bishop, WatanabeSmith, Tobias Rockel, et al. 2020. <em>Moderndive/ModernDive<span>_</span>book: Cleaned Bookdown Code, Typo Fixes, New Tips &amp; Tricks Page</em>. Zenodo. <a href="https://doi.org/10.5281/ZENODO.3932023">https://doi.org/10.5281/ZENODO.3932023</a>.
</div>
</div></section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>I prefer to use the term meaningful.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>meaning they are bell shaped and symmetric<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Taking the mean of observations assumes they are inherently similar, so we shouldn’t calculate the mean of evaluation scores that are very different!<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© Copyright 2023, Allison Theobold</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/atheobold/stat-313-website/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>This page is built with ❤️ and <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>




</body></html>