<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.549">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>STAT 313 / 513 - Week 7 – Confidence Intervals for the Slope</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">Week 7 – Confidence Intervals for the Slope</li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
      <a href="../../index.html" class="sidebar-logo-link">
      <img src="../../images/cp-stat-hex.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
      <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/atheobold/stat-313-website" title="GitHub organization" class="quarto-navigation-tool px-1" aria-label="GitHub organization"><i class="bi bi-github"></i></a>
    <a href="https://posit.cloud/" title="" class="quarto-navigation-tool px-1" aria-label="RStudio Cloud"><i class="bi bi-cloud-fill"></i></a>
    <a href="https://canvas.calpoly.edu" title="Cal Poly Canvas" class="quarto-navigation-tool px-1" aria-label="Cal Poly Canvas"><i class="bi bi-person-fill"></i></a>
</div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false">
 <span class="menu-text">Course information</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../course-overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Overview</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../course-syllabus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Syllabus</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../course-support.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Support</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../course-team.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Teaching team</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Schedule</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false">
 <span class="menu-text">Computing</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../computing-access.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Access</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false">
 <span class="menu-text">R Resources</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../course_resources.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">R Resources</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="false">
 <span class="menu-text">Projects</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../project/midterm-project-directions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Midterm Project Description</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../project/final-project-directions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Final Project Description</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="false">
 <span class="menu-text">Weekly materials</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../weeks/week-0.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 0</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../weeks/week-1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../weeks/week-2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../weeks/week-3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 3</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../weeks/week-4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 4</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../weeks/week-5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 5</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../weeks/week-6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 6</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../weeks/week-7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 7</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../weeks/week-8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 8</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../weeks/week-9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 9</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../weeks/week-10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 10</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#sampling-review" id="toc-sampling-review" class="nav-link active" data-scroll-target="#sampling-review"><span class="header-section-number">0.1</span> Sampling Review</a></li>
  <li><a href="#baby-birth-weights" id="toc-baby-birth-weights" class="nav-link" data-scroll-target="#baby-birth-weights"><span class="header-section-number">1</span> Baby Birth Weights</a>
  <ul class="collapse">
  <li><a href="#observed-data" id="toc-observed-data" class="nav-link" data-scroll-target="#observed-data"><span class="header-section-number">1.1</span> Observed data</a></li>
  <li><a href="#variability-of-the-statistic" id="toc-variability-of-the-statistic" class="nav-link" data-scroll-target="#variability-of-the-statistic"><span class="header-section-number">1.2</span> Variability of the statistic</a></li>
  <li><a href="#resampling-once" id="toc-resampling-once" class="nav-link" data-scroll-target="#resampling-once"><span class="header-section-number">1.3</span> Resampling once</a></li>
  </ul></li>
  <li><a href="#computer-simulation-and-resampling" id="toc-computer-simulation-and-resampling" class="nav-link" data-scroll-target="#computer-simulation-and-resampling"><span class="header-section-number">2</span> Computer simulation and resampling</a>
  <ul class="collapse">
  <li><a href="#virtually-resampling-once" id="toc-virtually-resampling-once" class="nav-link" data-scroll-target="#virtually-resampling-once"><span class="header-section-number">2.1</span> Virtually resampling once</a></li>
  <li><a href="#infer-package-workflow" id="toc-infer-package-workflow" class="nav-link" data-scroll-target="#infer-package-workflow"><span class="header-section-number">2.2</span> <strong>infer</strong> package workflow</a></li>
  <li><a href="#virtually-resampling-1000-times" id="toc-virtually-resampling-1000-times" class="nav-link" data-scroll-target="#virtually-resampling-1000-times"><span class="header-section-number">2.3</span> Virtually resampling 1,000 times</a></li>
  <li><a href="#connection-to-sampling-distributions" id="toc-connection-to-sampling-distributions" class="nav-link" data-scroll-target="#connection-to-sampling-distributions"><span class="header-section-number">2.4</span> Connection to sampling distributions</a></li>
  </ul></li>
  <li><a href="#sec-understanding" id="toc-sec-understanding" class="nav-link" data-scroll-target="#sec-understanding"><span class="header-section-number">3</span> Understanding confidence intervals</a>
  <ul class="collapse">
  <li><a href="#sec-percentile-method" id="toc-sec-percentile-method" class="nav-link" data-scroll-target="#sec-percentile-method"><span class="header-section-number">3.1</span> Percentile method</a></li>
  <li><a href="#sec-se-method" id="toc-sec-se-method" class="nav-link" data-scroll-target="#sec-se-method"><span class="header-section-number">3.2</span> Standard error method</a></li>
  </ul></li>
  <li><a href="#constructing-confidence-intervals" id="toc-constructing-confidence-intervals" class="nav-link" data-scroll-target="#constructing-confidence-intervals"><span class="header-section-number">4</span> Constructing confidence intervals</a></li>
  <li><a href="#interpreting-confidence-intervals" id="toc-interpreting-confidence-intervals" class="nav-link" data-scroll-target="#interpreting-confidence-intervals"><span class="header-section-number">5</span> Interpreting confidence intervals</a>
  <ul class="collapse">
  <li><a href="#did-our-intervals-capture-beta_1" id="toc-did-our-intervals-capture-beta_1" class="nav-link" data-scroll-target="#did-our-intervals-capture-beta_1"><span class="header-section-number">5.1</span> Did our interval(s) capture <span class="math inline">\(\beta_1\)</span>?</a></li>
  <li><a href="#constructing-more-intervals" id="toc-constructing-more-intervals" class="nav-link" data-scroll-target="#constructing-more-intervals"><span class="header-section-number">5.2</span> Constructing more intervals</a></li>
  <li><a href="#connection-to-the-empiracle-rule" id="toc-connection-to-the-empiracle-rule" class="nav-link" data-scroll-target="#connection-to-the-empiracle-rule"><span class="header-section-number">5.3</span> Connection to the empiracle rule</a></li>
  <li><a href="#precise-and-shorthand-interpretation" id="toc-precise-and-shorthand-interpretation" class="nav-link" data-scroll-target="#precise-and-shorthand-interpretation"><span class="header-section-number">5.4</span> Precise and shorthand interpretation</a></li>
  <li><a href="#ci-width" id="toc-ci-width" class="nav-link" data-scroll-target="#ci-width"><span class="header-section-number">5.5</span> Width of confidence intervals</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/atheobold/stat-313-website/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Week 7 – Confidence Intervals for the Slope</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>This week’s reading is a compilation of <a href="https://moderndive.com/8-confidence-intervals.html">Chapter 8</a> from <em>ModernDive</em> <span class="citation" data-cites="kim2020">(<a href="#ref-kim2020" role="doc-biblioref">Kim et al. 2020</a>)</span>, <a href="openintro-ims.netlify.app/inf-model-slr.html">Chapter 24</a> from <em>Introduction to Modern Statistics</em> <span class="citation" data-cites="ims">(<a href="#ref-ims" role="doc-biblioref">Çetinkaya-Rundel and Hardin 2023</a>)</span>, with a smattering of my own ideas.</p>
<section id="sampling-review" class="level3" data-number="0.1">
<h3 data-number="0.1" class="anchored" data-anchor-id="sampling-review"><span class="header-section-number">0.1</span> Sampling Review</h3>
<p>In the last reading, we studied the concept of sampling variation. Using the example of estimating the proportion of red balls in a bowl, we started with a “tactile” exercise where a shovel was used to draw a sample of balls from the bowl. While we could have performed an exhaustive count of <strong>all</strong> the balls in the bowl, this would have been a tedious process. So instead, we used a shovel to extract a sample of balls and used the resulting proportion that were red as an <em>estimate</em>. Furthermore, we made sure to mix the bowl’s contents before every use of the shovel. Because of the randomness created by the mixing, different uses of the shovel yielded different proportions red and hence different estimates of the proportion of the bowl’s balls that are red.</p>
<p>We then used R to mimic this “tactile” sampling process. Using our computer’s random number generator, we were able to quickly mimic the tactile sampling procedure a large number of times. Moreover, we were able to explore how different our results would be if we used different sized shovels, with 25, 50, and 100 slots. When we visualized the results of these three different shovel sizes, we saw that as the sample size increased, the variation in the estimates (<span class="math inline">\(\widehat{p}\)</span>) decreased.</p>
<p>These visualizations of the repeated sampling from the bowl have a special name in Statistics – a <em>sampling distribution</em>. These distributions all us to study how our estimates ($) varied from one sample to another; in other words, we wanted to study the effect of <em>sampling variation</em>. Once we had over 1,000 different estimates, we quantified the variation of these estimates using their standard deviation, which also has a special name in Statistics – the <em>standard error</em>. Visually we saw the spread of the sampling distributions get narrower as the sample size increased, which was reiterated by the standard errors – the standard errors decreased as the sample size increased. This decrease in spread of the sampling distribution gives us more <em>precise</em> estimates that varied less around the center.</p>
<p>We then tied these sampling concepts to the statistical terminology and mathematical notation related to sampling. Our <em>study population</em> was the large bowl with <span class="math inline">\(N\)</span> = 2400 balls, while the <em>population parameter</em>, the unknown quantity of interest, was the population proportion <span class="math inline">\(p\)</span> of the bowl’s balls that were red. Since performing a <em>census</em> would be expensive in terms of time and energy, we instead extracted a <em>sample</em> of size <span class="math inline">\(n\)</span> = 50. The <em>point estimate</em>, also known as a <em>sample statistic</em>, used to estimate <span class="math inline">\(p\)</span> was the sample proportion <span class="math inline">\(\widehat{p}\)</span> of these 50 sampled balls that were red. Furthermore, since the sample was obtained at <em>random</em>, it can be considered as <em>unbiased</em> and <em>representative</em> of the population. Thus any results based on the sample could be <em>generalized</em> to the population. Therefore, the proportion of the shovel’s balls that were red was a “good guess” of the proportion of the bowl’s balls that are red. In other words, we used the sample to <em>infer</em> about the population.</p>
<p>However, we acknowledged that both the tactile and virtual sampling exercises are not what one would do in real life; this was merely an activity used to study the effects of sampling variation. In a real-life situation, we would not take 1,000s of samples of size <span class="math inline">\(n\)</span>, but rather take a <em>single</em> representative sample that’s as large as possible. Additionally, we knew that the true proportion of the bowl’s balls that were red was 37.5%. In a real-life situation, we will not know what this value is. Because if we did, then why would we take a sample to estimate it?</p>
<p>So how does one quantify the effects of sampling variation when you only have a <em>single sample</em> to work with? You cannot directly study the effects of sampling variation when you only have one sample. One common method to study this is <em>bootstrapping resampling</em>, which will be the focus of the earlier sections of this reading.</p>
<p>Furthermore, what if we would like not only a single estimate of the unknown population parameter, but also a <em>range of highly plausible</em> values? For example, when you read about political polls, they tell you the percent of all Californians who support a specific measure, but in addition to this estimate they provide the poll’s “margin of error”. This margin of error can be used to construct a range of plausible values for the true percentage of people who support a specific measure. This range of plausible values is what’s known as a <em>confidence interval</em>, which will be the focus of the later sections of this reading.</p>
</section>
<section id="baby-birth-weights" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="baby-birth-weights"><span class="header-section-number">1</span> Baby Birth Weights</h2>
<p>Medical researchers may be interested in the relationship between a baby’s birth weight and the age of the mother, so as to provide medical interventions for specific age groups if it is found that they are associated with lower birth weights.</p>
<p>Every year, the US releases to the public a large data set containing information on births recorded in the country. The <a href="http://openintrostat.github.io/openintro/reference/births14.html"><code>births14</code></a> dataset is a random sample of 1,000 cases from one such dataset released in 2014.</p>
<section id="observed-data" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="observed-data"><span class="header-section-number">1.1</span> Observed data</h3>
<p><a href="#fig-births-slr" class="quarto-xref">Figure&nbsp;1</a> visualizes the relationship between <code>mage</code> and <code>weight</code> for this sample of 1,000 birth records.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> births14, </span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> mage, <span class="at">y =</span> weight)) <span class="sc">+</span> </span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>) <span class="sc">+</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Mother's Age"</span>, </span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Birth Weight of Baby (lbs)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-births-slr" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-births-slr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="week7-reading2_files/figure-html/fig-births-slr-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-births-slr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Weight of baby at birth (in lbs) as explained by mother’s age.
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#tbl-births-slr" class="quarto-xref">Table&nbsp;1</a> displays the estimated regression coefficients for modeling the relationship between <code>mage</code> and <code>weight</code> for this sample of 1,000 birth records.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>births_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(weight <span class="sc">~</span> mage, <span class="at">data =</span> births14)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">get_regression_table</span>(births_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div id="tbl-births-slr" class="cell quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-births-slr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: The least squares estimates of the intercept and slope for modeling the relationship between baby’s birth weight and mother’s age.
</figcaption>
<div aria-describedby="tbl-births-slr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std_error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p_value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">lower_ci</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">upper_ci</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">intercept</td>
<td style="text-align: right;">6.793</td>
<td style="text-align: right;">0.208</td>
<td style="text-align: right;">32.651</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">6.385</td>
<td style="text-align: right;">7.201</td>
</tr>
<tr class="even">
<td style="text-align: left;">mage</td>
<td style="text-align: right;">0.014</td>
<td style="text-align: right;">0.007</td>
<td style="text-align: right;">1.987</td>
<td style="text-align: right;">0.047</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.028</td>
</tr>
</tbody>
</table>


</div>
</div>
</figure>
</div>
</div>
<p>Based on these coefficients, the estimated regression equation is:</p>
<p><span class="math display">\[ \widehat{\text{birth weight}} = -6.793 + 0.014 \times \text{mother's age}\]</span></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>We will let <span class="math inline">\(\beta_1\)</span> represent the slope of the relationship between baby’s birth weight and mother’s age for <strong>every</strong> baby born in the US in 2014. We will estimate <span class="math inline">\(\beta_1\)</span> using the <code>births14</code> dataset, labeling the estimate <span class="math inline">\(b_1\)</span> (just as we did in Week 4).</p>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Caution
</div>
</div>
<div class="callout-body-container callout-body">
<p>A <strong>parameter</strong> is the value of the statistic of interest for the entire <strong>population</strong>.</p>
<p>We typically estimate the parameter using a “point estimate” from a sample of data. The point estimate is also referred to as the <strong>statistic</strong>.</p>
</div>
</div>
</section>
<section id="variability-of-the-statistic" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="variability-of-the-statistic"><span class="header-section-number">1.2</span> Variability of the statistic</h3>
<p>This sample of 1,000 births is only one of possibly tens of thousands of possible samples that could have been taken from the large dataset released in 2014. So, then we might wonder how different our regression equation would be if we had a different sample. There is no reason to believe that <span class="math inline">\(\beta_1\)</span> is 0.279, but there is also no reason to believe that <span class="math inline">\(\beta_1\)</span> is particularly far away from <span class="math inline">\(b_1 =\)</span> 0.279.</p>
<p>Just this week you read about how estimates, such as <span class="math inline">\(b_1\)</span>, are prone to sampling variation – the variability from sample to sample. For example, if we took a different sample of 1,000 births, would we obtain a slope of exactly 0.279? No, that seems fairly unlikely. We might obtain a slope of 0.29 or 0.26, or even 0.35!</p>
<p>When we studied the effects of sampling variation, we took many samples, something that was easily done with a shovel and a bowl of red and white balls. In this case, however, how would we obtain another sample? Well, we would need to go to the source of the data—the large public dataset released in 2014—and take another random sample of 1,000 observations. Maybe we don’t have access to that original dataset of 2014 births, how could we study the effects of sampling variation using our single sample? We will do so using a technique known as <strong>bootstrap resampling with replacement</strong>, which we now illustrate.</p>
</section>
<section id="resampling-once" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="resampling-once"><span class="header-section-number">1.3</span> Resampling once</h3>
<div id="fig-baby-post-it" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-baby-post-it-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/baby-postit.jpg" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-baby-post-it-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Step 1: Write out mother’s ages and baby’s birth weights on 1,000 slips of paper representing one of the 1,000 births included in the original sample.
</figcaption>
</figure>
</div>
<p><strong>Step 1</strong>: Print out 1,000 identically sized slips of paper (or post-it notes) representing the sample of 1,000 babies in our sample. On each piece of paper, write the mother’s age and the birth weight of the baby. <a href="#fig-baby-post-it" class="quarto-xref">Figure&nbsp;2</a> displays six of these such papers.</p>
<p><strong>Step 2</strong>: Put the 1,000 slips of paper into a hat as seen in <a href="#fig-hat" class="quarto-xref">Figure&nbsp;3</a>.</p>
<div id="fig-hat" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-hat-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/hat.JPG" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-hat-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Step 2: Putting 1,000 slips of paper (post-its) in a hat.
</figcaption>
</figure>
</div>
<p><strong>Step 3</strong>: Mix the hat’s contents and draw one slip of paper at random, as seen in <a href="#fig-draw-out" class="quarto-xref">Figure&nbsp;4</a>. Record the mother’s age and baby’s birth weight, as printed on the paper.</p>
<div id="fig-draw-out" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-draw-out-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/draw-out2.jpg" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-draw-out-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Step 3: Drawing one slip of paper at random.
</figcaption>
</figure>
</div>
<p><strong>Step 4</strong>: Put the slip of paper back in the hat! In other words, replace it as seen in <a href="#fig-put-back" class="quarto-xref">Figure&nbsp;5</a>.</p>
<div id="fig-put-back" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-put-back-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/put-back.jpg" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-put-back-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Step 4: Replacing slip of paper.
</figcaption>
</figure>
</div>
<p><strong>Step 5</strong>: Repeat Steps 3 and 4 a total of 999 more times, resulting in 1,000 recorded mother’s ages and baby birth weights.</p>
<p>What we just performed was a <em>resampling</em> of the original sample of 1,000 birth records. We <strong>are not</strong> sampling 1,000 birth records from the population of all 2014 US births as we did for our original sample. Instead, we are mimicking this process by resampling 1,000 birth records from our original sample.</p>
<p>Now ask yourselves, why did we replace our resampled slip of paper back into the hat in Step 4? Because if we left the slip of paper out of the hat each time we performed Step 4, we would end up with the <strong>same</strong> 1,000 birth records! In other words, replacing the slips of paper induces <em>sampling variation</em>.</p>
<p>Being more precise with our terminology, we just performed a <em>resampling with replacement</em> from the original sample of 1,000 birth records. Had we left the slip of paper out of the hat each time we performed Step 4, this would be <em>resampling without replacement</em>.</p>
<p>Let’s study our sample of 1,000 resampled birth records. First, I’ve made a table of the number of times each observation (birth record) was resampled. <a href="#tbl-resample-id" class="quarto-xref">Table&nbsp;2</a> displays the birth records that were resampled the most often. Based on the table, it appears that record IDs 71 and 534 were resampled six times.</p>
<div class="cell">
<div id="tbl-resample-id" class="cell quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-resample-id-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Frequencies of how often a given birth record (ID) was resampled.
</figcaption>
<div aria-describedby="tbl-resample-id-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">71</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">534</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">170</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">561</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">19</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">142</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">305</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">309</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">495</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">573</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">726</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">727</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">835</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">838</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">840</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">864</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">919</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">924</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">929</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">953</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">6</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
</tr>
</tbody>
</table>


</div>
</div>
</figure>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Remember
</div>
</div>
<div class="callout-body-container callout-body">
<p>When sampling with replacement, not every observation is guaranteed to be sampled. So, some observations from the original sample may never appear in the resample, whereas others may appear multiple times.</p>
</div>
</div>
<p><a href="#fig-compare-dist" class="quarto-xref">Figure&nbsp;6</a> compares the relationship between mother’s age and baby’s birth weight from our resample with the relationship in our original sample.</p>
<div class="cell" data-layout-nrow="1">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> births14, </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> mage, <span class="at">y =</span> weight)) <span class="sc">+</span> </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>) <span class="sc">+</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Mother's Age"</span>, </span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Birth Weight (lbs)"</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> resample1, </span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> mage, <span class="at">y =</span> weight)) <span class="sc">+</span> </span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>) <span class="sc">+</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Mother's Age"</span>, </span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Birth Weight (lbs)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="fig-compare-dist" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-compare-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-compare-dist" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-compare-dist-1" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-compare-dist-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="week7-reading2_files/figure-html/fig-compare-dist-1.png" class="img-fluid figure-img" data-ref-parent="fig-compare-dist" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-compare-dist-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Original Sample of 1,000 Birth Records
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-compare-dist" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-compare-dist-2" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-compare-dist-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="week7-reading2_files/figure-html/fig-compare-dist-2.png" class="img-fluid figure-img" data-ref-parent="fig-compare-dist" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-compare-dist-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Resample of 1,000 Birth Records
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-compare-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Comparing relationship between <code>mage</code> and <code>weight</code> in the resampled birth records compared to the relationship seen in the original sample of birth records.
</figcaption>
</figure>
</div>
</div>
<p>Observed in <a href="#fig-compare-dist" class="quarto-xref">Figure&nbsp;6</a> that while the general shape of both relationships are similar, they are not identical.</p>
<p>Recall, from the previous section that the sample slope (<span class="math inline">\(b_1\)</span>) from the original sample was . What about for our resample? Based on the scatterplot, what would your guess be? Larger than before? Smaller than before?</p>
<p>Let’s look at the coefficient estimates for the resampled dataset. <a href="#tbl-births-resample" class="quarto-xref">Table&nbsp;3</a> displays the estimated regression coefficients for modeling the relationship between <code>mage</code> and <code>weight</code> for the resample of 1,000 birth records.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>resample_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(weight <span class="sc">~</span> mage, <span class="at">data =</span> resample1)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">get_regression_table</span>(resample_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div id="tbl-births-resample" class="cell quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-births-resample-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: The least squares estimates of the intercept and slope for modeling the relationship between baby’s birth weight and mother’s age, for the <em>resample</em> of 1,000 birth records.
</figcaption>
<div aria-describedby="tbl-births-resample-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std_error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p_value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">lower_ci</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">upper_ci</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">intercept</td>
<td style="text-align: right;">6.981</td>
<td style="text-align: right;">0.220</td>
<td style="text-align: right;">31.738</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">6.549</td>
<td style="text-align: right;">7.413</td>
</tr>
<tr class="even">
<td style="text-align: left;">mage</td>
<td style="text-align: right;">0.005</td>
<td style="text-align: right;">0.008</td>
<td style="text-align: right;">0.684</td>
<td style="text-align: right;">0.494</td>
<td style="text-align: right;">-0.010</td>
<td style="text-align: right;">0.020</td>
</tr>
</tbody>
</table>


</div>
</div>
</figure>
</div>
</div>
<p>For the resampled dataset, the relationship between mother’s age and baby birth weight is much weaker than in the original sample, with an estimated slope of <span class="math inline">\(b_1 =\)</span> 0.005.</p>
<p>What if we repeated this resampling exercise many times? Would we obtain the same slope each time? In other words, would our guess at the slope for the relationship between mother’s age and baby’s birth weight for all births in the US in 2014 exactly 0.005 every time?</p>
</section>
</section>
<section id="computer-simulation-and-resampling" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="computer-simulation-and-resampling"><span class="header-section-number">2</span> Computer simulation and resampling</h2>
<p>It should be very clear that tactile resampling with a dataset with 1,000 observations would be extremely time consuming, nothing we would want to ask our friends to do. A computer, however, would be happy to do this process for us!</p>
<section id="virtually-resampling-once" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="virtually-resampling-once"><span class="header-section-number">2.1</span> Virtually resampling once</h3>
<p>First, let’s perform the virtual analog of resampling once. Recall that the <code>births14</code> dataset included in the <strong>openintro</strong> package contains the 1,000 birth records from the original study. Furthermore, recall in the last chapter that we used the <code>rep_sample_n()</code> function as a virtual shovel to sample balls from our virtual bowl of 2400 balls as follows:</p>
<p>Let’s modify this code to perform the resampling <em>with replacement</em> from the 1,000 birth records in the original sample:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>virtual_resample <span class="ot">&lt;-</span> <span class="fu">rep_sample_n</span>(births14, </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">size =</span> <span class="dv">1000</span>,</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">replace =</span> <span class="cn">TRUE</span>, </span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">reps =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Observe how we explicitly set the <code>replace</code> argument to <code>TRUE</code> in order to tell <code>rep_sample_n()</code> that we would like to sample birth records <em>with replacement</em>. Had we not kept <code>replace = FALSE</code>, we would have done resampling <em>without replacement</em>. Additionally, we changed the sample <code>size</code>, as we need to create a sample with the <em>same</em> size as the original sample which had 1,000 observations.</p>
<p>Let’s look at only the first 10 out of 1,000 rows of <code>virtual_resample</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>virtual_resample</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,000 × 15
# Groups:   replicate [1]
   replicate    ID  mage weight  fage mature      weeks premie    visits gained
       &lt;int&gt; &lt;int&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;int&gt; &lt;chr&gt;       &lt;dbl&gt; &lt;chr&gt;      &lt;dbl&gt;  &lt;dbl&gt;
 1         1   333    29   7.4     31 younger mom    39 full term     13     50
 2         1   595    29   0.75    NA younger mom    21 premie         4     NA
 3         1   338    31   6.94    NA younger mom    39 full term      9     20
 4         1   531    33   6.94    37 younger mom    39 full term     14     20
 5         1   289    35   7.98    35 mature mom     38 full term     10     40
 6         1   461    32   7.15    33 younger mom    39 full term     13     NA
 7         1   137    26   7.69    36 younger mom    38 full term     NA     25
 8         1   828    36   4.54    65 mature mom     36 premie        11     10
 9         1   118    26   8.31    24 younger mom    37 full term     12     25
10         1    95    38   6.04    37 mature mom     36 premie        10     32
# ℹ 990 more rows
# ℹ 5 more variables: lowbirthweight &lt;chr&gt;, sex &lt;chr&gt;, habit &lt;chr&gt;,
#   marital &lt;chr&gt;, whitemom &lt;chr&gt;</code></pre>
</div>
</div>
<p>The <code>replicate</code> variable only takes on the value of 1 corresponding to us only having <code>reps = 1</code>, the <code>ID</code> variable indicates which of the 1,000 birth records was resampled, and <code>mage</code> and <code>weight</code> denote mother’s age and the baby’s birth weight, respectively.</p>
<p>Let’s now compute the slope for the relationship between mother’s age and baby’s birth weight for this resample:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>virtual_resample_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(weight <span class="sc">~</span> mage, <span class="at">data =</span> virtual_resample)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">get_regression_table</span>(virtual_resample_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div id="tbl-virtual-resample-lm" class="cell quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-virtual-resample-lm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: The least squares estimates of the intercept and slope for modeling the relationship between baby’s birth weight and mother’s age, for the virtual resample of 1,000 birth records.
</figcaption>
<div aria-describedby="tbl-virtual-resample-lm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std_error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p_value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">lower_ci</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">upper_ci</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">intercept</td>
<td style="text-align: right;">7.156</td>
<td style="text-align: right;">0.224</td>
<td style="text-align: right;">31.974</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">6.716</td>
<td style="text-align: right;">7.595</td>
</tr>
<tr class="even">
<td style="text-align: left;">mage</td>
<td style="text-align: right;">0.002</td>
<td style="text-align: right;">0.008</td>
<td style="text-align: right;">0.210</td>
<td style="text-align: right;">0.834</td>
<td style="text-align: right;">-0.014</td>
<td style="text-align: right;">0.017</td>
</tr>
</tbody>
</table>


</div>
</div>
</figure>
</div>
</div>
<p>As we saw when we did our tactile resampling exercise, <a href="#tbl-virtual-resample-lm" class="quarto-xref">Table&nbsp;4</a> shows that the estimated slope is different from the slope of our original sample of 0.005.</p>
</section>
<section id="infer-package-workflow" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="infer-package-workflow"><span class="header-section-number">2.2</span> <strong>infer</strong> package workflow</h3>
<p>Unfortunately, our process of virtual resampling relies on us fitting a linear regression for each <code>rep</code>licate of our <code>virtual_resample</code> dataset. This gets a bit tricky coding wise, as we would need to fit 35 different linear regressions if we had 35 different resamples of our data.</p>
<p>Enter, <strong>infer</strong>, an R package for statistical inference. <strong>infer</strong> makes efficient use of the <code>%&gt;%</code> pipe operator we learned in Week 3 to spell out the sequence of steps necessary to perform statistical inference in a “tidy” and transparent fashion. Furthermore, just as the <strong>dplyr</strong> package provides functions with verb-like names to perform data wrangling, the <strong>infer</strong> package provides functions with intuitive verb-like names to perform statistical inference.</p>
<p>Let’s go back to our original slope. Previously, we computed the value of the sample slope <span class="math inline">\(b_1\)</span> using the <code>lm()</code> function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>births_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(weight <span class="sc">~</span> mage, <span class="at">data =</span> births14)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">get_regression_table</span>(births_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We’ll see that we can also do this using <strong>infer</strong> functions <code>specify()</code> and <code>calculate()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>births14 <span class="sc">%&gt;%</span> </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">specify</span>(<span class="at">response =</span> weight, </span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">explanatory =</span> mage) <span class="sc">%&gt;%</span> </span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">calculate</span>(<span class="at">stat =</span> <span class="st">"slope"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You might be asking yourself: “Isn’t the <strong>infer</strong> code longer? Why would I use that code?”. While not immediately apparent, you’ll see that there are three chief benefits to the <strong>infer</strong> workflow as opposed to the <code>lm()</code> function workflow we had previously.</p>
<p>First, the <strong>infer</strong> verb names better align with the overall resampling framework you need to understand to construct confidence intervals and to conduct hypothesis tests. We’ll see flowchart diagrams of this framework in the upcoming <a href="#fig-infer-workflow-ci" class="quarto-xref">Figure&nbsp;12</a>.</p>
<p>Second, you can jump back and forth seamlessly between confidence intervals and hypothesis testing with minimal changes to your code. This will become apparent next week, when we also use <strong>infer</strong> to conduct hypothesis tests for the slope statistic.</p>
<p>Third, the <strong>infer</strong> workflow is much simpler for conducting inference when you have <em>more than one variable</em>, meaning we can extend what we’ve learned for simple linear regression to multiple linear regression models.</p>
<p>Let’s now illustrate the sequence of verbs necessary to construct a confidence interval for <span class="math inline">\(\b_1\)</span>, the slope of the relationship between mother’s age and baby’s birth weight for all US births in 2014.</p>
<section id="sec-specify" class="level4">
<h4 class="anchored" data-anchor-id="sec-specify">1. <code>specify()</code> variables</h4>
<div id="fig-infer-specify" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-infer-specify-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/specify.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-infer-specify-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: “Diagram of <code>specify()</code>ing variables.”
</figcaption>
</figure>
</div>
<p>As shown in <a href="#fig-infer-specify" class="quarto-xref">Figure&nbsp;7</a>, the <code>specify()</code> function is used to choose which variables in a data frame will be the focus of our statistical inference. We do this by <code>specify</code>ing the <code>response</code> argument. For example, in our <code>births14</code> data frame, the response variable of interest is <code>weight</code> and the explanatory variable is <code>mage</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>births14 <span class="sc">%&gt;%</span> </span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">specify</span>(<span class="at">response =</span> weight, </span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">explanatory =</span> mage)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Response: weight (numeric)
Explanatory: mage (numeric)
# A tibble: 1,000 × 2
   weight  mage
    &lt;dbl&gt; &lt;dbl&gt;
 1   6.96    34
 2   8.86    31
 3   7.51    36
 4   6.19    16
 5   6.75    31
 6   6.69    26
 7   6.13    36
 8   6.74    24
 9   8.94    32
10   9.12    26
# ℹ 990 more rows</code></pre>
</div>
</div>
<p>Notice how the dataset got smaller, now there are only two columns where before there were 14. You should also notice the messages above the dataset (<code>Response: weight (numeric)</code> and <code>Explanatory: mage</code>). These are <em>meta-data</em> about the grouping structure of the dataset, declaring which variable has been assigned to the explanatory / response.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>This is similar to how the <code>group_by()</code> verb from <code>dplyr</code> doesn’t change the data, but only adds “grouping” meta-data, as we saw in Week 3.</p>
</div>
</div>
</section>
<section id="sec-generate" class="level4">
<h4 class="anchored" data-anchor-id="sec-generate">2. <code>generate()</code> replicates</h4>
<div id="fig-infer-generate" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-infer-generate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/generate.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-infer-generate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: “Diagram of <code>generate()</code> replicates.”
</figcaption>
</figure>
</div>
<p>After we <code>specify()</code> the variables of interest, we pipe the results into the <code>generate()</code> function to generate replicates. <a href="#fig-infer-generate" class="quarto-xref">Figure&nbsp;8</a> shows how this is combined with <code>specify()</code> to start the pipeline. In other words, repeat the resampling process a large number of times, similar to how we collected 35 different samples of balls from the bowl.</p>
<p>The <code>generate()</code> function’s first argument is <code>reps</code>, which sets the number of replicates we would like to generate. Suppose we were interested in obtaining 50 different resamples (each of 1,000 birth records). Then, we would we set <code>reps = 50</code>, telling <strong>infer</strong> that we are interested in obtaining 50 different resamples, each with 1,000 observations.</p>
<p>The second argument <code>type</code> determines the type of computer simulation we’d like to perform. We set this to <code>type = "bootstrap"</code> indicating that we want to perform bootstrap resampling, meaning the resampling should be done <em>with replacement</em>. You’ll see different options for <code>type</code> when we learn about hypothesis testing next week.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>births14 <span class="sc">%&gt;%</span> </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">specify</span>(<span class="at">response =</span> weight, </span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">explanatory =</span> mage) <span class="sc">%&gt;%</span> </span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">generate</span>(<span class="at">reps =</span> <span class="dv">50</span>, </span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">type =</span> <span class="st">"bootstrap"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Response: weight (numeric)
Explanatory: mage (numeric)
# A tibble: 50,000 × 3
# Groups:   replicate [50]
   replicate weight  mage
       &lt;int&gt;  &lt;dbl&gt; &lt;dbl&gt;
 1         1  10.6     31
 2         1   4.31    31
 3         1   4.94    33
 4         1   5.65    36
 5         1   8       23
 6         1   7.63    37
 7         1   8       19
 8         1   3.22    30
 9         1   8.56    32
10         1   4.32    21
# ℹ 49,990 more rows</code></pre>
</div>
</div>
<p>Observe that the resulting data frame has 50,000 rows. This is because we performed resampling of 1000 birth records with replacement 50 times and 1000 <span class="math inline">\(\times\)</span> 50 = 50,000.</p>
<p>The variable <code>replicate</code> indicates which resample each row belongs to. So it has the value <code>1</code> 1000 times, the value <code>2</code> 1000 times, all the way through to the value 50 1000 times.</p>
<p><strong>Comparing with original workflow</strong>: Note that the steps of the <strong>infer</strong> workflow so far produce the same results as the original workflow using the <code>rep_sample_n()</code> function we saw earlier. In other words, the following two code chunks produce similar results:</p>
<div class="columns">
<div class="column" style="width:45%;">
<p><strong>infer</strong> workflow</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>births14 <span class="sc">%&gt;%</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">specify</span>(<span class="at">response =</span> weight, </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">explanatory =</span> mage) <span class="sc">%&gt;%</span> </span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">generate</span>(<span class="at">reps =</span> <span class="dv">50</span>, </span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">type =</span> <span class="st">"bootstrap"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div><div class="column" style="width:5%;">

</div><div class="column" style="width:45%;">
<p>Original workflow</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rep_sample_n</span>(births14, </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">size =</span> <span class="dv">1000</span>, </span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">replace =</span> <span class="cn">TRUE</span>,</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">reps =</span> <span class="dv">50</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</section>
<section id="sec-calculate" class="level4">
<h4 class="anchored" data-anchor-id="sec-calculate">3. <code>calculate()</code> summary statistics</h4>
<div id="fig-calculate" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-calculate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/calculate.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-calculate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9: Diagram of calculate()d summary statistics.
</figcaption>
</figure>
</div>
<p>After we <code>generate()</code> many replicates of bootstrap resampling with replacement, we next want to summarize each of the 50 resamples of size 1000 to a single sample statistic value. As seen in <a href="#fig-calculate" class="quarto-xref">Figure&nbsp;9</a>, the <code>calculate()</code> function does this.</p>
<p>In our case, we want to calculate the slope between mother’s age and baby’s birth weight for each bootstrap resample of size 1000. To do so, we set the <code>stat</code> argument to <code>"slope"</code>.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>You can also set the <code>stat</code> argument to a variety of other common summary statistics, like <code>"median"</code>, <code>"sum"</code>, <code>"sd"</code> (standard deviation), and <code>"prop"</code> (proportion). To see a list of all possible summary statistics you can use, type <code>?calculate</code> and read the help file.</p>
</div>
</div>
<p>Let’s save the result in a data frame called <code>bootstrap_distribution</code> and explore its contents:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>bootstrap_distribution <span class="ot">&lt;-</span> births14 <span class="sc">%&gt;%</span> </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">specify</span>(<span class="at">response =</span> weight, </span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">explanatory =</span> mage) <span class="sc">%&gt;%</span> </span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">generate</span>(<span class="at">reps =</span> <span class="dv">50</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">calculate</span>(<span class="at">stat =</span> <span class="st">"slope"</span>)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>bootstrap_distribution</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Response: weight (numeric)
Explanatory: mage (numeric)
# A tibble: 50 × 2
   replicate    stat
       &lt;int&gt;   &lt;dbl&gt;
 1         1 0.0328 
 2         2 0.0181 
 3         3 0.0123 
 4         4 0.0106 
 5         5 0.0183 
 6         6 0.0190 
 7         7 0.0145 
 8         8 0.00824
 9         9 0.0155 
10        10 0.0160 
# ℹ 40 more rows</code></pre>
</div>
</div>
<p>Observe that the resulting data frame has 50 rows and two columns. The <code>replicate</code> column corresponds to the 50 replicates and the <code>stat</code> column corresponds to the estimated slope for each resample.</p>
</section>
<section id="visualize-the-results" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="visualize-the-results">4. <code>visualize()</code> the results</h4>
<div id="fig-visualize" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-visualize-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/visualize.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-visualize-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10: Diagram of closing the entire process by visualize()ing the results.
</figcaption>
</figure>
</div>
<p>The <code>visualize()</code>verb provides a quick way to visualize the bootstrap distribution as a histogram of the numerical <code>stat</code> variable’s values. The pipeline of the main <strong>infer</strong> verbs used for exploring bootstrap distribution results is shown in <a href="#fig-infer-visualize" class="quarto-xref">Figure&nbsp;11</a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">visualize</span>(bootstrap_distribution)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-infer-visualize" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-infer-visualize-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="week7-reading2_files/figure-html/fig-infer-visualize-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-infer-visualize-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11: Bootstrap distribution of slope statistics from 50 bootstrap resamples.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <code>visualize()</code> function can take many other arguments which we’ll see momentarily to customize the plot further. It also works with helper functions to do the shading of the histogram values corresponding to the confidence interval values.</p>
</div>
</div>
<p><strong>Comparing with original workflow</strong>: In fact, <code>visualize()</code> is a <em>wrapper function</em> for the <code>ggplot()</code> function that uses a <code>geom_histogram()</code> layer. That’s a lot of fancy language which means that the <code>visualize()</code> function does the <strong>same</strong> thing as we did previously with <code>ggplot()</code>, just with fewer steps.</p>
<div class="columns">
<div class="column" style="width:45%;">
<p><strong>infer</strong> workflow</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">visualize</span>(bootstrap_distribution)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div><div class="column" style="width:5%;">

</div><div class="column" style="width:50%;">
<p>Original workflow</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> bootstrap_distribution,</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> stat)) <span class="sc">+</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Caution
</div>
</div>
<div class="callout-body-container callout-body">
<p>Careful! It might sound tempting to ditch the <code>ggplot()</code> code altogether now that you know of a simpler approach. The <code>visualize()</code> function only works for a specific case – a data frame containing a distribution of <code>calculate()</code>d statistics.</p>
</div>
</div>
<p>Let’s recap the steps of the <strong>infer</strong> workflow for constructing a bootstrap distribution and then visualizing it in <a href="#fig-infer-workflow-ci" class="quarto-xref">Figure&nbsp;12</a>.</p>
<div id="fig-infer-workflow-ci" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-infer-workflow-ci-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/ci_diagram.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-infer-workflow-ci-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12: infer package workflow for resampling
</figcaption>
</figure>
</div>
</section>
</section>
<section id="virtually-resampling-1000-times" class="level3" data-number="2.3">
<h3 data-number="2.3" class="anchored" data-anchor-id="virtually-resampling-1000-times"><span class="header-section-number">2.3</span> Virtually resampling 1,000 times</h3>
<p>To change from resampling 50 times to resampling 1,000 times, only one line of code needs to change—the number of <code>reps</code>. In the code process below, we’ve chained together the entire <strong>infer</strong> pipeline, connecting the specify, generate, calculate, and visualize steps.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>bootstrap_1000 <span class="ot">&lt;-</span> births14 <span class="sc">|&gt;</span> </span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">specify</span>(<span class="at">response =</span> weight, </span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">explanatory =</span> mage) <span class="sc">|&gt;</span> </span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">generate</span>(<span class="at">reps =</span> <span class="dv">1000</span>, </span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">type =</span> <span class="st">"bootstrap"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">calculate</span>(<span class="at">stat =</span> <span class="st">"slope"</span>) </span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a><span class="fu">visualize</span>(bootstrap_1000) <span class="sc">+</span> </span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Bootstrap Slope Statistic"</span>, </span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Bootstrap Distribution of 1,000 Resamples"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-infer-1000" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-infer-1000-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="week7-reading2_files/figure-html/fig-infer-1000-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-infer-1000-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13: Bootstrap distribution with 1,000 replicates.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Changing axis labels
</div>
</div>
<div class="callout-body-container callout-body">
<p>Notice you can still use the <code>labs()</code> function to change your axis labels. Notice that you still need to connect the axis labels with the plot using a <code>+</code> sign.</p>
</div>
</div>
<p>What do you notice about this distribution? What distribution does it resemble? Why is that the case?</p>
</section>
<section id="connection-to-sampling-distributions" class="level3" data-number="2.4">
<h3 data-number="2.4" class="anchored" data-anchor-id="connection-to-sampling-distributions"><span class="header-section-number">2.4</span> Connection to sampling distributions</h3>
<p>The histogram of sample slopes in <a href="#fig-infer-1000" class="quarto-xref">Figure&nbsp;13</a> is called the <strong>bootstrap distribution</strong>. The bootstrap distribution is an <em>approximation</em> to the sampling distribution of sample slopes.</p>
<p>If you recall back to the last chapter, a sampling distribution was a distribution of statistics from repeatedly <em>sampling</em> from the <strong>population</strong>. However, a bootstrap distribution is a distribution of statistics from repeatedly <em>resampling</em> from the <strong>sample</strong>. This may seem rather strange, how can a distribution based entirely on the sample approximate a distribution based on the population? That’s a great question!</p>
<p>The bootstrapping process hinges on the belief that the sample is representative of the population. Meaning, there are not systematic differences between the sample and the population. For example, if there were no young mothers in the sample of 1,000 birth records in the <code>births14</code> dataset. If we have a random sample, however, then on average our sample should look very similar to our population. Meaning, the individuals in the sample can “stand in” for individuals in the population with similar characteristics. So, we can think of repeatedly <em>resampling</em> from our sample as a similar process as sampling from the population.</p>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
No guaranteed representation
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The process of randomly sampling <strong>does not</strong> guarantee that smaller groups of observations will <em>always</em> appear in the sample. Rather, by randomly sampling from the population, on average the representation of individuals in the sample should reflect the proportion of individuals in the population.</p>
<p>To me, this feels rather uncomfortable as a random sample assumes that you can generalize from the sample onto the population from which it was drawn. This means you are generalizing the observations of a few individuals onto the entire population of similar individuals. For example, if you were to collect a random sample of Cal Poly students, it is likely your sample would include very few Black students (as Cal Poly is a predominantly white institution). But, if your sample was random, statistically you could infer from your small sample of Black students onto the entire population of Black students at Cal Poly. That seems kind of iffy to me.</p>
</div>
</div>
</div>
</section>
</section>
<section id="sec-understanding" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="sec-understanding"><span class="header-section-number">3</span> Understanding confidence intervals</h2>
<p>Let’s start this section with an analogy involving fishing. Say you are trying to catch a fish. On the one hand, you could use a spear, while on the other you could use a net. Using the net will probably allow you to catch more fish!</p>
<p>In the <code>births14</code> investigation, we are trying to estimate the population slope for the relationship between mother’s age and baby’s birth weight (<span class="math inline">\(\beta_1\)</span>) for <strong>all</strong> babies born in the US in 2014. Think of the value of <span class="math inline">\(\beta_1\)</span> as a fish.</p>
<p>On the one hand, we could use the appropriate <em>point estimate/sample statistic</em> to estimate <span class="math inline">\(\beta_1\)</span>, which we saw in <a href="#tbl-births-slr" class="quarto-xref">Table&nbsp;1</a> is the sample slope <span class="math inline">\(b_1\)</span>. Based on our sample of 1000 birth records, the sample slope was 0.014. Think of using this value as “fishing with a spear.”</p>
<p>What would “fishing with a net” correspond to? Look at the bootstrap distribution in <a href="#fig-infer-1000" class="quarto-xref">Figure&nbsp;13</a> once more. Between which values would you say that “most” sample slopes lie? While this question is somewhat subjective, saying that most sample slopes lie between 0 and 0.03 would not be unreasonable. Think of this interval as the “net.”</p>
<p>What we’ve just illustrated is the concept of a <em>confidence interval</em>, which I’ll abbreviate with “CI” throughout this chapter. As opposed to a point estimate / sample statistic that estimates the value of an unknown population parameter with a single value, a <em>confidence interval</em> gives what can be interpreted as a range of plausible values. Going back to our analogy, point estimates / sample statistics can be thought of as spears, whereas confidence intervals can be thought of as nets.</p>
<div id="fig-spear-net" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-spear-net-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/point_estimate_vs_conf_int.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-spear-net-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14: Analogy of difference between point estimates and confidence intervals.
</figcaption>
</figure>
</div>
<p>Our proposed interval of 0 to 0.03 was constructed by eye and was thus somewhat subjective. We now introduce two methods for constructing such intervals in a more exact fashion: the <em>percentile method</em> and the <em>standard error method</em>.</p>
<p>Both methods for confidence interval construction share some commonalities. First, they are both constructed from a bootstrap distribution, as you constructed in the previous section and visualized in <a href="#fig-infer-1000" class="quarto-xref">Figure&nbsp;13</a>.</p>
<p>Second, they both require you to specify the <em>confidence level</em>. Commonly used confidence levels include 90%, 95%, and 99%. All other things being equal, higher confidence levels correspond to wider confidence intervals, and lower confidence levels correspond to narrower confidence intervals.</p>
<section id="sec-percentile-method" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="sec-percentile-method"><span class="header-section-number">3.1</span> Percentile method</h3>
<p>One method to construct a 95% confidence interval is to use the middle 95% of values of the bootstrap distribution. We can do this by computing the 2.5th and 97.5th percentiles, which are 0.0002 and 0.0281, respectively. This is known as the <em>percentile method</em> for constructing confidence intervals.</p>
<p>For now, let’s focus only on the concepts behind a percentile method constructed confidence interval; we’ll show you the code that computes these values in the next section.</p>
<p>Let’s mark these percentiles on the bootstrap distribution with vertical lines in <a href="#fig-percentile-method" class="quarto-xref">Figure&nbsp;15</a>. About 95% of the <code>slope</code> variable values in <code>bootstrap_1000</code> fall between 0.0002 and 0.0281, with 2.5% to the left of the leftmost line and 2.5% to the right of the rightmost line.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-percentile-method" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-percentile-method-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="week7-reading2_files/figure-html/fig-percentile-method-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-percentile-method-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;15: Percentile method 95% confidence interval. Interval endpoints marked by vertical lines.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="sec-se-method" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="sec-se-method"><span class="header-section-number">3.2</span> Standard error method</h3>
<p>Recall in the last chapter we saw that if a numerical variable follows a normal distribution, or, in other words, the histogram of this variable is bell-shaped, then roughly 95% of values fall between <span class="math inline">\(\pm\)</span> 1.96 standard deviations of the mean. Given that our bootstrap distribution based on 1000 resamples with replacement in <a href="#fig-infer-1000" class="quarto-xref">Figure&nbsp;13</a> is normally shaped, let’s use this fact about normal distributions to construct a confidence interval in a different way.</p>
<p>First, recall the bootstrap distribution has a mean equal to 0.014. This value almost coincides exactly with the value of the sample slope <span class="math inline">\(b_1\)</span> of our original 1000 birth records 0.014. Second, let’s compute the standard deviation of the bootstrap distribution using the bootstrap slope statistics stored in the <code>stat</code> column of the <code>bootstrap_1000</code> data frame:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>bootstrap_1000 <span class="sc">%&gt;%</span> </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">SE =</span> <span class="fu">sd</span>(stat))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
       SE
    &lt;dbl&gt;
1 0.00722</code></pre>
</div>
</div>
<p>What is this value? Recall that the bootstrap distribution is an approximation to the sampling distribution. Thus, the variability of the sampling distribution may be approximated by the variability of the resampling distribution. Recall also that the standard deviation of a sampling distribution has a special name: the <em>standard error</em>. Putting these two facts together, we can say that 0.00722 is an approximation of the standard error of <span class="math inline">\(b_1\)</span>.</p>
<p>Traditional theory-based methodologies for inference also have formulas for standard errors, assuming some conditions are not violated. In this method, we are not using a formula to get our standard error, but using the standard error of the bootstrap distribution. Thus, using our 95% rule of thumb about normal distributions, we can use the following formula to determine the lower and upper endpoints of a 95% confidence interval for <span class="math inline">\(\beta_1\)</span>:</p>
<p><span class="math display">\[
b_1 \pm 1.96 \times SE = (b_1 - 1.96 \times SE, b_1 + 1.96 \times SE)
\]</span></p>
<p><span class="math display">\[
= (0.014 - 1.96 \times 0.007, 0.014 + 1.96 \times 0.007)
\]</span></p>
<p><span class="math display">\[
= (0.00028, 0.02772)
\]</span></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>To use the bootstrap standard error in this formula the bootstrap distribution <strong>must</strong> be bell shaped and symmetric. This is often the case with bootstrap distributions, especially those in which the original distribution of the sample is not highly skewed, however it is not always the case. Next week, we’ll go deeper into the explorations of model conditions.</p>
</div>
</div>
<p>Let’s now add the SE method confidence interval with dashed lines in <a href="#fig-percentile-and-se-method" class="quarto-xref">Figure&nbsp;16</a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-percentile-and-se-method" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-percentile-and-se-method-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="week7-reading2_files/figure-html/fig-percentile-and-se-method-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-percentile-and-se-method-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;16: Comparing two 95% confidence interval methods.
</figcaption>
</figure>
</div>
</div>
</div>
<p>We see that both methods produce nearly identical 95% confidence intervals for <span class="math inline">\(\beta_1\)</span> with the percentile method yielding <span class="math inline">\((0.0002, 0.0281)\)</span> while the standard error method produces <span class="math inline">\((0.0001, 0.0284)\)</span>.</p>
<p>Now that we’ve introduced the concept of confidence intervals and laid out the intuition behind two methods for constructing them, let’s explore the code that allows us to construct them.</p>
</section>
</section>
<section id="constructing-confidence-intervals" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="constructing-confidence-intervals"><span class="header-section-number">4</span> Constructing confidence intervals</h2>
<p>Now that we’ve covered two methods for obtaining confidence intervals, let’s now check out the <strong>infer</strong> package code that explicitly constructs these. There are also some additional neat functions to visualize the resulting confidence intervals built-in to the <strong>infer</strong> package!</p>
<section id="sec-percentile-infer" class="level4">
<h4 class="anchored" data-anchor-id="sec-percentile-infer">Percentile method with <strong>infer</strong></h4>
<p>Recall the percentile method for constructing 95% confidence intervals we introduced in <a href="#sec-percentile-method" class="quarto-xref">Section&nbsp;3.1</a>. This method sets the lower endpoint of the confidence interval at the 2.5th percentile of the bootstrap distribution and similarly sets the upper endpoint at the 97.5th percentile. The resulting interval captures the middle 95% of the values of the sample mean in the bootstrap distribution.</p>
<p>We can compute the 95% confidence interval using the <code>get_confidence_interval()</code> function function from the <code>infer</code> package. This function takes three arguments (inputs):</p>
<ul>
<li>a data frame containing <code>calculate()</code>d statistics (e.g., slope statistics)</li>
<li>a confidence <code>level</code> (e.g., 0.95 or 0.99)</li>
<li>the <code>type</code> of interval to be made – <code>"percentile"</code> or <code>"se"</code></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>percentile_ci <span class="ot">&lt;-</span> <span class="fu">get_confidence_interval</span>(bootstrap_distribution, </span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>                                         <span class="at">level =</span> <span class="fl">0.95</span>, </span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>                                         <span class="at">type =</span> <span class="st">"percentile"</span>)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>percentile_ci</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  lower_ci upper_ci
     &lt;dbl&gt;    &lt;dbl&gt;
1 -0.00185   0.0285</code></pre>
</div>
</div>
<p>Alternatively, we can visualize this interval by adding a <code>shade_confidence_interval()</code> layer to the <code>visualize()</code> step. This step requires the <code>endpoints</code> of the interval to be specified, so the previous step <strong>must</strong> come <em>before</em> the following step.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">visualize</span>(bootstrap_1000) <span class="sc">+</span> </span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">shade_confidence_interval</span>(<span class="at">endpoints =</span> percentile_ci)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-percentile-ci-viz" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-percentile-ci-viz-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="week7-reading2_files/figure-html/fig-percentile-ci-viz-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-percentile-ci-viz-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;17: Percentile method 95% confidence interval shaded corresponding to potential values.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Observe in <a href="#fig-percentile-ci-viz" class="quarto-xref">Figure&nbsp;17</a> that 95% of the sample slopes stored in the <code>stat</code> variable in <code>bootstrap_1000</code> fall between the two endpoints marked with the darker lines, with 2.5% of the sample means to the left of the shaded area and 2.5% of the sample means to the right.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>The default colors for <code>shade_confidence_interval()</code> are <code>color = "mediumaquamarine"</code> and <code>fill = "turquoise"</code>. You can, however, change these colors if you wish!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">visualize</span>(bootstrap_distribution) <span class="sc">+</span> </span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">shade_ci</span>(<span class="at">endpoints =</span> percentile_ci, <span class="at">color =</span> <span class="st">"hotpink"</span>, <span class="at">fill =</span> <span class="st">"khaki"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</section>
<section id="sec-se-infer" class="level4">
<h4 class="anchored" data-anchor-id="sec-se-infer">Standard error method with <code>infer</code></h4>
<p>Recall the standard error method for constructing 95% confidence intervals we introduced in <a href="#sec-se-method" class="quarto-xref">Section&nbsp;3.2</a>. From properties of the Normal Distribution, we know that for any distribution that is bell shaped and symmetric, roughly 95% of the values lie within two standard deviations of the mean. Recall that in the case of the sampling distribution, the standard deviation has a special name: the <em>standard error</em>. Moreover, remember that the bootstrap distribution provides us with a robust estimate of the standard error of the sampling distribution.</p>
<p>So in our case, 95% of values of the bootstrap distribution will lie within <span class="math inline">\(\pm 1.96\)</span> standard errors of <span class="math inline">\(b_1\)</span>. Thus, a 95% confidence interval is</p>
<p><span class="math display">\[
b_a \pm 1.96 \times SE = (b_1 - 1.96 \times SE, b_1 + 1.96 \times SE)
\]</span></p>
<p>Computation of the 95% confidence interval can once again be done by inputting the the <code>bootstrap_1000</code> data frame we created into the <code>get_confidence_interval()</code> function, using roughly the same code as before. There are two components, however, that must change:</p>
<ul>
<li>we need to set the <code>type</code> argument to be <code>"se"</code></li>
<li>we need to specify where the confidence interval should be centered – the <code>point_estimate</code></li>
</ul>
<p>To calculate the point estimate, we need one additional step <strong>before</strong> calculating our confidence interval. Rather than using the output from the <code>lm()</code> function like we did in <a href="#tbl-births-slr" class="quarto-xref">Table&nbsp;1</a>, let’s obtain our observed slope statistic using the infer pipeline! This process should look familiar, in fact the only part that has changed is we no longer have a <code>generate()</code> step. We are not generating any resamples, so that step is no longer needed. All we need to do is <code>specify()</code> our variables and <code>calculate()</code> the <code>"slope"</code> statistic.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>obs_slope <span class="ot">&lt;-</span> births14 <span class="sc">|&gt;</span> </span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">specify</span>(<span class="at">response =</span> weight, </span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">explanatory =</span> mage) <span class="sc">|&gt;</span> </span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">calculate</span>(<span class="at">stat =</span> <span class="st">"slope"</span>)</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>standard_error_ci <span class="ot">&lt;-</span> <span class="fu">get_confidence_interval</span>(bootstrap_1000, </span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>                                             <span class="at">type =</span> <span class="st">"se"</span>, </span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>                                             <span class="at">point_estimate =</span> obs_slope, </span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>                                             <span class="at">level =</span> <span class="fl">0.95</span>)</span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>standard_error_ci</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
   lower_ci upper_ci
      &lt;dbl&gt;    &lt;dbl&gt;
1 0.0000947   0.0284</code></pre>
</div>
</div>
<p>If we would like to visualize this interval, we can once again add a <code>shade_confidence_interval()</code> layer to our plot. However, when visualizing an interval constructed using the SE method, we need to declare the <code>endpoints</code> of the interval, as seen in <a href="#fig-se-ci-viz" class="quarto-xref">Figure&nbsp;18</a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">visualize</span>(bootstrap_1000) <span class="sc">+</span> </span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">shade_confidence_interval</span>(<span class="at">endpoints =</span> standard_error_ci)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-se-ci-viz" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-se-ci-viz-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="week7-reading2_files/figure-html/fig-se-ci-viz-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-se-ci-viz-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;18: Standard-error-method 95% confidence interval.
</figcaption>
</figure>
</div>
</div>
</div>
<p>As noted in <a href="#sec-se-method" class="quarto-xref">Section&nbsp;3.2</a>, both methods produce similar confidence intervals:</p>
<div class="cell">
<div id="tbl-comparison-of-intervals" class="cell quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-comparison-of-intervals-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Comparison of 95% confidence intervals between percentile and SE methods.
</figcaption>
<div aria-describedby="tbl-comparison-of-intervals-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">type</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">2.5%</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">97.5%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Percentile</td>
<td style="text-align: right;">-0.0018499</td>
<td style="text-align: right;">0.0285359</td>
</tr>
<tr class="even">
<td style="text-align: left;">SE</td>
<td style="text-align: right;">0.0000947</td>
<td style="text-align: right;">0.0283909</td>
</tr>
</tbody>
</table>


</div>
</div>
</figure>
</div>
</div>
</section>
</section>
<section id="interpreting-confidence-intervals" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="interpreting-confidence-intervals"><span class="header-section-number">5</span> Interpreting confidence intervals</h2>
<p>Now that we’ve shown you how to construct confidence intervals using a sample drawn from a population, let’s now focus on how to interpret their effectiveness. The effectiveness of a confidence interval is judged by whether or not it contains the true value of the population parameter. Going back to our fishing analogy in <a href="#sec-understanding" class="quarto-xref">Section&nbsp;3</a>, this is like asking, “Did our net capture the fish?”.</p>
<p>So, for example, does our percentile-based confidence interval of (-0.0018, 0.0285) “capture” the slope of the relationship between mother’s age and baby’s birth weight (<span class="math inline">\(\beta_1\)</span>) for <em>all</em> babies born in the US in 2014? Alas, we’ll never know, because we don’t know what the true value of <span class="math inline">\(\beta_1\)</span> is. After all, we’re sampling to estimate it!</p>
<p>In order to interpret a confidence interval’s effectiveness, we need to <em>know</em> what the value of the population parameter is. That way we can say whether or not a confidence interval “captured” this value. In the case of <code>births14</code> dataset, we have the ability to go find the original dataset, housing the birth records of every baby born in the US in 2014. I did so, and found that the slope for the relationship between mother’s age and baby’s birth weight (<span class="math inline">\(\beta_1\)</span>) for <em>all</em> babies born in the US in 2014 was <span class="math inline">\(\beta_1 = 0.0007\)</span>.</p>
<section id="did-our-intervals-capture-beta_1" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="did-our-intervals-capture-beta_1"><span class="header-section-number">5.1</span> Did our interval(s) capture <span class="math inline">\(\beta_1\)</span>?</h3>
<p>Now that we know the value of <span class="math inline">\(\beta_1\)</span>, we can see if the intervals we constructed previously do in fact contain this parameter. The percentile interval of (-0.0018, 0.0285) contains <span class="math inline">\(\beta_1 = 0.0007\)</span> and the SE interval of 0.0001, 0.0284) also contains <span class="math inline">\(\beta_1 = 0.0007\)</span>. Will our 95% confidence intervals <em>always</em> contain <span class="math inline">\(\beta_1\)</span>? Let’s see!</p>
</section>
<section id="constructing-more-intervals" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="constructing-more-intervals"><span class="header-section-number">5.2</span> Constructing more intervals</h3>
<p>Let’s construct 50 more confidence intervals for <span class="math inline">\(\beta_1\)</span> using the infer workflow we learned before. We can then compare how many of these confidence intervals “captured” the true value of <span class="math inline">\(\beta_1\)</span>, which we know to be 0.0007. That is to say, “Did the net capture the fish?”.</p>
<p>In the code below, we create a second bootstrap distribution, also with 1,000 bootstrap resamples. Then, using this second bootstrap distribution, we use the percentile method to calculate a 95% confidence interval.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Choice of method
</div>
</div>
<div class="callout-body-container callout-body">
<p>I’ve chosen to use the percentile method as we saw that the intervals had similar results and the percentile method has fewer steps. So, I’m choosing to be efficient! However, since we saw the bootstrap distribution was bell shaped and symmetric, either method would work.</p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>bootstrap_1000_v2 <span class="ot">&lt;-</span> births14 <span class="sc">%&gt;%</span> </span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">specify</span>(<span class="at">response =</span> weight, </span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">explanatory =</span> mage) <span class="sc">%&gt;%</span> </span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">generate</span>(<span class="at">reps =</span> <span class="dv">1000</span>, </span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">type =</span> <span class="st">"bootstrap"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">calculate</span>(<span class="at">stat =</span> <span class="st">"slope"</span>)</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>percentile_ci_2 <span class="ot">&lt;-</span> <span class="fu">get_confidence_interval</span>(bootstrap_1000_v2, </span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>                                         <span class="at">level =</span> <span class="fl">0.95</span>)</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>percentile_ci_2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
    lower_ci upper_ci
       &lt;dbl&gt;    &lt;dbl&gt;
1 -0.0000326   0.0285</code></pre>
</div>
</div>
<p>Notice this interval, also contains <span class="math inline">\(\beta_1\)</span>. Let’s do this again…</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>bootstrap_1000_v3 <span class="ot">&lt;-</span> births14 <span class="sc">%&gt;%</span> </span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">specify</span>(<span class="at">response =</span> weight, </span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">explanatory =</span> mage) <span class="sc">%&gt;%</span> </span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">generate</span>(<span class="at">reps =</span> <span class="dv">1000</span>, </span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">type =</span> <span class="st">"bootstrap"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">calculate</span>(<span class="at">stat =</span> <span class="st">"slope"</span>)</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>percentile_ci_3 <span class="ot">&lt;-</span> <span class="fu">get_confidence_interval</span>(bootstrap_1000_v3, </span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>                                         <span class="at">level =</span> <span class="fl">0.95</span>)</span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>percentile_ci_3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
   lower_ci upper_ci
      &lt;dbl&gt;    &lt;dbl&gt;
1 -0.000133   0.0285</code></pre>
</div>
</div>
<p>Again, our interval contains <span class="math inline">\(\beta_1\)</span>. Let’s scale this up and look at 50 different intervals constructed using this method. <a href="#fig-50-intervals" class="quarto-xref">Figure&nbsp;19</a> visualizes these 50 intervals, where:</p>
<ul>
<li>the true value of <span class="math inline">\(\beta_1 = 0.0007\)</span> is marked with a red, vertical line</li>
<li>each of the intervals is marked with a horizontal line</li>
</ul>
<p>If the interval contained <span class="math inline">\(\beta_1 = 0.0007\)</span>, the line is colored grey. If the interval <strong>did not</strong> contain <span class="math inline">\(\beta_1 = 0.0007\)</span>, the line is colored black.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-50-intervals" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-50-intervals-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="week7-reading2_files/figure-html/fig-50-intervals-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-50-intervals-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;19: 50 percentile-based 95% confidence intervals for the true slope for the relationship between mother’s age and baby’s birth weight, for all babies born in the US in 2014.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Of the 50 95% confidence intervals, 46 of them captured the true value of <span class="math inline">\(\beta_1 = 0.0007\)</span>, whereas 4 of them didn’t. In other words, 46 of our nets caught the fish, and 4 of our nets didn’t.</p>
<p>This is where the “95% confidence level” comes into play: for every 50 95% confidence intervals constructed, we expect that about 95% of them will capture <span class="math inline">\(\beta_1\)</span> and 5% of them won’t. That’s a bit tricky for 50, as 95% of 50 is 47.5. Technically, we can only have either 47 or 48 intervals contain <span class="math inline">\(\beta_1\)</span>, but this should reinforce that the process is not exact. We will not always get 95% of the intervals containing <span class="math inline">\(\beta_1\)</span>, but on average we expect that 95% of them should.</p>
</section>
<section id="connection-to-the-empiracle-rule" class="level3" data-number="5.3">
<h3 data-number="5.3" class="anchored" data-anchor-id="connection-to-the-empiracle-rule"><span class="header-section-number">5.3</span> Connection to the empiracle rule</h3>
<p>You might wonder, why do only 5% of the 95% confidence intervals miss the parameter they are estimating. This reasoning goes back to what you read on the empiracle rule for bell-shaped and symmetric curves. Namely, the rule of thumb that 95% of values will lie within approximately 2 standard deviations of the center of the distribution. The center of a sampling distribution is the value of the parameter. For our example, this value is <span class="math inline">\(\beta_1 = 0.0007\)</span>, the value of the slope for the relationship between mother’s age and baby’s birth weight for all babies born in the US in 2014.</p>
<p><a href="#fig-normal-rule-of-thumb" class="quarto-xref">Figure&nbsp;20</a> displays the sampling distribution of <span class="math inline">\(b_1\)</span>, centered at <span class="math inline">\(\beta_1 = 0.0007\)</span>. Because our sampling distribution is bell-shaped and symmetric, we know that 95% of the slope statistics should fall within 2 standard errors of the center, as noted by the two dashed lines. That means, only 5% of the slope statistics should fall <em>outside</em> this interval. Our sample slope statistic (<span class="math inline">\(b_1\)</span>) is <strong>always</strong> the center of our confidence interval. So, if our sample slope statistic is greater than 2 standard deviations from the center of the sampling distribution, its confidence interval <strong>will not</strong> contain <span class="math inline">\(\beta_1\)</span>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-normal-rule-of-thumb" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-normal-rule-of-thumb-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="week7-reading2_files/figure-html/fig-normal-rule-of-thumb-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-normal-rule-of-thumb-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;20: Rules of thumb about areas under normal curves.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="precise-and-shorthand-interpretation" class="level3" data-number="5.4">
<h3 data-number="5.4" class="anchored" data-anchor-id="precise-and-shorthand-interpretation"><span class="header-section-number">5.4</span> Precise and shorthand interpretation</h3>
<p>Let’s return our attention to 95% confidence intervals. The precise and mathematically correct interpretation of a 95% confidence interval is a little long-winded:</p>
<blockquote class="blockquote">
<p>Precise interpretation: If we repeated our sampling procedure a large number of times, we expect about 95% of the resulting confidence intervals to capture the value of the population parameter.</p>
</blockquote>
<p>This is what we observed in <a href="#fig-50-intervals" class="quarto-xref">Figure&nbsp;19</a>. Our confidence interval construction procedure is 95% <em>reliable</em>. That is to say, we can expect our confidence intervals to include the true population parameter about 95% of the time.</p>
<p>A common but incorrect interpretation is: “There is a 95% probability that the confidence interval contains <span class="math inline">\(\beta_1\)</span>.” Looking at <a href="#fig-50-intervals" class="quarto-xref">Figure&nbsp;19</a>, each of the confidence intervals either does or doesn’t contain <span class="math inline">\(\beta_1\)</span>. In other words, the probability is either 100% or 0%.</p>
<p>So if the 95% confidence level only relates to the reliability of the confidence interval construction procedure and not to a given confidence interval itself, what insight can be derived from a given confidence interval? Loosely speaking, we can think of these intervals as our “best guess” of a plausible range of values for the slope of the relationship between mother’s age and baby’s birth weight <span class="math inline">\(\beta_1\)</span> of <em>all</em> babies born in the US in 2014. It is typical to use the following shorthand summary of the precise interpretation:</p>
<blockquote class="blockquote">
<p>We are 95% “confident” that a 95% confidence interval captures the value of the population parameter. We use quotation marks around “confident” to emphasize that while 95% relates to the reliability of our confidence interval construction procedure, ultimately a constructed confidence interval is our best guess of an interval that contains the population parameter. In other words, it’s our best net.</p>
</blockquote>
<p>So returning to the first confidence interval we calculated, we would interpret this interval as “We are 95% ‘confident’ that the slope of the relationship between mother’s age and baby’s birth weight <span class="math inline">\(\beta_1\)</span> of <em>all</em> babies born in the US in 2014 is between -0.0018 and 0.0285.</p>
</section>
<section id="ci-width" class="level3" data-number="5.5">
<h3 data-number="5.5" class="anchored" data-anchor-id="ci-width"><span class="header-section-number">5.5</span> Width of confidence intervals</h3>
<p>Now that we know how to interpret confidence intervals, let’s go over some factors that determine their width.</p>
<section id="impact-of-confidence-level" class="level4">
<h4 class="anchored" data-anchor-id="impact-of-confidence-level">Impact of confidence level</h4>
<p>One factor that determines confidence interval widths is the pre-specified confidence level. For example, we used 95% confidence intervals for this reading, but we could have equally chosen 85% intervals. A 95% confidence interval created using the percentile method contains 95% of the values in the bootstrap distribution. An 85% confidence interval would only contain 85% of these values, so it would be a <strong>narrower</strong> confidence interval. The quantification of the confidence level should match what many expect of the word “confident.” In order to be more confident in our best guess of a range of values, we need to widen the range of values.</p>
<p>To elaborate on this, imagine we want to guess the forecasted high temperature in Seoul, South Korea on August 15th. Given Seoul’s temperate climate with four distinct seasons, we could say somewhat confidently that the high temperature would be between 50°F - 95°F (10°C - 35°C). However, if we wanted a temperature range we were <em>absolutely</em> confident about, we would need to widen it.</p>
<p>We need this wider range to allow for the possibility of anomalous weather, like a freak cold spell or an extreme heat wave. So a range of temperatures we could be near certain about would be between 32°F - 110°F (0°C - 43°C). On the other hand, if we could tolerate being a little less confident, we could narrow this range to between 70°F - 85°F (21°C - 30°C).</p>
<p>So in order to have a higher confidence level, our confidence intervals must be wider. Ideally, we would have both a high confidence level and narrow confidence intervals. However, we cannot have it both ways. If we want to be more confident, we need to allow for wider intervals. Conversely, if we would like a narrow interval, we must tolerate a lower confidence level.</p>
<blockquote class="blockquote">
<p>The moral of the story is: Higher confidence levels tend to produce wider confidence intervals.</p>
</blockquote>
</section>
<section id="impact-of-sample-size" class="level4">
<h4 class="anchored" data-anchor-id="impact-of-sample-size">Impact of sample size</h4>
<p>Pulling from what we learned about the <em>Central Limit Theorem</em> at the end of the last reading, we know that variability decreases when sample size increases. We quantified the sampling variation of these sampling distributions using their standard deviation, which has that special name: the standard error. So as the sample size increases, the standard error decreases.</p>
<p>Connecting to what you learned in this reading, if we have a large sample size, the spread of the bootstrap distribution will be smaller, which in turn leads to smaller estimated standard errors, and narrower confidence intervals. In <a href="#sec-se-method" class="quarto-xref">Section&nbsp;3.2</a> you saw directly how the standard error is used when calculating a confidence interval.</p>



</section>
</section>
</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-ims" class="csl-entry" role="listitem">
Çetinkaya-Rundel, Mine, and Jo Hardin. 2023. <em>Introduction to Modern Statistics</em>. OpenIntro. <a href="https://openintro-ims.netlify.app/">https://openintro-ims.netlify.app/</a>.
</div>
<div id="ref-kim2020" class="csl-entry" role="listitem">
Kim, Albert Y., Chester Ismay, Starry Zhou, Marium Tapal, Dorothy Bishop, WatanabeSmith, Tobias Rockel, et al. 2020. <em>Moderndive/ModernDive<span>_</span>book: Cleaned Bookdown Code, Typo Fixes, New Tips &amp; Tricks Page</em>. Zenodo. <a href="https://doi.org/10.5281/ZENODO.3932023">https://doi.org/10.5281/ZENODO.3932023</a>.
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© Copyright 2023, Allison Theobold</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/atheobold/stat-313-website/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>This page is built with ❤️ and <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>




</body></html>