{
  "hash": "6135e902ee61aca663fc5d1a787e89ab",
  "result": {
    "markdown": "---\ntitle: \"Introduction to Linear Regression\"\nformat: revealjs\nembed-resources: true\neditor: visual\n---\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n\n::: {style=\"font-size: 2em; color: #000000;\"}\nRelationships Between Variables\n:::\n\n. . .\n\n-   In a statistical model, we generally have one variable that is the output and one or more variables that are the inputs.\n\n::: columns\n::: {.column width=\"40%\"}\n::: {.fragment .fade-in-then-semi-out}\n::: {style=\"font-size: 0.85em;\"}\n-   Response variable\n    -   a.k.a. $y$, dependent\n    -   The quantity you want to understand\n    -   In this class -- always numerical\n:::\n:::\n:::\n\n::: {.column width=\"5%\"}\n:::\n\n::: {.column width=\"55%\"}\n::: {style=\"font-size: 0.85em;\"}\n::: {.fragment}\n-   Explanatory variable\n    -   a.k.a. $x$, independent, explanatory, predictor\n    -   Something you think might be related to the response\n    -   Either numerical or categorical\n:::\n:::\n:::\n:::\n\n## \n\n::: {style=\"font-size: 2em; color: #000000;\"}\nVisualizing Linear Regression\n:::\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](week4-day1_files/figure-revealjs/viz-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n. . .\n\n</br>\n\n::: columns\n::: {.column width=\"40%\"}\n-   The scatterplot has been called the most \"generally useful invention in the history of statistical graphics.\"\n:::\n\n::: {.column width=\"5%\"}\n:::\n\n::: {.column width=\"55%\"}\n-   It is a simple two-dimensional plot in which the two coordinates of each dot represent the values of two variables measured on a single observation.\n:::\n:::\n\n## \n\n::: {style=\"font-size: 2em; color: #000000;\"}\nCharacterizing Relationships\n:::\n\n</br>\n\n::: incremental\n-   Form (e.g. linear, quadratic, non-linear)\n\n-   Direction (e.g. positive, negative)\n\n-   Strength (how much scatter/noise?)\n\n-   Unusual observations (do points not fit the overall pattern?)\n:::\n\n## \n\n::: {style=\"font-size: 2em; color: #000000;\"}\nData for Today\n:::\n\nThe [ncbirths]{style=\"color: #e28743;\"} dataset is a random sample of 1,000 cases taken from a larger dataset collected in North Carolina in 2004.\n\n::: {style=\"font-size: 0.75em;\"}\n> Each case describes the birth of a single child born in North Carolina, along with various characteristics of the child (e.g. birth weight, length of gestation, etc.), the child's mother (e.g. age, weight gained during pregnancy, smoking habits, etc.) and the child's father (e.g. age).\n:::\n\n## \n\n::: {style=\"font-size: 2em; color: #0F4C81;\"}\nYour Turn!\n:::\n\n::: columns\n::: {.column width=\"65%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](week4-day1_files/figure-revealjs/unnamed-chunk-1-1.png){width=100%}\n:::\n:::\n\n:::\n\n::: {.column width=\"5%\"}\n:::\n\n::: {.column width=\"30%\"}\nHow would your characterize this relationship?\n\n-   shape\n-   direction\n-   strength\n-   outliers\n:::\n:::\n\n## \n\n::: {style=\"font-size: 2em; color: #000000;\"}\nWhat if you added another variable?\n:::\n\n. . .\n\n::: columns\n::: {.column width=\"40%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](week4-day1_files/figure-revealjs/unnamed-chunk-2-1.png){fig-align='center' width=960}\n:::\n:::\n\n:::\n\n::: {.column width=\"60%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](week4-day1_files/figure-revealjs/unnamed-chunk-3-1.png){fig-align='center' width=960}\n:::\n:::\n\n:::\n:::\n\n# Summarizing a Linear Relationship\n\n## \n\n::: columns\n::: {.column width=\"20%\"}\n</br> Correlation:\n:::\n\n::: {.column width=\"80%\"}\n> strength and direction of a *linear* relationship between two *quantitative* variables\n:::\n:::\n\n. . .\n\n-   Correlation coefficient between -1 and 1\n-   Sign of the correlations shows direction\n-   Magnitude of the correlation shows strength\n\n## \n\n::: {style=\"font-size: 2em; color: #000000;\"}\nAnscombe Correlations\n:::\n\n::: columns\n::: {.column width=\"65%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](week4-day1_files/figure-revealjs/unnamed-chunk-4-1.png){width=100%}\n:::\n:::\n\n:::\n\n::: {.column width=\"5%\"}\n:::\n\n::: {.column width=\"30%\"}\n::: {style=\"font-size: 0.75em;\"}\nFour datasets, very different graphical presentations\n\n-   same mean and standard deviation in both $x$ and $y$\n-   same correlation\n-   same regression line\n:::\n:::\n:::\n\n. . .\n\n<center>\n\n[For which of these relationships is correlation a reasonable summary measure?]{style=\"font-size: 1.25em; color: #e28743;\"}\n\n## Calculating Correlation in R\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"false\"}\nbirths_post26 <- ncbirths %>% \n  drop_na(weight, weeks) %>% \n  filter(weeks > 26)\n\n\nget_correlation(births_post26, \n                weeks ~ weight)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 1\n    cor\n  <dbl>\n1 0.578\n```\n:::\n:::\n\n\n## \n\n::: {style=\"font-size: 2em; color: #000000;\"}\nThe Importance of Language\n:::\n\n::: incremental\n-   The word \"correlation\" has both a precise mathematical definition and a more general definition for typical usage in English.\n\n-   These uses are obviously related and generally in sync.\n\n-   There are times when these two uses can be conflated and/or misconstrued.\n:::\n\n## \n\n::: columns\n::: {.column width=\"20%\"}\n</br> Linear regression:\n:::\n\n::: {.column width=\"80%\"}\n>  we assume the the relationship between our response variable ($y$) and \nexplanatory variable ($x$) can be modeled with a linear function, plus some random noise\n:::\n:::\n\n. . .\n\n::: {.centered}\n$response = intercept + slope \\cdot explanatory + noise$\n:::\n\n## Writing the Regression Equation\n\n</br>\n\n::: columns\n::: {.column width=\"47%\"}\n::: {.fragment}\n**Population Model**\n\n$y = \\beta_0 + \\beta_1 \\cdot x + \\epsilon$\n\n</br>\n\n$y$ = response\n\n$\\beta_0$ = population intercept\n\n$\\beta_1$ = population slope\n\n$\\epsilon$ = errors / residuals\n:::\n:::\n\n::: {.column width=\"3%\"}\n:::\n\n::: {.column width=\"50%\"}\n::: {.fragment}\n**Sample Model**\n\n$\\widehat{y} = b_0 + b_1 \\cdot x$\n\n</br> \n\n[Why does this equation have a hat on $y$?]{style=\"color: #e28743;\"}\n:::\n:::\n:::\n\n\n# Linear Regression with One Numerical Explanatory Variable\n\n## \n\n::: {style=\"font-size: 2em; color: #000000;\"}\nObtaining Coefficient Estimates\n:::\n\nStep 1: Fit a linear regression\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"false\"}\nweeks_lm <- lm(weight ~ weeks, data = births_post26)\n```\n:::\n\n\n. . .\n\n</br>\n\nStep 2: Obtain coefficient table\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"false\"}\nget_regression_table(weeks_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 7\n  term      estimate std_error statistic p_value lower_ci upper_ci\n  <chr>        <dbl>     <dbl>     <dbl>   <dbl>    <dbl>    <dbl>\n1 intercept   -5.34      0.565     -9.45       0   -6.45    -4.23 \n2 weeks        0.325     0.015     22.2        0    0.296    0.354\n```\n:::\n:::\n\n\n\n## \n\n::: {style=\"font-size: 2em; color: #000000;\"}\nOur focus (for now...)\n:::\n\n<!-- Change to only focus on estimates! -->\n\n![](images/coefficients.jpg)\n\n## \n\n::: {style=\"font-size: 2em; color: #000000;\"}\nEstimated regression equation\n:::\n\n$$\\widehat{y} = b_0 + b_1 \\cdot x$$\n\n. . .\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 7\n  term      estimate std_error statistic p_value lower_ci upper_ci\n  <chr>        <dbl>     <dbl>     <dbl>   <dbl>    <dbl>    <dbl>\n1 intercept   -5.34      0.565     -9.45       0   -6.45    -4.23 \n2 weeks        0.325     0.015     22.2        0    0.296    0.354\n```\n:::\n:::\n\n\n. . .\n\n</br>\n\n<center>\n\n[Write out the estimated regression equation!]{style=\"color: #e28743; font-size: 1.5em;\"}\n\n##  {background-color=\"#b76352\"}\n\n::: columns\n::: {.column width=\"45%\"}\n::: {style=\"font-size: 1.75em; color: #000000;\"}\nHow do you interpret the intercept value of -5.341?\n:::\n\n:::\n\n::: {.column width=\"5%\"}\n:::\n\n::: {.column width=\"45%\"}\n:::{.fragment}\n::: {style=\"font-size: 1.75em; color: #000000;\"}\nHow do you interpret the slope value of 0.325?\n:::\n:::\n:::\n:::\n\n## \n\n::: {style=\"font-size: 2em; color: #000000;\"}\nObtaining Residuals\n:::\n\n</br>\n\n$\\widehat{weight} = -5.341+0.325 \\cdot weeks$\n\n</br>\n\n. . .\n\n[What would the residual be for a pregnancy that lasted 39 weeks and whose baby weighed 7.63 pounds?]{style=\"color: #e28743; font-size: 1.5em;\"}\n\n<!-- ##  -->\n\n<!-- ::: {style=\"font-size: 2em; color: #000000;\"} -->\n<!-- A different explanatory variable -->\n<!-- ::: -->\n\n<!-- ```{r} -->\n<!-- #| code-line-numbers: false -->\n<!-- #| echo: true -->\n\n<!-- weight_gain_lm <- lm(weight ~ gained, data = births_post26) -->\n\n<!-- get_regression_table(weight_gain_lm) -->\n<!-- ``` -->\n\n<!-- . . . -->\n\n<!-- </br> -->\n\n<!-- [Write out this estimated regression equation!]{style=\"color: #e28743; font-size: 1.5em;\"} -->\n\n<!-- ##  -->\n\n<!-- ::: {style=\"font-size: 2em; color: #000000;\"} -->\n<!-- How would you choose which model is better?! -->\n<!-- ::: -->\n\n<!-- . . . -->\n\n<!-- ```{r} -->\n<!-- #| echo: true -->\n<!-- #| code-line-numbers: false -->\n<!-- births_post26 %>%  -->\n<!--   drop_na(weight, gained, weeks) %>%  -->\n<!--   summarize(cor_weeks = cor(weight, weeks),  -->\n<!--             R_sq_weeks = cor_weeks^2,  -->\n<!--             cor_gained = cor(weight, gained), -->\n<!--             R_sq_gained = cor_gained^2) -->\n<!-- ``` -->\n\n# Linear Regression with One Categorical Explanatory Variables\n\n## Step 1: Finding `distinct` levels\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"false\"}\ndistinct(births_post26, habit)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 1\n  habit    \n  <fct>    \n1 nonsmoker\n2 smoker   \n```\n:::\n:::\n\n\n## \n\n::: {style=\"font-size: 1.75em; color: #000000;\"}\nStep 2: Fit a linear regression\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"false\"}\nhabit_lm <- lm(weight ~ habit, data = births_post26)\n```\n:::\n\n\n. . .\n\n</br>\n\n::: {style=\"font-size: 1.75em; color: #000000;\"}\nStep 3: Obtain coefficient table\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"false\"}\nget_regression_table(habit_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 7\n  term          estimate std_error statistic p_value lower_ci upper_ci\n  <chr>            <dbl>     <dbl>     <dbl>   <dbl>    <dbl>    <dbl>\n1 intercept         7.23     0.047    155.     0        7.14     7.32 \n2 habit: smoker    -0.4      0.13      -3.07   0.002   -0.656   -0.145\n```\n:::\n:::\n\n\n. . .\n\n::: {.centered}\n::: {style=\"font-size: 2em;\"}\n🤔\n:::\n:::\n\n## Estimated Regression Equation\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 7\n  term          estimate std_error statistic p_value lower_ci upper_ci\n  <chr>            <dbl>     <dbl>     <dbl>   <dbl>    <dbl>    <dbl>\n1 intercept         7.23     0.047    155.     0        7.14     7.32 \n2 habit: smoker    -0.4      0.13      -3.07   0.002   -0.656   -0.145\n```\n:::\n:::\n\n\n</br> \n\n. . .\n\n$$\\widehat{weight} = 7.23 - 0.4 \\cdot Smoker$$\n\n</br>\n\n. . .\n\n[But what does $Smoker$ represent???]{style=\"color: #e28743; font-size: 1.25em;\"}\n\n## \n\n::: {style=\"font-size: 2em; color: #000000;\"}\nIndicator Variables\n:::\n\n<center>$$\n  \\widehat{y} = b_0 + b_1 \\cdot x\n$$</center>\n\n. . .\n\n::: columns\n::: {.column width=\"40%\"}\n$x$ is a categorical variable with levels:\n\n-   `\"nonsmoker\"`\n-   `\"smoker\"`\n:::\n\n::: {.column width=\"5%\"}\n:::\n\n::: {.column width=\"55%\"}\nWe need to convert to:\n\n-   a \"baseline\" group\n-   \"offsets\" / adjustments to the baseline\n:::\n:::\n\n. . .\n\n[Based on the regression table, what `habit` group was chosen to be the baseline?]{style=\"color: #e28743; font-size: 1.25em;\"}\n\n## A More Intuitive Equation\n\n$$\\widehat{weight} = 7.23 - 0.4 \\cdot 1_{Smoker}(x)$$\n\nwhere \n\n<center>\n\n$1_{smoker}(x) = 1$ if the mother was a `\"smoker\"`\n\n$1_{smoker}(x) = 0$ if the mother was a `\"nonsmoker\"`\n\n## Obtaining Group Means\n\n$$\\widehat{weight} = 7.23 - 0.4 \\cdot 1_{Smoker}(x)$$\n</br>\n\nGiven the equation, what is the estimated mean birth weight for nonsmoking mothers?\n\n</br>\n\nFor smoking mothers?\n\n# Choose Your Adventure\n\n## Statistical Critique\n\n## Midterm Project Proposal\n",
    "supporting": [
      "week4-day1_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}